### ISSUE TITLE
What does `kombu.Consumer` abstract?

### ISSUE THREAD

**Issue by isaacleeai** [celery/kombu#1013]
1. Is `kombu.Consumer` the process / thread that actually calls the `__callback__` and executes the task, or is it merely the parent that spawns children to do the tasks?

2. I need to load some weights to the GPU before a task is enqueued in order to maximize throughput ( loading when task is requested is too slow ). I am planning on doing this by instantiating the threads / processes that will execute the task beforehand with weights loaded on the GPU at their instantiation. This would mean that I would require control over the when such threads / processes spawn, die, and how they are instantiated. Is this at all possible with kombu and celery?

**Comment by thedrow** [comment]
The Consumer class simply abstracts a Consumer.
No threads or processes are involved.

I don't know what `__callback__` is.
You can provide a list of callbacks to the Consumer's constructor and they will be called in order after a message is received.

You are responsible for spawning those and using a Consumer inside of them.
