### ISSUE TITLE
Redis transport visibility timeout does not work without event loop?

### ISSUE THREAD

**Issue by iwinux** [celery/kombu#1025]
In `kombu.transport.redis`:

* `QoS.restore_visible` is called by `MultiChannelPoller.maybe_restore_messages`
* `maybe_restore_messages` is registered in `Transport.register_with_event_loop`
* `register_with_event_loop` is called by `Connection.register_with_event_loop`

Which means, without an event loop, `visibility_timeout` has no effect when using Redis transport. Am I missing anything? Is there any other way to enforce `visibility_timeout`?

**Comment by iwinux** [comment]
Oops, I missed one line in `MultiChannelPoller.get()`: 

https://github.com/celery/kombu/blob/e9e1edf3966803b06a75480c372992a005b64100/kombu/transport/redis.py#L375

**Comment by iwinux** [comment]
Somehow it may never reach that line, though. With the following code (adapted from https://kombu.readthedocs.io/en/latest/userguide/simple.html):

```python
conn = Connection('redis://')
queue = connection.SimpleQueue('myqueue')

while True:
    try:
        msg = queue.get(block=True, timeout=1)
        print(msg.payload)
    except kombu.five.Empty:
        print('empty')
```

During the call path of `queue.get -> Connection.drain_events -> redis.Transport.drain_events -> MultiChannelPoller.get -> handle_event -> Channel._brpop_read`, there is an `Empty` exception raised by `_brpop_read`:

https://github.com/celery/kombu/blob/e9e1edf3966803b06a75480c372992a005b64100/kombu/transport/redis.py#L732-L739

Which is caught in `MultiChannelPoller.get`, but these lines may never reach due to this exception:

https://github.com/celery/kombu/blob/e9e1edf3966803b06a75480c372992a005b64100/kombu/transport/redis.py#L373-L376

**Comment by thedrow** [comment]
It seems like you are correct.
You could call it periodically in a thread.

In any case, Celery 5 will require an event loop for all I/O operations since it's going to be async.
I'm going to close this as won't fix.

If you have a suggestion on how to resolve this issue, please comment and I'll reopen.
