### ISSUE TITLE
Received and deleted unknown message.  Wrong destination without task

### ISSUE THREAD

**Issue by hasib32** [celery/kombu#1028]
I'm trying to implement  publisher/subscriber pattern with Celery/komby and RabbitMQ. Below is my sample code for creating the producer. if i don't specify the **task**  i get the wrong destination error. My question is do i always need to specify the **task** property?

``` python
media_exchange = Exchange('media', 'topic', durable=True)
    video_queue = Queue('video', exchange=media_exchange, routing_key='video')

    with Connection('amqp://myhost') as conn:
        if conn.connect():
            producer = conn.Producer()
            producer.publish(body={
                'name': 'jon doe',
                'email': 'jondoes@testing.com',
                "task": "mailer.tasks.consume_email_process",
                "id": "4cc7438e-afd4-4f8f-a2f3-f46567e7ca77"
            },
                exchange=media_exchange, routing_key='video', retry=True,
                             declare=[video_queue])
```

If i remove the **task** and **id** celery worker gives me this message.

[2019-03-25 21:41:46,715: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?

The full contents of the message body was: body: {'name': 'jon doe', 'email': 'jondoes@testing.com'} (51b)
{content_type:'application/json' content_encoding:'utf-8'
  delivery_info:{'consumer_tag': 'None5', 'delivery_tag': 2, 'redelivered': False, 'exchange': 'media', 'routing_key': 'video'} headers={}}

**Comment by thedrow** [comment]
Why are you using Kombu to publish tasks to Celery?

**Comment by hasib32** [comment]
Hi @thedrow I'm not. If i remove **"task": "mailer.tasks.consume_email_process"** this part then i get the following error. This is my first time working with Celery and Kombu. I'm trying to accomplish rabbitmq publisher/subscriber pattern. Ideally, a micro-service will publish something into RabbitMq and another micro-service will consume it.
```[2019-03-25 21:41:46,715: WARNING/MainProcess] Received and deleted unknown message. Wrong destination?!?
```

**Comment by thedrow** [comment]
So where is Celery involved in this?

**Comment by hasib32** [comment]
I created task in tasks.py. 
``` python
@shared_task(queue="video", bind=True)
def consume_email_process(self):
    print(self.request.email)
    print(self.request.name)
```
Then I was running celery command like this.
`$ celery -A email_service  worker -l info -Q video` 
the command was giving me the error. My question is do I need to have a celery task to consume or I can do other ways?

**Comment by thedrow** [comment]
Then why aren't you using Celery to send the task?
Please read the documentation.

**Comment by hasib32** [comment]
can you please share with me correct documentation link?

**Comment by hasib32** [comment]
I am more concerned about consuming the task. Actually, I have a PHP application. That application is will be publishing the message and my Python application needs to consume it. Is it possible for you to direct me to the correct documentation?

**Comment by thedrow** [comment]
https://github.com/gjedeer/celery-php
Install from master since the last released version is too old.
The link to our documentation is at the README file of each project.
