### ISSUE TITLE
kombu 4.6.0 does not have a changelog

### ISSUE THREAD

**Issue by clokep** [celery/kombu#1049]
What changes were released in version 4.6.0? The changelog just says `-`:

https://github.com/celery/kombu/blob/f4c05ebf185e77778804caaaae4fcbcec259e4a4/Changelog#L7-L14

**Comment by clokep** [comment]
@auvipy Looks like you did this release? Can you shed any light here?

**Comment by auvipy** [comment]
I will add the missing release notes.

**Comment by clokep** [comment]
@auvipy Any update on this? I see that the later releases (4.6.1 through 4.6.3) have changelogs.

I also don't see any tags pushed for these releases.

**Comment by auvipy** [comment]
I willl update them soon

**Comment by clokep** [comment]
@auvipy Any chance of getting this information added? I've avoided updating to 4.6.x without knowing more details about the changes.

**Comment by auvipy** [comment]
ping me again in 2-3 days if I forget to add the changes. https://github.com/celery/kombu/compare/v4.5.0...master

**Comment by matteius** [comment]
@auvipy Did you forget bud?

**Comment by auvipy** [comment]
yes again!! really sorry. but since celery 4.4 is due by 1 week I will complete both this and celery changelog

**Comment by clokep** [comment]
@thedrow FWIW Kombu 4.6.0 still doesn't have a changelog. See https://github.com/celery/kombu/blob/fe5adb539ce9b351ffe3df0719ca281a736b0014/Changelog.rst#460

**Comment by thedrow** [comment]
Oh I missed that.
I'm reopening.

**Comment by clokep** [comment]
Thanks @matusvalo.
