### ISSUE TITLE
Support for SQS DelaySeconds

### ISSUE THREAD

**Issue by ikonst** [celery/kombu#1074]
SQS has a built-in "DelaySeconds" feature that could support Celery's ETA/Countdown feature for up to 15 minutes.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-send-message-with-timer.html

**Comment by auvipy** [comment]
could you send a patch for this?

**Comment by ikonst** [comment]
It's on my radar once I have some free time. Just wanted to record an issue first to gather feedback.

**Comment by edmundlam** [comment]
Hello @auvipy, my colleague @erikaloranger recently monkey-patched our local kombu library to add the `DelaySeconds` to the kombu SQS transport, similar to how the `MessageDeduplicationID` and `MessageGroupId` is handled for fifo queues.

Can we fork and open a PR with a patch for review?

**Comment by auvipy** [comment]
please open and ask me for review
