### ISSUE TITLE
Error: No nodes replied within time constraint.

### ISSUE THREAD

**Issue by lemontree1991** [celery/kombu#1084]
when i run celery status,in the terminal, i got this response,I am pretty sure that celery can work correctly with kombu==4.6.3.

**Comment by matteius** [comment]
Duplicate report of https://github.com/celery/kombu/issues/1087

**Comment by matteius** [comment]
Well I guess you reported it first @lemontree1991 based on the issue numbering, but thats where all the discussion has been.
