### ISSUE TITLE
Postgresql transport password revealed in worker startup log.

### ISSUE THREAD

**Issue by rexroof** [celery/kombu#1085]
it looks like the results: block is sanitized, but not the postgresql url.

```

 -------------- celery@767a90b92f91 v4.3.0 (rhubarb)
---- **** -----
--- * ***  * -- Linux-4.9.125-linuxkit-x86_64-with-debian-9.9 2019-07-08 17:44:10
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         yms_server.background_worker:0x7fab050cf748
- ** ---------- .> transport:   sqla+postgresql://newt:Iengoachangedd4oe2ch@yms-pg/yms
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


```

**Comment by auvipy** [comment]
> Wait, why are you using postgresql as a broker?
> That's not very supported or maintained.
> You're welcome to submit a PR that fixes this issue.
> It probably belongs in the Kombu repository.
> @auvipy What do you think? Should we move the issue?

sqla is re-added to be used as development broker by the request of some apache downstream projects. It's not for production use at all. and yep it seems to be a kombu issue :dagger:

**Comment by thedrow** [comment]
If they want it, they should be the ones to maintain it.
Not us.

**Comment by rexroof** [comment]
thanks for looking at this.

damn, I wish there was some warning that this wasn't officially supported.
 I didn't make this choice, I'm just the ops engineer trying to get
passwords out of our logs.

I did try and do my due diligence to submit a PR to fix this myself.  It
appeared that the problem might be that celery wasn't
calling maybe_sanitize_url() in the right place.  without digging into some
testing my python breadcrumb tracking was failing me.

**Comment by thedrow** [comment]
It's not on the [list ](https://docs.celeryproject.org/en/latest/getting-started/brokers/index.html#broker-overview) so it's not supported.

**Comment by matteius** [comment]
Probably not that hard to ass basic password filtering out of the logging startup messages regardless of backends.

**Comment by matteius** [comment]
Nice, thanks @thedrow  that commit looks good!
