### ISSUE TITLE
kombu 4.6.4 breaks "celery status" cmd with redis broker

### ISSUE THREAD

**Issue by cluster-master** [celery/kombu#1091]
```
redis==3.2.1
celery==4.3.0
kombu==4.6.3
===================
```

celery worker -A...
celery status -A...

celery@host: OK
1 node online.

(kill worker)

`pip install kombu==4.6.4`
(restart worker)

celery status -A...
Error: No nodes replied within time constraint.

whats wrong with redis support in celery and kombu? never got it working flawlessly from the box since 3.X version :(

**Comment by auvipy** [comment]
this is a possible duplicate issue, please check the open 4.6 issues on kombu

**Comment by auvipy** [comment]
in the meantime,  you can stick with kombu==4.6.3 with celery==4.4.0rc3

**Comment by cluster-master** [comment]
Hello Asif! 
thanks for quick response and at all!

will i have any problems if go with kombu==4.6.3 and celery==4.3.0 for now?

**Comment by auvipy** [comment]
you can check I hope that will work.

**Comment by thedrow** [comment]
This should be fixed in the next version of kombu.
@auvipy Please close duplicate issues and refer them to the original one.
