### ISSUE TITLE
Performance regression when moving from kombu 4.2.x -> 4.3.0+ using SQS as broker

### ISSUE THREAD

**Issue by code-haven** [celery/kombu#1102]
We have a project that uses celery(4.1.0) with SQS as the broker. To make it work with Python 3.7, we had to upgrade celery to 4.3.0, kombu to 4.6.4. Tests pass with the new version but seem to significantly slower (~3x).

I have created a repository that demonstrates the regression in performance. A simple echo task being schedule 100 times:
https://github.com/code-haven/celery-sqs-broker-perf
Results from my local setup:
Celery 4.1.0 + Kombu 4.1.0 - `~3s` 
Celery 4.3.0 + Kombu 4.6.4 - `~10s` 

From my observation, messages from the queue are being read in an interval of 1 second, regardless of the number of messages in the queue. This behavior is not seen in celery4.1.0/kombu 4.1.0.

Am I doing something wrong here? I did try changing the value of `polling_interval` - it did not result in tasks being processed faster/slower.

[EDIT]: Sorry for the truckload of edits, the issue is now confirmed to happen with kombu 4.3.0+.

**Comment by code-haven** [comment]
After some more investigation, the slowdown seems to happen when upgrading from kombu `4.2.x` to `4.3.0`.
Celery 4.2.0 + Kombu 4.2.1 seems fine
Celery 4.2.0 + Kombu 4.3.0 sees the slowdown.

**Comment by auvipy** [comment]
what about celery 4.4.0rc3?

**Comment by code-haven** [comment]
@auvipy It's the same with celery 4.4.0rc3 + kombu 4.6.5, tests take `~10s` to complete

**Comment by code-haven** [comment]
@auvipy It would be great if someone could give some directions on fixing this, I would love to pick this up if no-one else is.

**Comment by auvipy** [comment]
can you let us know the performance issues with celery 4.4.2? and trace the performance issues in your system or celery codes?
