### ISSUE TITLE
Impossible to install latest celery and librabbitmq because of kombu dependencies

### ISSUE THREAD

**Issue by kelockhart** [celery/kombu#1112]
It's currently impossible to install both the latest releases of celery and of librabbitmq without micromanaging your kombu and amqp releases, since the latest release of celery requires kombu v4.6.5. Kombu v4.6.5 actually specifies amqp==**2.5.1** (the switch to 2.5.2 was made after the release). The latest release of librabbitmq grabs the latest release of amqp, which is v2.5.2. Trying to install both without explicitly installing amqp=2.5.1 first results in a dependency collision.

**Comment by auvipy** [comment]
this will be fixed shortly with  a new release with celery 4.4 rc3
