### ISSUE TITLE
Support health_check_interval option in broker_transport_options

### ISSUE THREAD

**Issue by kmctown** [celery/kombu#1114]
As a follow-up to #1019 and #1113, update the [hard-coded `health_check_interval`](https://github.com/celery/kombu/blob/master/kombu/transport/redis.py#L1105) to be configurable via `broker_transport_options`.

It also seems that we will want the default to be `25` instead of `30`.

cc: @thedrow

**Comment by jdavisp3** [comment]
Would having the current default be 30 cause the problem to sometimes continue? Still seeing the "error 32" bug on 2d92827746f0f2e5c964d685246836370f14786b.

**Comment by KFoxder** [comment]
@jdavisp3 
> Would having the current default be 30 cause the problem to sometimes continue? Still seeing the "error 32" bug

Per @kmctown 's [comment](https://github.com/celery/kombu/pull/1113#issuecomment-546942030) the number of broken pipes (error 32) should be greatly reduced but not completely eliminated. This issue here, once resolved, should allow us to configure it per our setup. 

> Have an update: it seems to have mostly fixed it but I am still getting some occasional broken pipes, so we are not out of the woods yet. It is greatly reduced, though, at least on my workload. I think the 30 timeout might be too high, and we might want 20-25 per @andymccurdy recommendation over on redis-py. Seems like the best solution is to make the configurable `broker_transport_options` update to control `health_check_interval` and reduce the default to `20` or `25`.

_Originally posted by @kmctown in https://github.com/celery/kombu/pull/1113#issuecomment-546942030_

**Comment by auvipy** [comment]
can we consider this as a blcker ? @thedrow

**Comment by thedrow** [comment]
Yes, this issue is a blocker.

**Comment by auvipy** [comment]
https://github.com/celery/kombu/pull/1122 ?

**Comment by KFoxder** [comment]
@auvipy Just to make sure I understand. It seems that https://github.com/celery/kombu/pull/1122 fixed this:
> It also seems that we will want the default to be 25 instead of 30.

But it didn't allow for custom set `health_check_interval` in the `broker_transport_options`. Is that correct?

**Comment by KFoxder** [comment]
@thedrow @kmctown I took a stab at this. Let me know if I am going down the right path or not.

**Comment by Ashish-Bansal** [comment]
> But it didn't allow for custom set health_check_interval in the broker_transport_options. Is that correct?

Yes, that's right.

I saw https://github.com/celery/kombu/pull/1145 got merged. May we can close this issue now.
