### ISSUE TITLE
py redis 3.3.x compat 

### ISSUE THREAD

**Issue by auvipy** [celery/kombu#1115]
reverting a PR might drop support for py-redis 3.3.x compatibility. this issue is to track it down before the next release of kombu 4.6.x 597d675ca15260794308be5b9641ea7fde9404f4

**Comment by thedrow** [comment]
@auvipy Please avoid blank issues.
This doesn't explain what you meant to do and if you forget to do it, nobody else would be able to pick up the work on it.

**Comment by auvipy** [comment]
OK. good pointer.

**Comment by auvipy** [comment]
according to https://github.com/celery/kombu/compare/4.6.5...master#diff-71927fc9756cfb863f54cf820c01b3ce the revert didn't downgrade the Redis version. The check is for compat. we can keep the check r just remove it to keep 3.3.x only. what say?

**Comment by thedrow** [comment]
Remove.
We already dropped the py-redis 2.x support.

**Comment by auvipy** [comment]
OK thanks
