### ISSUE TITLE
amqp version - 2.5.1 or 2.5.2?

### ISSUE THREAD

**Issue by eranzim** [celery/kombu#1120]
Hi!

The [changelog for kombu 4.6.5](https://docs.celeryproject.org/projects/kombu/en/stable/changelog.html) states that `amqp` version was bumped from 2.5.1 to 2.5.2, however the `METADATA` file still specifies `Requires-Dist: amqp (==2.5.1)`.. So which version should be used?

**Comment by auvipy** [comment]
a new version will be released with updated amqp. it was hardpinned mistakenly.
