### ISSUE TITLE
Consider moving to redislite

### ISSUE THREAD

**Issue by auvipy** [celery/kombu#1135]
https://github.com/yahoo/redislite

**Comment by auvipy** [comment]
https://github.com/antirez/disque-module

**Comment by matteius** [comment]
What motivation do you have for considering redislite over redis in pypi?  I have always used redis from pypi for Redis related integrations and it seems like the most apt choice as it correlates to the same Development team as the Redis server and I haven't had a need to consider other modules other than I also use fakeredis for mocking out the Redis server for unit testing.

**Comment by auvipy** [comment]
this is for getting consensus. you are one user and your use case doesn't mean anything else can be considered. in kombu 5 we might switch to the async version of all the libraries. but if that's really needed or provide better features.

**Comment by jheld** [comment]
So if for async then it should be titled around that for that motivation. aioredis (used by django channels redis) might be a better choice?

Otherwise why redislite?

**Comment by thedrow** [comment]
I agree it's not a good choice as most people aren't using it.
We'd probably use `aioredis` with `trio-asyncio` in Celery 5.

**Comment by jheld** [comment]
Should we close this issue?

**Comment by thedrow** [comment]
I think so.
