### ISSUE TITLE
Please tag releases in the git repository

### ISSUE THREAD

**Issue by stevecj** [celery/kombu#1155]
Since Python distribution packages do not include licenses, and since in our project, we need to include licenses of 3rd party code that we use, our build process retrieves the licenses from source repositories.

In order to get the right license file for the version  that we're using, we generate a version-specific URL to the file, which is normally based on tag name.

This used to be working for kombu but has now stopped working because recent versions do not have tags.

**Comment by auvipy** [comment]
can you elaborate? what exactly is missing from the latest release?

**Comment by thedrow** [comment]
@auvipy There are no tags in the repository since you're not using bumpversion as you should be when releasing.

**Comment by auvipy** [comment]
it was due to a file rename not tag. it's fixed now
