### ISSUE TITLE
Requeuing undeliverable message for queue '{celery}': No consumers.

### ISSUE THREAD

**Issue by pvyParts** [celery/kombu#1186]
# Issue
Kombu throws this error for every task that is action'd by a worker, it appears to be superficial and just fixes it it's self but the log spam is wild;
```[2020-05-04 13:12:21,035: WARNING/MainProcess] Requeuing undeliverable message for queue '{celery}': No consumers.```

[Link to the issue on our repo](https://gitlab.com/allianceauth/allianceauth/-/issues/1229)
[Link to our celery config](https://gitlab.com/allianceauth/allianceauth/-/blob/master/allianceauth/project_template/project_name/celery.py)

# Findings
I did some digging and found [this](https://github.com/celery/kombu/commit/f2970e81f823fca0fea3f5f436b02f24b875d39b) commit that appears to have [changed the prio info saved into Redis](https://github.com/celery/kombu/blob/f2970e81f823fca0fea3f5f436b02f24b875d39b/kombu/transport/redis.py#L782) but doesn't change the [parsing of the data back out](https://github.com/celery/kombu/blob/f2970e81f823fca0fea3f5f436b02f24b875d39b/kombu/transport/redis.py#L747).

# Enviro
We have a fairly simple use case where we use a Redis with a priority queue and a few celery workers.

## Setup
```python
import os
from celery import Celery
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myauth.settings.local')
from django.conf import settings 
app = Celery('myauth')
app.config_from_object('django.conf:settings')
app.conf.broker_transport_options = {
    'priority_steps': list(range(10)), 
    'queue_order_strategy': 'priority', 
}
app.conf.task_default_priority = 5  priority (9)
app.conf.worker_prefetch_multiplier = 1 
app.conf.ONCE = {
    'backend': 'allianceauth.services.tasks.DjangoBackend',
    'settings': {}
}
```
## Testing
I did some local testing in my dev environment and modified[this line](https://github.com/celery/kombu/blob/f2970e81f823fca0fea3f5f436b02f24b875d39b/kombu/transport/redis.py#L782) to confirm, i haven't seen the error the patch was fixing so figure this is the wrong way to go.
```python
    def _q_for_pri(self, queue, pri):
        pri = self.priority(pri)
        if pri:
            return "{}{}{}".format(queue, self.sep, pri)
        return queue
```
Was just using some basic dummy tasks for testing
```python
from celery import shared_task
import time

@shared_task
def long_task_sim():
    print("start")
    time.sleep(15)
    print("end")

@shared_task
def long_task_sim_generator():
    cnt = 0
    while cnt<50:
        long_task_sim.delay()
        cnt += 1
```

**Comment by matusvalo** [comment]
@pvyParts can you provide PR with the fix?

**Comment by rca** [comment]
I just enabled priorities 2 days ago and ran into this issue.  This is great; thanks for the quick fix!

Please note: if there are items in an existing queue that was created prior to this being applied, they will not be processed and just sit in Redis.

**Comment by youtux** [comment]
I was experimenting with priority queues in Celery as well, and by chance I saw that the queue names have a different behaviour depending on the version of Kombu.

Any ETA for the release of a fixed version of kombu?

Also, shouldn't messages in a queue created with an old version of kombu always be visible to a newer version of kombu?
Because it seems to me that tasks with priority created in celery 4.2.2 (kombu 4.3.0) are not visible to instances of celery running at least 4.3 (kombu 4.6.8), and they are just never picked up.

**Comment by auvipy** [comment]
try kombu and celery master plz

**Comment by youtux** [comment]
Just tried kombu and celery master, and indeed the worker can read tasks made with celery 4.2.2 (kombu 4.3.0), but it cannot read tasks made by a celery 4.3.0 (kombu 4.6.8).
