### ISSUE TITLE
Broken kombu.transport.redis.Mutex implementation

### ISSUE THREAD

**Issue by vinayinvicible** [celery/kombu#1190]
Our production system is running celery==4.3.0, kombu==4.5.0 with redis as messaging queue.
I've recently observed that, even with queues having no pending tasks, redis memory consumption is growing everyday.
This is because celery is not restoring unacked messages and this list keeps on growing (because celery worker restarts/crashes).
The reason is because the key unacked_mutex in redis has no TTL set.

**Issue 1:**
https://github.com/celery/kombu/blob/e316313222c03af4a85d8d50a01718f86d7a58d4/kombu/transport/redis.py#L113-L117

The reason unacked_mutex has no TTL is because we set it after inserting the key in redis.
There might have been an issue with key insertion being successful but expiry was never set and also cleanup in `finally` did not run.

**Issue 2:**
https://github.com/celery/kombu/blob/e316313222c03af4a85d8d50a01718f86d7a58d4/kombu/transport/redis.py#L119

There is fallback configured to expire unacked_mutex, if TTL is not configured. It is expecting that redis returns `False` value if TTL is not configured.
But redis returns -1 if key has no TTL and -2 if key does not exist (for Redis >=2.8).

**Proposed Solution:**
Instead of having a custom Mutex implementation, we can modify it to use lock provided by redis-py.

**Comment by auvipy** [comment]
try latest celery or celery from master and report again

**Comment by vinayinvicible** [comment]
@auvipy 
Reported bug is in kombu's Mutex implementation and I don't think it is related to celery version.

**Comment by auvipy** [comment]
feel free to come with the PR.
