### ISSUE TITLE
pidbox.Mailbox._publish doesn't properly use default channel

### ISSUE THREAD

**Issue by tik-stbuehler** [celery/kombu#1201]
It uses the passed (possible `None`) `channel` in `maybe_declare(self.reply_queue(channel))`, it probably should use `chan` instead.

https://github.com/celery/kombu/blob/5cc4a7688201f4d2e53f468734cc2e7cf177fc40/kombu/pidbox.py#L299-L302

**Comment by tik-stbuehler** [comment]
Same problem in `_collect`:

https://github.com/celery/kombu/blob/5cc4a7688201f4d2e53f468734cc2e7cf177fc40/kombu/pidbox.py#L359-L361

**Comment by auvipy** [comment]
what proposed improvement do you have in mind? can you come with a PR and test?
