### ISSUE TITLE
consumer lost while connections and channels are well

### ISSUE THREAD

**Issue by jshen28** [celery/kombu#1220]
I am using kombu 4.2.1 + rabbitmq 3.7.4 + openstack rocky. I sometimes saw some exchange not found errors when openstack server tries to publish to some reply_* exchanges.  The main consume logic is defined here https://github.com/openstack/oslo.messaging/blob/7e406c312a6514e7ae377edb52b9e02b5bf37a7d/oslo_messaging/_drivers/impl_rabbit.py#L1077 and declaration logic is here https://github.com/openstack/oslo.messaging/blob/7e406c312a6514e7ae377edb52b9e02b5bf37a7d/oslo_messaging/_drivers/impl_rabbit.py#L317.

When problem happens, I can see both connection & channel are intact and hence queue declaration will not be performed again. But on the rabbitmq server side, I see no such queues or exchanges.

I can pretty reliably reproduce this problem by add some delays on rabbitmq cluster network interface by tc qdisc add dev ${xxx} root netem delay 70ms 10ms on 2 out of 3 nodes.

My question is: is there some way that I can detect if there are any consumers left on the channel.

**Comment by auvipy** [comment]
can you try the latest kombu?
