### ISSUE TITLE
No module named 'sqs'

### ISSUE THREAD

**Issue by dekoza** [celery/kombu#1224]
I tried using Django and Celery with SQS backend. I also have django-celery-beat installed and configured. Everything based on [cookiecutter-django](https://github.com/pydanny/cookiecutter-django).

After adding periodic task via django-admin I tried lanuching it manually from the panel. I got 500 error with [traceback (gist)](https://gist.github.com/dekoza/4017a69ac0016928ca18c8eb9811b343) saying there's no 'sqs' module.

**Comment by thedrow** [comment]
Please install kombu correctly to use SQS: `pip install kombu[sqs]`.
