### ISSUE TITLE
Question: Celery rabbitmq connection friendly name

### ISSUE THREAD

**Issue by aravindrp** [celery/kombu#1252]
When using celery with RabbitMQ how can we give connection friendly names? I was able to do this in pika following the below issue ticket.

https://github.com/pika/pika/issues/989

How can we do this in celery as it uses kombu?

**Comment by matusvalo** [comment]
The `connection_name` parameter is passed via `client_properties`. In py-amqp this is done as follows:
```python
>>> import amqp
>>> c = amqp.Connection('broker.example.com', client_properties={'connection_name': 'foo'})
>>> c.connect()
```
For kombu it is simpy, just pass the client_properties to py-amqp driver using `transport_options`:

```python
>>> import kombu
>>> c = kombu.Connection('amqp://broker.example.com', transport_options={'client_properties': {'connection_name': 'foo'}})
>>> c.connect()
```
