### ISSUE TITLE
New release 5.1.0

### ISSUE THREAD

**Issue by terrycain** [celery/kombu#1288]
@thedrow I think you were planning on doing a release soon. Or is there a specific list of things to do for a release that I can pr?

**Comment by auvipy** [comment]
he might be very busy until 22nd January. if he can not I will do it on behalf of him

**Comment by terrycain** [comment]
Any update on this?

**Comment by auvipy** [comment]
@thedrow should I release kombu 5.1 today?

**Comment by terrycain** [comment]
@thedrow any update?

**Comment by thedrow** [comment]
I'm off today. I'll reply ASAP and will manage the release process myself.

**Comment by renejahn** [comment]
This seems to be closable as 5.1.0 is available on pypi
