### ISSUE TITLE
Version 5.0.5 downloaded via pip don't match with version on GitHub 

### ISSUE THREAD

**Issue by davidebersani** [celery/kombu#1295]
Hi,
I downloaded via pip Celery and, naturally, kombu with it. I downloaded the 5.0.2 version of kombu.

But I found out that the code is different and don't match with the code on GitHub. In particular I noticed that for the SQS.py file. (kombu/transport/SQS.py). Look at the new_sqs_client for example. It should be part of the 5.0.2 version. 

Why the versions don't match? I need the security token feature for SQS. 

Thank you.

**Comment by thedrow** [comment]
You should upgrade Kombu explictly using `pip install -U kombu` or use `pip install --upgrade-stratagy=eager -U celery`.
