### ISSUE TITLE
SQS transport - support back off policy

### ISSUE THREAD

**Issue by galCohen88** [celery/kombu#1302]
SQS supports managed visibility timeout, this lets us implementing back off policy (for instace exponential policy) which means that time between task failures will dynamically chaned based on number of retries

**Comment by galCohen88** [comment]
Link to PR https://github.com/celery/kombu/pull/1301
Link to docs PR https://github.com/celery/celery/pull/6648

**Comment by vdksoda** [comment]
@galCohen88 Thanks for this PR. As an enhancement would a back-off policy per task be more flexible?
```
broker_transport_options = {
        'predefined_queues': {
            'my-q': {
                'url': 'https://ap-southeast-2.queue.amazonaws.com/123456/my-q',
                'access_key_id': 'xxx',
                'secret_access_key': 'xxx',
                #'backoff_policy': {1: 10, 2: 20, 3: 40, 4: 80, 5: 320, 6: 640},
                #'backoff_tasks': ['svc.tasks.tasks.task1'],
                'backoff_strategies': {
                     'svc.tasks.tasks.task1': {1: 10, 2: 20, 3: 40, 4: 80, 5: 320, 6: 640},
                     'svc.tasks.tasks.task2': {1: 5, 2: 100}
                 }
            }
        }
    }
```

**Comment by galCohen88** [comment]
@vdksoda Good idea, can you please create a new issue for this?

**Comment by vdksoda** [comment]
@galCohen88 Sure. Let me have a go at a PR for this enhancement. I'll target by 9th May and mark you for review.
