### ISSUE TITLE
kombu.utils.objects.cached_property is not thread safe.

### ISSUE THREAD

**Issue by matusvalo** [celery/kombu#1303]
`cached_property` is heavily used in celery but it is causing issues in multi-threaded code since it is not thread safe. We need to change implementation to store data in thread local storage. 
See following PRs/issues as example: https://github.com/celery/celery/issues/4363, https://github.com/celery/celery/pull/5145, https://github.com/celery/celery/pull/6416
There are multiple ways how we can do it:
1. Fix implementation to store data in thread local storage
2. Use 3rd party component - https://github.com/pydanny/cached-property
3. Use std lib implementation https://docs.python.org/3.9/library/functools.html?highlight=s#functools.cached_property. But this requires python >3.8 and needs to be checked whether is thread-safe.

**Comment by thedrow** [comment]
What happened to the issue links?

**Comment by matusvalo** [comment]
Sorry, my mistake. issue links fixed.

**Comment by thedrow** [comment]
stdlib's `cached_property` is [thread-safe](https://github.com/python/cpython/blob/master/Lib/functools.py#L966).
