### ISSUE TITLE
Pool.set_limit is incorrectly stated as defaulting to 200 in the documentation

### ISSUE THREAD

**Issue by Tecktron** [celery/kombu#1313]
In the [documentation](https://docs.celeryproject.org/projects/kombu/en/stable/userguide/pools.html?highlight=set_limit#setting-pool-limits) it states:
>By default every connection instance has a limit of 200 connections.

However in the code, one can see that this is actually being set to `_limit[0]`  which is set as 10 here: 
https://github.com/celery/kombu/blob/master/kombu/pools.py#L15

This is when `limit` is not provided, when `use_global_limit` is set or there has been no call to `set_limit` with a value.
https://github.com/celery/kombu/blob/master/kombu/pools.py#L91
https://github.com/celery/kombu/blob/master/kombu/pools.py#L127 

Maybe I'm missing something here, but it seems that one of these is incorrect.

The documentation also gives the impression that calling `pool.set_limit()` would use this 200 default, which is not true and actually just sets it to 0 as you can see in the code around here:
https://github.com/celery/kombu/blob/master/kombu/pools.py#L136

I'd also like to point out that when `pool.resize` is called from `set_limit`, the additional parameters (which are not documented on set limit anyway) are not passed along. 

Thanks!

**Comment by matusvalo** [comment]
Already fixed in https://github.com/celery/kombu/commit/3704a1c61e802957ed64f61e25106347d5bba856. We need just new release of kombu. To view fixed version see master version in readthedocs.
