### ISSUE TITLE
Activate DeepSource for static analysis

### ISSUE THREAD

**Issue by akshgpt7** [celery/kombu#1329]
As per the changes made in #1320, this issue is regarding discussion on activating DeepSource on this repo.

**Comment by thedrow** [comment]
What are the differences, feature-wise, between DeepSource & DeepCode?

**Comment by akshgpt7** [comment]
DeepSource has a number of added benefits over DeepCode, some of them are:
- Automatic code formatting to comply with the code style (through Transformers).
- Option to Autofix detected issues through one click.
- You can also tailor the analysis by customizing rules to suit your context easily via the dashboard.
- Quick and simple configuration for the project through the config builder.
- DeepSource Python analyzer detects 520 issues as of now (new support being continuously added).
- Less than 5% false positive reports in DeepSource.
- Option to report false positives directly to the team.
