### ISSUE TITLE
DeprecationWarning - SelectableGroups dict interface is deprecated. Use select.

### ISSUE THREAD

**Issue by AbdealiJK** [celery/kombu#1339]
```
venv/lib/python3.7/site-packages/kombu/utils/compat.py:93: DeprecationWarning:

SelectableGroups dict interface is deprecated. Use select.
```

I get this warning when I use kombu with py3.7
Deprecation is documented for importlib-metadata:
https://github.com/python/importlib_metadata/blob/0c86a02fbbbbdc9a888d9f2a149ec0d2cf5e7d2c/CHANGES.rst#v390

**Comment by folkvir** [comment]
Same thing happens when importing my app when using pytest, it does not in production.

Python: 3.6.8
Celery: celery==5.1.2 with kombu==5.1.0

```bash
python_venv/current/lib64/python3.6/site-packages/kombu/utils/compat.py:93: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
    for ep in importlib_metadata.entry_points().get(namespace, [])

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

Tempory Removed until resolution with: 
```python
import warning

warnings.filterwarnings('ignore', 'SelectableGroups dict interface')
# import the module
```

**Comment by auvipy** [comment]
anyone up for a fix?

**Comment by enricodvn** [comment]
This happens for python pior to 3.8, with the need of `importlib_metadata` lib. You can set `importlib_metadata==3.6` in your requirements to stop this warning from happening.

For python >=3.8:

> Users of Python 3.8 and beyond are encouraged to use the standard library module when possible and fall back to importlib_metadata when necessary. 
https://importlib-metadata.readthedocs.io/en/latest/

In the code, it has a comment to remove `importlib_metadata` usage when dropping 3.7 support. Is a PR still necessary?

**Comment by auvipy** [comment]
sure

**Comment by dmick** [comment]
I note that the stdlib documentation also says the dict interface is going away in future: https://docs.python.org/3/library/importlib.metadata.html#entry-points, see "Compatibility Note".  It seems prudent to fix this sooner rather than later in kombu.

**Comment by tgross35** [comment]
@auvipy Is there any chance for a tagged release soon to squash this message on the pypi latest version?

**Comment by auvipy** [comment]
yes within a week or 2 i guess

**Comment by sergeyklay** [comment]
Any chance to get this released?

**Comment by auvipy** [comment]
already released https://github.com/celery/kombu/releases/tag/v5.3.0b1

**Comment by sergeyklay** [comment]
Thank you

**Comment by yarikoptic** [comment]
> already released https://github.com/celery/kombu/releases/tag/v5.3.0b1

it is a "pre-release" and thus by default not installed by `pip` while stating kombu as dependency unless dependency lists this or any other pre-release version (AFAIK). As a result, that release does not "address" the issue for downstream projects. Could there be a "full" 5.3.0 release please?

**Comment by n1ngu** [comment]
> [...] Could there be a "full" 5.3.0 release please?

I understand the 5.3 milestone https://github.com/celery/kombu/milestone/9 is being worked on but its due date by late 2023 is rather bleak. Is it realistic or just a foobar mandatory field for github milestones?

Are all linked issues blockers for a release? Not that a release should be rushed, but is there anything where the community could help?

**Comment by auvipy** [comment]
it is 30th nov, 2022 now. previous year was mistakenly choosen

**Comment by marianhlavac** [comment]
I'm currently in a process of clearing up deprecation warnings reported when running tests, and this is one of the last deprecation warnings I'm getting in our project.

The fix for this issue has been sitting in beta release for almost two years – as @n1ngu suggested, is there any way we can help to have this included in stable release to get rid of deprecation warnings?

**Comment by piotrsynowiec** [comment]
I have the same deprecation warning using pytest. I will appreciate any help to remove it as well.

**Comment by davepeck** [comment]
I'm not proud of it, but I eventually decided to filter this warning. In my `pyproject.toml`:

```toml
[tool.pytest.ini_options]
filterwarnings = ["ignore:SelectableGroups dict interface is deprecated. Use select.:DeprecationWarning"]
```
