### ISSUE TITLE
SQS `ListQueues` permission denied error with predefined_queues

### ISSUE THREAD

**Issue by kshitiz38** [celery/kombu#1340]
According to Celery [documentation](https://docs.celeryproject.org/en/stable/getting-started/brokers/sqs.html) 
> If you want Celery to use a set of predefined queues in AWS, and to never attempt to list SQS queues, nor attempt to create or delete them, pass a map of queue names to URLs using the predefined_queues setting:

However with latest Celery using following code results in a `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListQueues operation: Access to the resource https://queue.amazonaws.com/ is denied.`

```
app = Celery(os.environ['APP_NAME'])
app.conf.update(
    broker = 'sqs://',
    task_default_queue = 'queue-1',
    transport_options={
        'region': os.environ['SQS_REGION'],
        'predefined_queues': {
            'queue-1': {
                'url': os.environ['SQS_BROKER_QUEUE_URL'],
                'access_key_id': os.environ['AWS_ACCESS_KEY_ID'],
                'secret_access_key': os.environ['AWS_SECRET_ACCESS_KEY'],
            }
        }
    },
    result_backend='redis://:{password}@{host}:6379/{db}'.format(
        password=quote(os.environ['REDIS_PASSWORD'], safe=''),
        host=os.environ['REDIS_RESULT_HOST'],
        db=os.environ['REDIS_RESULT_DB']),
    ...
)
```

Environment details
```
boto3==1.14.54
botocore==1.17.63
celery==5.0.5
kombu==5.0.2
pycurl==7.43.0.6
```

My issue seems similar to one reported #1255 but does not resolve on updating/downgrading the libraries and If I use boto3 directly without Celery, I'm able to connect to the queue and retrieve data

Moreover changing `transport_options` to `broker_transport_options` results in a different error `kombu.transport.SQS.UndefinedQueueException: Queue with name 'celery' must be defined in 'predefined_queues'.` even though the default queue name is not celery. I'm unable to identify which is the correct usage since the documentation mentions using `broker_transport_options` while example at [source](https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L53-L72) uses `transport_options`

Thanks

**Comment by kshitiz38** [comment]
Hi sorry, this was a misconfiguration with my environment, sqs support working as intended in latest stable release. Closing this.

**Comment by programmingwithalex** [comment]
@ktzsh Sorry to bring this up after so long, would you mind sharing what your issues was? I'm experiencing a similar issue myself but can't find a solution.
