### ISSUE TITLE
ModuleNotFoundError: No module named 'librabbitmq'

### ISSUE THREAD

**Issue by lowmanisbusy** [celery/kombu#1352]
I had already installed librabbitmq，but when I use  "librabbitmq://guest:guest@localhost:5672//"，it alway raise 
```
    import librabbitmq as amqp
ModuleNotFoundError: No module named 'librabbitmq'
```
what is the problem

**Comment by lordoffreaks** [comment]
Any joy with this?

**Comment by auvipy** [comment]
please use py-amqp instead

**Comment by thedrow** [comment]
Also, this is not a bug. This is a usage question. Please refer to our support channels for help.
