### ISSUE TITLE
Queue name contained reserved prefix 'amq.*'

### ISSUE THREAD

**Issue by gitpushdashf** [celery/kombu#1361]
Hi everyone,

Trying to track down a bug. I'm not sure if it's in Kombu or my code. I don't have a simple bit of code to reproduce this.

Basically, I publish to an producer, and all is fine. I do it a second time, and the declaration blows up. This is only when using rabbitmq and not memory://.

docker-compose-style logs follow. queue_1 is rabbitmq.

```
app  | DEBUG:__main__:handle_request() published to exchange.
queue_1                  | 2021-07-27 23:49:30.112 [error] <0.806.0> Channel error on connection <0.799.0 (172.18.0.4:49922 -> 172.1
8.0.3:5672, vhost: '/', user: 'guest'), channel 1:
queue_1                  | operation queue.declare caused a channel exception access_refused: queue name 'amq.gen-9mfGbXi45mhE5Z_O3LCBfg' contains reserved prefix 'amq.*'
app  | DEBUG:amqp:Channel open
app  | DEBUG:amqp:Closed channel #1
app  | CRITICAL:root:Queue.declare: (403) ACCESS_REFUSED - queue name 'amq.gen-9mfGbXi45mhE5Z_O3LCBfg' contains reserved prefix 'amq.*'
```

I'm using Kombu 5.1.0.

Thank you!

**Comment by gitpushdashf** [comment]
Simplifying this a bit, if I call `maybe_declare(some_queue)` twice, I get this error.

**Comment by gitpushdashf** [comment]
This only happens with the producer's maybe_declare, from what I can tell. `some_queue(conn).declare()` doesn't trigger it.

**Comment by thedrow** [comment]
Please file a new bug report with all the necessary details provided to you by the template to reproduce this issue.
A minimally reproducible test case would be very helpful in this case.
