### ISSUE TITLE
Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database

### ISSUE THREAD

**Issue by ylh23y** [celery/kombu#1362]
Celery in 5.1.2, Kombu in 5.1.0, redis in 3.5.3;  Multitask error  
![00](https://user-images.githubusercontent.com/13464610/127281782-30292730-4a60-40f9-87da-3b9691e983c2.png)
![0](https://user-images.githubusercontent.com/13464610/127281793-daa1746a-940b-40f7-853d-86c34acc7ec8.png)

**Comment by matusvalo** [comment]
Duplicate of #1063
