### ISSUE TITLE
Creating documentation for redis transport module fails

### ISSUE THREAD

**Issue by matusvalo** [celery/kombu#1385]
Following page is empty:
https://docs.celeryproject.org/projects/kombu/en/master/reference/kombu.transport.redis.html

Should contain documentation of redis transport. Creation of this page fails with following error:

```
WARNING: autodoc: failed to import module 'redis' from module 'kombu.transport'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kombu/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kombu/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/kombu/checkouts/latest/docs/../kombu/transport/redis.py", line 267, in <module>
    class PrefixedStrictRedis(GlobalKeyPrefixMixin, redis.Redis):
AttributeError: 'NoneType' object has no attribute 'Redis'
```

**Comment by MahsaSeifikar** [comment]
I have this problem again although the version of `kumbu==5.2.2`!

**Comment by matusvalo** [comment]
> I have this problem again although the version of `kumbu==5.2.2`!

I am able to see it: https://docs.celeryproject.org/projects/kombu/en/v5.2.2/reference/kombu.transport.redis.html

**Comment by andrescodas** [comment]
I just had an error like this.  I didnt have redis installed. `pip install redis` resolved

**Comment by andrescodas** [comment]
I wouldn't do this silently:

https://github.com/celery/kombu/blob/b183f484de677ad0235758ff3bfdeef9fc7aff52/kombu/transport/redis.py#L78-L81

**Comment by MahsaSeifikar** [comment]
Thanks, @andrescodas @matusvalo.
My problem is solved by installing Redis!

**Comment by wolf24ru** [comment]
Today I got exactly the same error from docker container.
Redis was **installed yield**.

```bash
$ pip list | grep -P 'celery|redis|kombu' 
celery                            5.3.1
django-celery-beat                2.5.0
django-celery-results             2.5.1
django-celerybeat-status          0.0.10
kombu                             5.3.1
redis                             5.0.0

```

I couldn't figure out what was wrong for a long time. Then I tried to import redis in a console:
```python
import redis
 ````
To which I got a new error:
```bash
ModuleNotFoundError: No module named 'async_timeout' 
``` 
After installing async_timeout everything worked!
`pip install async-timeout`

Maybe this will help someone.

**Comment by auvipy** [comment]
we don't support redis 5 yet but thanks for the pointer!

**Comment by the-homeless-god** [comment]
> Today I got exactly the same error from docker container. Redis was **installed yield**.
> 
> ```shell
> $ pip list | grep -P 'celery|redis|kombu' 
> celery                            5.3.1
> django-celery-beat                2.5.0
> django-celery-results             2.5.1
> django-celerybeat-status          0.0.10
> kombu                             5.3.1
> redis                             5.0.0
> ```
> 
> I couldn't figure out what was wrong for a long time. Then I tried to import redis in a console:
> 
> ```python
> import redis
> ```
> 
> To which I got a new error:
> 
> ```shell
> ModuleNotFoundError: No module named 'async_timeout' 
> ```
> 
> After installing async_timeout everything worked! `pip install async-timeout`
> 
> Maybe this will help someone.

Thanks, spend a few hours to find your comment.
I hate python :D
