### ISSUE TITLE
Tasks Sporadically Lost in Redis Broker

### ISSUE THREAD

**Issue by herbertli** [celery/kombu#1405]
Hi, we've recently started running celery/kombu in an environment with autoscaling workers and with Redis as a broker. 
What we've noticed is that tasks mysteriously disappear from time to time even though we are using acks_late.

I'm suspecting that they may be getting lost somewhere in the process of moving tasks from `unacked` back onto a queue (after the visibility timeout)

Here's the line of code that schedules this periodic task
https://github.com/celery/kombu/blob/master/kombu/transport/redis.py#L1242

and the function that does the actual restore:
https://github.com/celery/kombu/blob/master/kombu/transport/redis.py#L359-L366

I believe an issue may arise if a worker is in the process of restoring tasks, and receives a SIGTERM. Since `restore_by_tag` isn't pipelining the entire set of Redis commands, tasks may potentially be lost if they are in the middle of being moved.

**Comment by matusvalo** [comment]
I have created a draft PR fixing based on comment

> I believe an issue may arise if a worker is in the process of restoring tasks, and receives a SIGTERM. Since restore_by_tag isn't pipelining the entire set of Redis commands, tasks may potentially be lost if they are in the middle of being moved.

**Comment by matusvalo** [comment]
@herbertli @linar-jether could you please validate the PR which should fix this issue?
