### ISSUE TITLE
Failure to send message to SQS FIFO queue when using `predefined_queues`

### ISSUE THREAD

**Issue by n0061q** [celery/kombu#1449]
# Preconditions
* use SQS transport
* FIFO queue must be created in SQS
* use `predefined_queues` setting (queue name MUST not end with `.fifo` and queue URL naturally ends with `.fifo`) as per [documentation](https://docs.celeryproject.org/projects/kombu/en/stable/reference/kombu.transport.SQS.html#predefined-queues), e.g.
```python
'predefined_queues': {
    'celery': {
        'url': 'https://sqs.us-east-1.amazonaws.com/xxx/queue.fifo',
        'access_key_id': 'a',
        'secret_access_key': 'b',
    }
}
```

# Actual result
Sending any message will fail because it will be missing `MessageGroupId` attribute and it is required for FIFO queues.
This happens because such configuration in `predefined_queues` is not treated as a FIFO queue based on the queue name while the actual queue is FIFO:

https://github.com/celery/kombu/blob/9a91e8b7807aa634031e369f05682df4820766ce/kombu/transport/SQS.py#L372-L382

# Expected result
Since nothing prevents to have a predefined FIFO queue with a name that does not end with `.fifo` the easiest way to fix would be to detect FIFO queues by checking queue URL and not the name (which is just a routing key).

Other way would be to validate the `predefined_queues` and force user to name FIFO queues properly.

**Comment by matusvalo** [comment]
Hi @n0061q, thank you for your report.

> Other way would be to validate the predefined_queues and force user to name FIFO queues properly.

I would rather fix the issue in this way. I think is more clear solution since the name of FIFO queue must end with .fifo based on SQS documentation [1].

[1] https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html

**Comment by n0061q** [comment]
Hi @matusvalo, thanks for the feedback.

I agree that it is more coherent to have queues named according to the convention.
I will adjust the PR accordingly.

I suppose update to the docs is also required?

**Comment by matusvalo** [comment]
> I suppose update to the docs is also required?

Yes please just a short note about it.
