### ISSUE TITLE
Make use of batching for Amazon SQS

### ISSUE THREAD

**Issue by kjoconnor** [celery/kombu#147]
As described [here](http://docs.amazonwebservices.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/throughput.html), using the batch methods of getting/deleting/etc. is the ideal way to increase throughput.  We've found currently the only way to increase SQS throughput is to launch additional celery instances, however it seems like using batching may help as well.  Let me know if I'm way off on that.

Thanks!

**Comment by ask** [comment]
SQS in master supports batching, and it's rewritten using async I/O.
