### ISSUE TITLE
Use typing annotations in Kombu (PEP 484)

### ISSUE THREAD

**Issue by atombrella** [celery/kombu#1485]
Please see https://github.com/celery/celery/issues/7258 for more detail.

I have a branch where I did some work with `com2ann`, and not much else (except importing from `typing`). It's a lot of work to annotate an entire code base, but may help finding potential bugs, and increase readability.
https://github.com/atombrella/kombu/tree/type_annotations

**Comment by auvipy** [comment]
we prefer progressive typing.

**Comment by atombrella** [comment]
> we prefer progressive typing.

So everything at once, rather than adding them incrementally? I'm not really sure I follow what you mean.

**Comment by auvipy** [comment]
I meant incremental by telling progressive :)

**Comment by atombrella** [comment]
> I meant incremental by telling progressive :)

Good :+1: It's also the approach that Certbot followed (I helped with the Apache module).

**Comment by auvipy** [comment]
I am sorry for not providing 100% correct english, it's not my mother tongue

**Comment by auvipy** [comment]
small incremental/gradual changes are better. you don't have to worry about full code base. I can also take some stub of that.

**Comment by atombrella** [comment]
> I am sorry for not providing 100% correct english, it's not my mother tongue

It's not mine either, so no worries :)

> small incremental/gradual changes are better. you don't have to worry about full code base. I can also take some stub of that.

It takes a long time to add them, so that's a good suggestion.

**Comment by auvipy** [comment]
closing in favor of https://github.com/celery/kombu/issues/1511
