### ISSUE TITLE
 KeyError: 'No such transport: '

### ISSUE THREAD

**Issue by Jaraiz91** [celery/kombu#1501]
I am trying to build a docker compose with fastapi, celery and redis
when I build up an error occurs with the Celery container, as follows:

Traceback (most recent call last):
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/kombu/transport/__init__.py", line 57, in resolve_transport
celery_worker    |     transport = TRANSPORT_ALIASES[transport]
celery_worker    | KeyError: ''
celery_worker    |
celery_worker    | During handling of the above exception, another exception occurred:
celery_worker    |
celery_worker    | Traceback (most recent call last):
celery_worker    |   File "/usr/local/bin/celery", line 8, in <module>
celery_worker    |  redis://127.0.0.1:6379/0
celery_worker    | ######################################
celery_worker    | <Celery app.celery_worker at 0x7fb599c56070>
celery_worker    | ######################################
celery_worker    | ######################################
celery_worker    | ######################################
celery_worker    |     sys.exit(main())
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
celery_worker    |     sys.exit(_main())
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/bin/celery.py", line 213, in main
celery_worker    |     return celery(auto_envvar_prefix="CELERY")
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
celery_worker    |     return self.main(*args, **kwargs)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
celery_worker    |     rv = self.invoke(ctx)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
celery_worker    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
celery_worker    |     return ctx.invoke(self.callback, **ctx.params)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
celery_worker    |     return __callback(*args, **kwargs)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
celery_worker    |     return f(get_current_context(), *args, **kwargs)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/bin/base.py", line 134, in caller
celery_worker    |     return f(ctx, *args, **kwargs)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/bin/worker.py", line 343, in worker
celery_worker    |     worker = app.Worker(
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 99, in __init__
celery_worker    |     self.setup_instance(**self.prepare_args(**kwargs))
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 120, in setup_instance
celery_worker    |     self._conninfo = self.app.connection_for_read()
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 808, in connection_for_read
celery_worker    |     return self._connection(url or self.conf.broker_read_url, **kwargs)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 867, in _connection
celery_worker    |     return self.amqp.Connection(
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 181, in __init__
celery_worker    |     if not get_transport_cls(transport).can_parse_url:
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/kombu/transport/__init__.py", line 85, in get_transport_cls
celery_worker    |     _transport_cache[transport] = resolve_transport(transport)
celery_worker    |   File "/usr/local/lib/python3.9/site-packages/kombu/transport/__init__.py", line 66, in resolve_transport
celery_worker    |     raise KeyError(f'No such transport: {transport}')
celery_worker    | KeyError: 'No such transport: '

as far as I could find on the internet this may happen because broker_url may be with " in the env.  I removed them from the env and still gave the same error. So I decided to give broker_url  directly as follows:

app = Celery(__name__)
app.conf.broker_url = 'redis://localhost:6379/0'
app.conf.result_backend = 'redis://localhost:6379/0'

still giving the same problem. I don´t understand why transport variable is empty. Thanks in advance for your suggestions

**Comment by Jaraiz91** [comment]
I am leaving here my requirements.txt just in case:

uvicorn==0.14.0 # https://github.com/encode/uvicorn
pydantic==1.7.4 # https://pydantic-docs.helpmanual.io/
fastapi==0.65.2 # https://github.com/tiangolo/fastapi
starlette==0.14.2 # https://github.com/encode/starlette
python-multipart==0.0.5 # https://github.com/andrew-d/python-multipart
python-dotenv==0.19.0  # https://github.com/theskumar/python-dotenv
SQLAlchemy==1.4.7 # https://www.sqlalchemy.org/
psycopg2==2.9.1 # https://www.psycopg.org/
loguru==0.5.3 # https://github.com/Delgan/loguru
pandas==1.3.3
fastapi-versioning==0.9.1 # https://github.com/DeanWay/fastapi-versioning
fastapi-pagination==0.8.3 # https://github.com/uriyyo/fastapi-pagination
pdf2image==1.16.0 # https://github.com/Belval/pdf2image
opencv-python==4.5.3.56 # https://github.com/opencv/opencv-python
pytesseract==0.3.8 # https://github.com/madmaze/pytesseract
aiofiles == 0.7.0
celery == 5.1.2
redis == 3.5.3
flower == 1.0.0
kombu == 5.1.0

**Comment by saurabhm0284** [comment]
Received Same Error while using Celery with FastAPI.

The issue persist while running the celery worker not only inside the container but also outside it (ubuntu platform).

basically in my .env file I tried with 2 options

BROKER_URL = '.....'
and
CELERY_BROKER_URL = '.....'

In both these cases celery gave the above mentioned exception of :
celery_worker | raise KeyError(f'No such transport: {transport}')
celery_worker | KeyError: 'No such transport: '

To handled just tweaked the variable name slight in the .env file to

CELERY_BROKER_TRANSPORT_URL
(basically added a work TRANSPORT in between so that it does not show any conflict with 'broker_transport_options'...)

But this certainly is the celery issue.

It would be really great if we get a permanent fix to this issue.

Thanks.
