### ISSUE TITLE
Docs DNS Failure

### ISSUE THREAD

**Issue by zekenautilus** [celery/kombu#1503]
Seems like the docs are currently down?

Trying to access at https://docs.celeryproject.org/projects/kombu/en/stable/ results in a `DNS_PROBE_FINISHED_NXDOMAIN`

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/58951029/158413113-86869343-9925-46f0-821d-93b9d30a9de4.png">

**Comment by amchii** [comment]
See https://github.com/celery/celery/issues/7351.

**Comment by zekenautilus** [comment]
docs appear to have (temporarily?) moved here: https://docs.celeryq.dev/en/stable/

per: https://github.com/celery/celeryproject/issues/52#issuecomment-1072945860
