### ISSUE TITLE
Couldn't apply scheduled task task_name: Channel.open: (506) No free channel ids

### ISSUE THREAD

**Issue by chaneyzorn** [celery/kombu#1504]
version: 
python-celery-3.1.19
python-kombu-3.0.30

I noticed that `Connect.ensure_connection` would take no effect (no matter how many times) when `virtual.Transport._avail_channel_ids` exhausted already.  (I presume this issue also exists in the latest version)

Can someone help me how to properly handle recovering from this scenario?

The `try-except Exception` in `celery/beat.py Scheduler.apply_async` is not enough to recover from this scenario.

```
File "/usr/lib/python2.7/site-packages/celery/bin/beat.py", line 79, in run
  return beat().run()
File "/usr/lib/python2.7/site-packages/celery/apps/beat.py", line 83, in run
  self.start_scheduler()
File "/usr/lib/python2.7/site-packages/celery/apps/beat.py", line 112, in start_scheduler
  beat.start()
File "/usr/lib/python2.7/site-packages/celery/beat.py", line 473, in start
  interval = self.scheduler.tick()
File "/usr/lib/python2.7/site-packages/celery/beat.py", line 221, in tick
  next_time_to_run = self.maybe_due(entry, self.publisher)
File "/usr/lib/python2.7/site-packages/celery/beat.py", line 207, in maybe_due
  exc, traceback.format_stack(), exc_info=True)

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
    result = self.apply_async(entry, publisher=publisher)
  File "/usr/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
    **entry.options)
  File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 560, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "/usr/lib/python2.7/site-packages/kombu/transport/mongodb.py", line 92, in __init__
    super(Channel, self).__init__(*vargs, **kwargs)
  File "/usr/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 390, in __init__
    self.connection.channel_max), (20, 10),
SchedulingError: Couldn't apply scheduled task task_name: Channel.open: (506) No free channel ids, current=204, channel_max=65535
```

**Comment by thedrow** [comment]
@auvipy Please avoid closing issues without explaining why they were closed.

**Comment by matteius** [comment]
@chaneyzorn  Are you using celery 3.x?

**Comment by auvipy** [comment]
> @auvipy Please avoid closing issues without explaining why they were closed.

reports using python 2.7 and kombu 3 should be closed. explaining them are waste of maintainers time. please don't reopen issues like this unless they provide proper issues.

**Comment by chaneyzorn** [comment]
@thedrow @auvipy Thx for the reply, the issue is not just ask for free help from coding maintainers, but from the community and myself.

It can help to avoid to waste time to just close the issue, but without facilitating knowledge exchange, the maintainer can only fight alone.

I'm actually trying to make my research more serious and reading codes carefully for a long time.

I'll give a try to use the latest version to reproduce the problem.

**Comment by auvipy** [comment]
> @thedrow @auvipy Thx for the reply, the issue is not just ask for free help from coding maintainers, but for/from the community and myself.
> 
> It can help to avoid to waste time to just close the issue, but without facilitating knowledge exchange, the maintainer can only fight alone.
> 
> I'm actually trying to make my research more serious and reading codes (including latest version) carefully for a long time.
> 
> I'll give a try to use the latest version to reproduce the problem.

thank you. we have a discussion section too in github. lets try latest release and let us know

**Comment by chaneyzorn** [comment]
> @chaneyzorn Are you using celery 3.x?

@thedrow Yes，I'am using celery-3.1.19.

I just found a possible clear path to reproduce this problem with this version，and found a patch https://github.com/celery/kombu/pull/1470 may change the logic. (the change is not too long ago)

I am going to compare the impact of this patch before and after, and whether the problem still exists in the new version

**Comment by auvipy** [comment]
also use https://github.com/celery/py-amqp/releases/tag/v5.1.0

**Comment by chaneyzorn** [comment]
Here are some results that I understand so far.

### Minimal snippet used to track code

tasks.py (celery==5.2.3 kombu==5.2.4 amqp==5.1.0)

```
from celery import Celery

app = Celery("tasks", broker="redis://localhost:6379/0")


@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    # Calls test('hello world') every 1 s.
    sender.add_periodic_task(1, test.s("hello world"))


@app.task
def test(arg):
    print(arg)
```

Start consumer：

```
celery -A tasks worker --loglevel=INFO
```

Start the producer：

```
celery -A tasks beat
```


### A path that can stably reproduce the problem in version 3.x

1. Prepare the broker, then start the producer and consumer, keep running for 10s, and then.
2. Stop the broker and keep it stopped for the next 10 hours.
3. Producers and consumers start printing `Connection refused` exceptions.
4. After about tens of hours, the producer starts to print `No free channel ids` exception.
5. Before the `No free channel ids` exception occurs, restart the broker, and the producer can automatically restore the connection.
6. If the `No free channel ids` exception occurs, **the producer cannot restore the connection even the broker is restarted already**.

### The cause of this problem in version 3.x

The main logic of the producer to publish message is located in kombu/connection.py `Connection.ensure`.

When there is a connection error, the exception is caught and `Connection._do_close_self` is called  to "Close only connection and channel(s), **but not transport**"

https://github.com/celery/kombu/blob/a98382f8b8564efd1e3db79bc38d9c0a8f723392/kombu/connection.py#L448

Then, Connection.ensure_connection is called to reconnect the broker. The calling path is as follows：

```
Connection.ensure_connection
Connection.connect
Connection.connection
Connection._establish_connection()
Connection.transport.establish_connection()         # <== re-use the transport

kombu/transport/virtual/ Transport.establish_connection()
Transport.establish_connection()
Transport.create_channel()
Transport.Channel()
```

Taking redis broker as an example, when trying to reconnect redis, the calling path is as follows：

```
kombu/transport/redis.Channel.__init__
	super(Channel, self).__init__
kombu/transport/virtual.Channel.__init__
	self.channel_id = self.connection._avail_channel_ids.pop()  # <== Transport._avail_channel_ids leaks here
kombu/transport/redis.Channel.__init__
	self.client.info()                                          # same as self.client.ping in latest version
	raise
```

`Transport._avail_channel_ids` have been consumed, but the Channel was not instantiated successfully due to the connection failure.

After adding some debug logs, I can see that `Transport._avail_channel_ids` is monotonically decreasing when broker stoped.

When `Transport._avail_channel_ids` is exhausted, even if the broker is normal at this time, the producer will have no chance to reconnect:

```
try:
	self.channel_id = self.connection._avail_channel_ids.pop()   # <== always failed
except IndexError:
	raise ResourceError(                                         # <== no chance to call redis.Channel.client.ping
		'No free channel ids, current={0}, channel_max={1}'.format(
			len(self.connection.channels),
			self.connection.channel_max), (20, 10),
	)
```

### In the latest version this problem no longer exists

In the latest version, `Transport._used_channel_ids` will also be used to record consumed ids due to connection failures.
(So it doesn't make sense to retry more than 65535 times in `Connection.ensure_connection.retry_over_time`, and of course no one will do it.)

Versions with this [patch](https://github.com/celery/kombu/commit/1c2b9723851db3caa913b8da19d6ccad447f3568) (introduced in v4.0.0) will not have the same problem.

https://github.com/celery/kombu/blob/0282e1419fad98da5ae956ff38c7e87e539889ac/kombu/connection.py#L535

`Connection._do_close_self` is replaced by `Connection.collect`, which calls `Connection._do_close_transport()`

The transport will not be reused after connection failure, so `Transport._used_channel_ids` will also be reset.

After commenting out `self._do_close_transport()`, the problem came back.


------

Since this problem no longer exists in the latest version, I will consider upgrading my environment next.

If my understanding above is inaccurate or worth adding, please advise, thank you.

I'm considering keeping this issue open for another day for any discussion that might be of interest to this issue.

If no other issues are discussed in the future, I will close this issue.

thank you all.
