### ISSUE TITLE
Kombu is very picky about broker url formatting

### ISSUE THREAD

**Issue by cyounkins** [celery/kombu#152]
When using celery...

BROKER_URL = "amqp://autoref:*****@localhost:5672/autoref"    works but 

BROKER_URL = "amqp://autoref:*****@localhost:5672/autoref/" does not (note the ending slash)

This caused me hours of headache :-( Unfortunately I couldn't find the cause of this in the code.

Craig Younkins

**Comment by Lifang13** [comment]
what is the broker_url formatting for aws sqs? 

sqs://aws_id:aws_secret@sqs_host/aws_account?
