### ISSUE TITLE
kombu.transport.SQS.InvalidQueueException: must have a name ending with .fifo

### ISSUE THREAD

**Issue by don1uppa** [celery/kombu#1521]
Appears to be  bug here:

kombu.transport.SQS.InvalidQueueException: Queue with url 'https://sqs.us-east-1.amazonaws.com/xxxxxxx/xxx-sqs-airflow-dev-queue.fifo' must have a name ending with .fifo

This may be fixed , I don't see it in the latest code.   kombu==5.2.4    It is referenced byt the airflow 2.2.5 build.

I was able to work around this my changing the queue name  to end in .fifo.   Why was that made a requirement?

CELERY_CONFIG["broker_transport_options"]["predefined_queues"] = {
    "**sqs-queue.fifo**": {"region": "us-east-1",

**Comment by auvipy** [comment]
can u please elaborate more?

**Comment by don1uppa** [comment]
There was a check in the code which I think has been removed now that needed the queue_name in the code to end in .fifo if the amazon sqs queue also ended in .fifo.

**Comment by thedrow** [comment]
See #1449. This is working as intended.
