### ISSUE TITLE
JSON utils looks redundant

### ISSUE THREAD

**Issue by dobosevych** [celery/kombu#1528]
At top of https://github.com/celery/kombu/blob/master/kombu/utils/json.py. 
We import `import json as stdjson`, but then we try again to `import json` and otherwise do `import simplejson`. This looks like legacy of Python 2.7 and there is no need to support that. I propose to clean top of file and keep only `import json` and remove this `stdjson`.

**Comment by auvipy** [comment]
yes, just using json is alright. simple json is old.
