### ISSUE TITLE
CurlClient isn't used anymore and probably could be deleted

### ISSUE THREAD

**Issue by dobosevych** [celery/kombu#1537]
CurlClient isn't used anymore and it is broken for a lot of time, so probably can be removed[http/curl.py](https://github.com/celery/kombu/tree/master/kombu/asynchronous/http/curl.py). There are several reasons for that
1. It depends on `pycurl` that isn't in any dependencies, so on next code we will receive an error
```
from kombu.asynchronous.http.curl import CurlClient
c = CurlClient()
```
2. I don't see any usage client CurlClient or Client in celery repo

In any case code could be at least cleaned

**Comment by auvipy** [comment]
it was scheduled to removed

**Comment by dobosevych** [comment]
but it isn't in any dependencies already
should I help with code cleaning?

**Comment by auvipy** [comment]
boto sqs?

**Comment by dobosevych** [comment]
```
pip install kombu
```
```
>>> from kombu.asynchronous.http.curl import CurlClient
>>> c = CurlClient()
```
will lead to an error. This I suppose should be fixed or cleaned. What is your suggestion?

**Comment by auvipy** [comment]
https://github.com/celery/kombu/issues/737 check this please

**Comment by spawn-guy** [comment]
check this out, please. https://github.com/celery/kombu/pull/2134 and see if it works for your needs (planned to be in `v5.5`)
