### ISSUE TITLE
Celery's pytest worker fixture fails to start with latest azurestoragequeues broker (5.3.0b1)

### ISSUE THREAD

**Issue by davidbossanyi** [celery/kombu#1585]
Celery's [`celery_worker` pytest fixture](https://docs.celeryq.dev/en/stable/userguide/testing.html#celery-worker-embed-live-worker) fails to start (timeout error) using the latest azurestoragequeues broker. However, the worker starts successfully if the previously failing test is run a second time. This appears to be due to the fact that the `celery` queue already exists when the test is run for the second time. Indeed, manually creating a queue called `celery` before starting any of the worker fixtures resolves the issue. This is using [Azurite](https://github.com/Azure/Azurite) to locally emulate Azure storage for integration testing.

Related to #1468 and possibly #1168 

### Steps to reproduce
I've created a minimal example of this behaviour [here](https://github.com/davidbossanyi/fastapi-celery-example/tree/pytest-celery-azurestoragequeues-bug). Also including the relevant info below:

#### Environment
* Windows 10 (but the same issue occurs in a [CI pipeline running on ubuntu](https://github.com/davidbossanyi/fastapi-celery-example/blob/pytest-celery-azurestoragequeues-bug/.github/workflows/tests.yaml#L13))
* Python 3.10
* Celery, Kombu version 5.3.0b1
* azure-storage-queue version 12.4.0
* pytest version 7.1.2
* [azurite](https://github.com/Azure/Azurite) version 3.18.0

#### docker-compose.yaml
```yaml
version: "3.9"

services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  redis:
    image: redis:alpine
    ports:
      - "8000:6379"
```

#### Test file
```python
import pytest


REDIS_URL = "redis://localhost:8000/0"
AZURESTORAGEQUEUE_URL = "azurestoragequeues://Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==@http://localhost:10001/devstoreaccount1"


@pytest.mark.celery(broker_url=REDIS_URL, result_backend=REDIS_URL)
@pytest.mark.usefixtures("celery_app", "celery_worker")
def test_worker_starts_first_time_using_redis_broker() -> None:
    assert True


@pytest.mark.celery(broker_url=AZURESTORAGEQUEUE_URL, result_backend=REDIS_URL)
@pytest.mark.usefixtures("celery_app", "celery_worker")
def test_worker_fails_to_start_the_first_time_using_azurestoragequeue_broker() -> None:
    assert True


@pytest.mark.celery(broker_url=AZURESTORAGEQUEUE_URL, result_backend=REDIS_URL)
@pytest.mark.usefixtures("celery_app", "celery_worker")
def test_worker_starts_the_second_time_using_azurestoragequeue_broker() -> None:
    assert True
```

#### Run the integration tests
```commandline
docker-compose up -d
poetry run pytest
docker-compose down
```

#### Expected behaviour
All three tests should pass

#### Actual behaviour
The second test fails, but the third test (which is identical) passes. This appears to be because when the third test runs, there is already a queue named `celery` created on the Azure storage account. To confirm this, the queue can be created manually before running the tests, e.g. using
```python
from azure.storage.queue import QueueServiceClient

queue_service_client = QueueServiceClient(
    account_url="http://localhost:10001/devstoreaccount1",
    credential="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==",
)
queue_service_client.create_queue("celery")
```

**Comment by auvipy** [comment]
can you help to provide a fix?

**Comment by davidbossanyi** [comment]
> can you help to provide a fix?

Sure, I think #1586 will do the trick.
