### ISSUE TITLE
Unable to configure connect_timeout and failover at the same time

### ISSUE THREAD

**Issue by intgr** [celery/kombu#1594]
Hi. My use case is this: I want to use Celery with multiple clustered RabbitMQ servers **without** a load balancer in between.

When the first RabbitMQ server is unreachable, Celery should wait until connection timeout and retry connecting to the next server. From the surface it seems like that configuration is possible: I can pass multiple URLs to `kombu.Connection` and there are more settings to fine-tune failover/retry configuration: `max_retries`, `failover_strategy`, etc.

However, this does not seem to work in practice: when connection to the 1st server **timeouts**, Kombu never tries the 2nd server in the list.

When using `Connection.default_channel`, it calls `_extract_failover_opts()`:

```python
    def _extract_failover_opts(self):
        conn_opts = {'timeout': self.connect_timeout}
```

This `timeout` is then passed `Connection.default_channel` -> `_ensure_connection()` -> `retry_over_time(self._connection_factory, ..., timeout=(timeout from above))`

`self._connection_factory()` and `retry_over_time()` use the exact same `connect_timeout` value when connecting. By the time `_connection_factory` raises a TimeoutError, `retry_over_time`'s timeout has also expired. I don't see any way to pass different values for these timeouts.

I also notice that the `Connection.connect()` method hard-codes `max_retries=1`. This method doesn't seem to be called in my usage, but still I have to ask: WHY? Shouldn't the retry and failover policy be up to user configuration?

----

As a solution, I think there should be two separate settings for timeouts: One to set TCP-level timeout for a single connection attempt, and the other timeout for the retry loop in `retry_over_time()`.

**Comment by intgr** [comment]
PR that changed this behavior: https://github.com/celery/kombu/pull/1458

**Comment by auvipy** [comment]
would you mind share failing tests and part of your proposed solution?

**Comment by intgr** [comment]
See #1599 for my first attempt to fix this.
