### ISSUE TITLE
simplejson - AKA (de)serializing bytes data

### ISSUE THREAD

**Issue by dstromberg** [celery/kombu#1604]
It appears that simplejson support has been removed from kombu/utils/json.py .  This feels like a bug to me.

I really want to be able to (de)serialize bytes data!  I have a large REST API that uses Celery+Kombu, and it's going to be pulling teeth to go through and convert all the bytes to str.

If I add simplejson back into kombu/utils/json.py using an environment variable, and the code isn't too awful, would it be merged?

**Comment by auvipy** [comment]
isn't it possible to acheive that using built in json module?

**Comment by dstromberg** [comment]
I could manually convert all my bytes data to str before returning it, but that's not very DRY.  One way would be to base64 before returning, and on the other side de-base64 - two manual steps.  Another would be to assume UTF-8, which would probably work most of the time, but again wants a pair of conversions that aren't very DRY.

I'm working on a largish REST API that sometimes returns with str, sometimes returns with bytes. I'd have to locate all the places I'm trying to return bytes, and convert them to str explicitly.  Finding all the bytes returns is a formidable task, given that the tracebacks do not identify where the source of the problem is.

Please see:
https://stackoverflow.com/questions/73901352/how-might-i-persuade-kombu-to-use-simplejson-instead-of-the-json-module

Thanks!

**Comment by thedrow** [comment]
This is now supported by the JSON serializer.
https://github.com/celery/kombu/blob/a3de6f66c1c62cba5008f078c2df20d97f32dcbe/kombu/utils/json.py#L54-L61
