### ISSUE TITLE
Error using Celery and kombu >= 5.2 with python 3.7

### ISSUE THREAD

**Issue by CartierPierre** [celery/kombu#1614]
https://github.com/celery/kombu/blob/6e0d26d510d9269dec33752455478baf715e311d/kombu/utils/compat.py#L14

The fix import isn't compatible with 

https://github.com/celery/kombu/blob/444aa42d4aecb5e73a1d6bab046bcc8ac8131455/kombu/utils/compat.py#L82

I suppose this is in 5.3 fix but not deployed yet. So I upgraded to python 3.8 and it worked.

**Comment by auvipy** [comment]
this should be fixed in https://github.com/celery/kombu/releases/tag/v5.3.0b2

**Comment by auvipy** [comment]
also you can manually pin import metadata package. but upgrading to python 3.8 is a good idea
