### ISSUE TITLE
SQS transport calls get_queue_url *every* time before receive_message - should cache?

### ISSUE THREAD

**Issue by sparrowt** [celery/kombu#1618]
When using the SQS transport (in my case with celery) I see a *lot* of `GetQueueUrl` AWS API calls (~900 per hour) which seems unnecessary given the queue URL essentially never changes.

As far as I can see this is because:
 - `kombu.transport.SQS.Channel._get_bulk_async` -> `_get_async` -> calls `_get_from_sqs`...
 - ...and `_get_from_sqs` does `queue_url = connection.get_queue_url(queue)` (if you you haven't specified `self.predefined_queues`)

Could `_get_from_sqs` check `self._queue_cache[queue]` instead to save re-fetching the queue URL every time?

There seems to be precedent for this e.g:
 - both `Channel._get_bulk` and `Channel._size` call `_new_queue`...
 - ...which checks `_queue_cache` regardless of whether `self.predefined_queues` exists or not

If the lack of caching is deliberate in this specific case, why is it different from the other cases where `_queue_cache` is used?

I realise that this could be avoided by putting the URLs in `predefined_queues`, but in our environment there are a lot of instances of the application and this extra faff when the discovery from `queue_name_prefix` combined with the queue name works excellently.

**Comment by auvipy** [comment]
I am open for an improvement here

**Comment by sparrowt** [comment]
I've opened https://github.com/celery/kombu/pull/1621 which should fix this
