### ISSUE TITLE
Lib importlib_metadata

### ISSUE THREAD

**Issue by meinreno** [celery/kombu#1620]
https://github.com/celery/kombu/blob/2bdeba1d76c49245b96e21060c33731ccb4d282a/kombu/utils/compat.py#L87

In the Last version of lib importlib_metadata 5.0.0 has removed .get, to solve my problem I have forced install importlib-metadata = "4.13.0".
I will investigate a better solution to commit here.

**Comment by thedrow** [comment]
https://github.com/celery/kombu/commit/de560081d3651844882f3401c8f66f0813043057 should indeed fix the issue.
@meinreno Please comment if you have any other issue with importlib. We will re-open this ticket if that's the case.
