### ISSUE TITLE
Please make a new (beta) release

### ISSUE THREAD

**Issue by mgorny** [celery/kombu#1654]
FWICS 5.3.0b2 is broken with Python 3.10 (`t/unit/utils/test_compat.py::test_entrypoints`) and doesn't support SQLAlchemy 2.0. Could you please make a new release?

**Comment by mgorny** [comment]
Oh, and it's broken with setuptools-66+ too.

**Comment by auvipy** [comment]
you should open a dicussion for this. yeah a new beta release is long overdue and i should be release one soon.
