### ISSUE TITLE
5.2.4: pytz dependency break building from source

### ISSUE THREAD

**Issue by bruno-fs** [celery/kombu#1677]
Building kombu 5.2.4 from sources using setuptools 67 or greater is impossible due to pytz dependency not being formatted correctly.

I see this was already fixed on #1652, but the fix is only available for kombu "beta" releases for 5.3.x

Could we have this fix backported for 5.2.x series?

Thanks in advance!

**Comment by auvipy** [comment]
you can try downgrade setuptools
