### ISSUE TITLE
version 5.3.0b3 changes SQS serialization that breaks existing workers.  

### ISSUE THREAD

**Issue by darkpssngr** [celery/kombu#1678]
Version 5.2.4 used to serialize Decimal and dates to string. Due to this all workers were written with an assumption that it will be string. We also use the payload to send it to other services over http. 
5.3.0b3 has started preserving the type of these and breaks the contract that was in place. Since it's a minor version change is it possible to keep it backward compatible and not change contract?

We wanted to use this version mainly because we could use  DelaySeconds feature of SQS. Earlier we were using eta which was causing issues with visibility in SQS and sometime starving other jobs in the queue since all the eta tasks started running at the same time.

**Comment by auvipy** [comment]
as far I know, we actually fixed a long standing regression

**Comment by darkpssngr** [comment]
Oh it used to preserve the types before?

**Comment by auvipy** [comment]
@last-partizan did your change cause this? can you check please?

**Comment by last-partizan** [comment]
Yes, my change caused this.

It's correct to pass Decimal as Decimal.

@darkpssngr if you want to pass Decimal as string, add this code somewhere before configuring your worker:

```python
from kombu.utils.json import register_type

register_type(Decimal, "decimal", str, str)
```

It will override default decoder for decimal, and will use string.

**Comment by cloutierjo** [comment]
Found out that if your using json.load on the other end you can do this:

```
def object_hook(dct):
    if "__type__" in dct:
        if dct["__type__"] == "datetime":
            return datetime.fromisoformat(dct["__value__"]).strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    return dct

data = json.load(message, object_hook=object_hook)
```

then fill-in all missing format required

**Comment by auvipy** [comment]
I will be more then happy to accept any better fix for this.

**Comment by last-partizan** [comment]
@cloutierjo what are you doing?

You don't supposed to use json.loads manually, this format is for working with celery workers, and you just have to use same celery version for sending a task (client) and for processing a task (worker).

**Comment by cloutierjo** [comment]
In our case it's our functional test, we listen to the queue using pika to validate that the rigth task has been sent but we are not processing it, but I'm sure there is plenty of other use case out there

**Comment by last-partizan** [comment]
@auvipy 

I think this issue may be closed, as there is nothing we can improve on our side.
