### ISSUE TITLE
Version 5.3.02 not available on pypi

### ISSUE THREAD

**Issue by CaueP** [celery/kombu#1687]
Hi there!

I need to update kombu on my project to [version 5.3.02](https://github.com/celery/kombu/blob/main/Changelog.rst#5302) to get the importlib update, but this package version is not available on pypi. Was it released already or not?

**Comment by auvipy** [comment]
it is on pypi https://pypi.org/project/kombu/5.3.0b2/ . the changelog has a typo

**Comment by CaueP** [comment]
> it is on pypi https://pypi.org/project/kombu/5.3.0b2/ . the changelog has a typo

Oh, just noticed that and forgot to close the issue. Thanks!
