### ISSUE TITLE
Confluent Kafka Transport missing ability to pass several botstrap servers

### ISSUE THREAD

**Issue by skonik** [celery/kombu#1688]
Hello. It seems that there's no way to pass multiple servers to confluent kafka transport config. I might be wrong about how it works, but looks like it's because of these lines:
https://github.com/celery/kombu/blob/a3de6f66c1c62cba5008f078c2df20d97f32dcbe/kombu/transport/confluentkafka.py#L324-L327

Created this issue for future PR. Going to fork the repo and resolve it.

**Comment by auvipy** [comment]
I am open to tested fixes

**Comment by skonik** [comment]
I've just opened kafka tests and discovered that we can pass several bootstrap servers in such way: 
https://github.com/celery/kombu/blob/main/t/integration/test_kafka.py#L17-L21

At first glance it wasn't clear how to do it(I'm not familiar with the codebase). Closing the issue. Resolved.
