### ISSUE TITLE
Broken MongoDB transport with `pymongo>=4`

### ISSUE THREAD

**Issue by fmigneault** [celery/kombu#1689]
As stated in the [4.x breaking changes of `pymongo`](
https://github.com/mongodb/mongo-python-driver/blob/acc6605ea119ca62b4d9dbff07b62bbc7c86c3d8/doc/changelog.rst#breaking-changes-in-40), multiple collection methods have been removed, which cause some errors depending on which `celery` command is applied.

An example is `celery status` (others are also causing similar errors), which ends up raising the following:
```python
TypeError: 'Collection' object is not callable. If you meant to call the 'remove' method on a 'Collection' object it is failing because no such method exists.
``` 
that originates from the following call:
https://github.com/celery/kombu/blob/2de7f9f038dd62e097e490cb3fa609067c1c3c36/kombu/transport/mongodb.py#L259-L260

This transport implementation should be updated with the new corresponding collection methods (e.g.: `delete_one` instead of `remove`). Most of the method mappings are introduced in `pymongo==3.0` where the removed methods in 4.x were originally deprecated. The transport should probably perform some kind of check with the installed `pymongo` version for backward support as well.

**Comment by auvipy** [comment]
can you please contribute the compat fixes?

**Comment by auvipy** [comment]
https://github.com/celery/kombu/pull/1536 most probably missed some

**Comment by fmigneault** [comment]
@auvipy 
Yes, I can push some changes for methods where I encounter issues.

**Comment by auvipy** [comment]
ping me after opening the PR

**Comment by fmigneault** [comment]
@auvipy 
See https://github.com/celery/kombu/pull/1694
