### ISSUE TITLE
CI workflow failing: lint (3.10) is trying to use python3.9

### ISSUE THREAD

**Issue by sparrowt** [celery/kombu#1699]
### Problem
Recently the 'CI' workflow has been failing because for some reason the `lint (3.10)` step is trying to find `python3.9`
```
Run tox -v -e flake8 -- -v
flake8: find interpreter for spec PythonSpec(major=3, minor=9)
...
flake8: skipped because could not find python interpreter with spec(s): python3.9
  flake8: SKIP (0.61 seconds)
  evaluation failed :( (0.84 seconds)
Error: Process completed with exit code 255.
```
This seems to be happening on all PRs e.g. [like this](https://github.com/celery/kombu/actions/runs/4728800759/jobs/8390814738)

### Cause
https://github.com/celery/kombu/pull/1663 added python 3.10 to CI and set it as the `python-version` under `lint` in `ci.yaml` but didn't change the `basepython` for `flake8` and friends in tox.ini to match.

Looking back to the change for python 3.9 (4f77faab77bafce288d2baa143e66d4ec870d2eb) we do see that flake8 & friends were moved down a line so I think the same needs to happen here (though it feels odd that we have to specify the same thing in 2 places).

**Comment by auvipy** [comment]
thanks a lot for the investigation

**Comment by sparrowt** [comment]
Np! I was going to open a PR today but I see you already have ❤ #1700

**Comment by stegayet** [comment]
This has been fixed in https://github.com/celery/kombu/pull/1718, thanks a lot for your initial investigation @sparrowt :smile:

**Comment by auvipy** [comment]
thanks both of you
