### ISSUE TITLE
Dependency conflict: Cannot install kombu[sqs]==5.3.0rc1

### ISSUE THREAD

**Issue by james-emerton** [celery/kombu#1737]
> pip install "kombu[sqs]==5.3.0rc1"

    <snip usual pip output>

    INFO: pip is looking at multiple versions of kombu[sqs] to determine which version is compatible with other requirements. This could take a while.
    ERROR: Cannot install boto3, botocore==1.29.143 and kombu[sqs]==5.3.0rc1 because these package versions have conflicting dependencies.
    
    The conflict is caused by:
        kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
        botocore 1.29.143 depends on urllib3<1.27 and >=1.25.4
        kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
        botocore 1.29.142 depends on urllib3<1.27 and >=1.25.4
        kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
        botocore 1.29.141 depends on urllib3<1.27 and >=1.25.4
        kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
        botocore 1.29.140 depends on urllib3<1.27 and >=1.25.4
        kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
        botocore 1.29.139 depends on urllib3<1.27 and >=1.25.4

`botocore` currently pins `urllib3` to `<1.27` while `kombu` requires `urllib3>=2.0.2`. This makes it impossible to install kombo with the `sqs` extra (without forcing an incompatible set of requirements.) Given the widespread use of `boto3` even in the absence of `sqs`, it seems this may be problematic until such time as `botocore` can use `urllib3>=2`.

Is it possible to make `kombu` compatible with earlier versions of `urllib3`?

(I'm currently trying to use such a recent version of kombu because I need the fix in #1620)

**Comment by james-emerton** [comment]
See also: https://github.com/boto/botocore/issues/2926

**Comment by auvipy** [comment]
thanks for the report. part of it already used boto 3 already

**Comment by auvipy** [comment]
https://github.com/celery/kombu/pull/1739

**Comment by auvipy** [comment]
fixed with new release
