### ISSUE TITLE
Starting kombu 5.3.0rc1 installation requires urllib3>=2.02 for SQS extra.

### ISSUE THREAD

**Issue by maciejstromich** [celery/kombu#1743]
Currently Boto doesn't support urllib3>2 https://github.com/boto/botocore/issues/2926

when trying to install kombu > 5.3.0b2 with sqs pip is throwing an installation conflict error:

The conflict is caused by:
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.147 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.146 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.145 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.144 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.143 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.142 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.141 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.140 depends on urllib3<1.27 and >=1.25.4
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"
    botocore 1.29.139 depends on urllib3<1.27 and >=1.25.4

**Comment by maciejstromich** [comment]
I saw that in extras(sqs.txt) it's defined as urllib3>=1.26.16 but when I specifically add urllib3<2 to requirements.txt I end up with
```
ERROR: Cannot install kombu[sqs]==5.3.0rc1 and urllib3<2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3<2
    kombu[sqs] 5.3.0rc1 depends on urllib3>=2.0.2; extra == "sqs"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by auvipy** [comment]
the stable release reduced the requirement
