### ISSUE TITLE
Backwards incompatible change in 5.3.0 (json serialization for datetime and UUID)

### ISSUE THREAD

**Issue by vitorquintanilha** [celery/kombu#1749]
Hello there,

Version 5.3.0 introduces a backwards-incompatible change which modifies how `datetime` and `UUID` objects are serialized. Before, they were serialized as strings. Now they are serialized as custom dicts.

Source of change: https://github.com/celery/kombu/pull/1575

This has an enormous potential to break existing services using kombu (which happened to me). I don't know if Kombu follows [semantic versioning](https://semver.org/) but, if it does, this change should have waited for a major version bump since it introduces an incompatible change to a public API.

If it doesn't, we could at least put a big warning on the changelog explaining the update and the steps to work around the change if needed.

This would avoid having other developers (like myself) wasting time investigating issues caused by this change.

Thanks in advance!

**Comment by auvipy** [comment]
it was actually a bug before. now it works properly. we usually introduce new API's in 5.2,5.3 releases like django does

**Comment by cloutierjo** [comment]
Beg to add more information, I would say current way look way more like a bug to me than string serialization for a datetime or uuid. I can understand for more complex type, but not single value type.

**Comment by auvipy** [comment]
I'm open to accept more improvement in this regard. you can start with failing unit & integration tests :)

**Comment by auvipy** [comment]
should be fixed now with new release https://github.com/celery/kombu/releases/tag/v5.3.1

**Comment by JeffreyCA** [comment]
Yeah I was affected and surprised by this change as well. My project still uses Celery 5.1.2 so didn't expect it to consume the latest version of kombu.

**Comment by LincolnPuzey** [comment]
> we usually introduce new API's in 5.2,5.3 releases like django does

It is true that Django introduces breaking changes in X.1,X.2 versions.
However these are clearly documented as such in the release notes, e.g.
https://docs.djangoproject.com/en/4.2/releases/4.2/#backwards-incompatible-changes-in-4-2
Did kombu make a similar effort? In my opinion, no, the change was listed in a dot point along with every other change for the release: https://docs.celeryq.dev/projects/kombu/en/stable/changelog.html / https://github.com/celery/kombu/releases

Also, speaking as someone who has done several Django upgrades on medium-large projects, these breaking changes are usually restricted to small, obscure parts of the Django API. Any breaking change to a major part of the Django API typically goes through a separate deprecation process:
https://docs.djangoproject.com/en/dev/internals/release-process/#deprecation-policy
which allows developers to adapt their projects as needed before the breaking change arrives.

<hr>

> should be fixed now with new release https://github.com/celery/kombu/releases/tag/v5.3.1

@auvipy Can you please explain how 5.3.1 fixes this issue? As far as I can see, the 5.3.0 changelog still doesn't list this as a breaking change, and the breaking change to the API is still present in 5.3.1. I can't think of any other way this issue could be fixed.

<hr>

To anyone reading this thread in frustration that a non-major celery/kombu upgrade has yet again broken their application, I can only suggest they consider trying https://dramatiq.io/ as an alternative.
Unfortunately, I don't have personal experience with `dramatiq`, so I can't recommend it, but I look forward to the day that I do.

**Comment by auvipy** [comment]
every celery kombu release like 5.1.0, 5.2.0 etc is actually major release like django. that is why though it was a bug it wasn't introduced in a point release. the only issue i see is less visibility in the docs or release note for that. we documented that in celery release notes but sadly that was cleaned up by a automated script we use.

**Comment by loic-simon** [comment]
Isn't it possible to retroactively add a prominent warning on Celery 5.3 release page / change history? We just got bitten by this and this breaking change (even if bug fix) is only barely mentionned in kombu changelog :(
