### ISSUE TITLE
Assigning to cached_property is broken on Python 3.12

### ISSUE THREAD

**Issue by ThiefMaster** [celery/kombu#1804]
This code worked fine before:

```python
$ pip freeze | egrep -i 'celery|kombu'
celery==5.3.4
kombu==5.3.2

$ python
Python 3.12.0 (main, Oct  5 2023, 13:07:56) [GCC 13.2.1 20230826] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from celery import Celery
>>> from celery import Celery
>>> c = Celery()
>>> class MyTask(c.Task): pass
...
>>> c.Task = MyTask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/dev/indico/py3/env-312/lib/python3.12/site-packages/kombu/utils/objects.py", line 37, in __set__
    with self.lock:
         ^^^^^^^^^
AttributeError: 'cached_property' object has no attribute 'lock'
```

It likely  broke because of this change in 3.12:

> The undocumented locking behavior of [cached_property()](https://docs.python.org/3/library/functools.html#functools.cached_property) is removed, because it locked across all instances of the class, leading to high lock contention. This means that a cached property getter function could now run more than once for a single instance, if two threads race. For most simple cached properties (e.g. those that are idempotent and simply calculate a value based on other attributes of the instance) this will be fine. If synchronization is needed, implement locking within the cached property getter function or around multi-threaded access points.

**Comment by ThiefMaster** [comment]
As a workaround in Celery I can do `c.__dict__['Task'] = ...` in my code, but this is quite ugly of course (and no idea if `cached_property` properties are being written to anywhere else as well)

**Comment by tari** [comment]
The Python change is https://github.com/python/cpython/commit/056dfc71dce15f81887f0bd6da09d6099d71f979, for reference.

I think this needs to simply introduce its own lock, rather than reusing the one that it previously got for free (now removed). Not locking would be unsafe because this needs to guarantee that get and set operations won't race, otherwise a set could be lost when it races a get.

**Comment by mnito** [comment]
Based on the PR mentioned above, looks like running the snippet below before importing Celery works around the issue:

```python
import kombu.utils
from threading import RLock

if not getattr(kombu.utils.cached_property, 'lock', None):
    setattr(kombu.utils.cached_property, 'lock', property(lambda _: RLock()))
```

**Comment by ThiefMaster** [comment]
Won't that create a new lock every time `self.lock` is accessed? It'd prevent the main breakage, but not actually do any locking. I think you need to make `lock` a cached_property

**Comment by mnito** [comment]
> Won't that create a new lock every time `self.lock` is accessed? It'd prevent the main breakage, but not actually do any locking. I think you need to make `lock` a cached_property

Ahh good point, I edited the above snippet to set a `cached_property` instead of a `property`. Thanks!

**Comment by bruun** [comment]
Glad to see this issue has been fixed! Would it be possible to release a new version containing this fix in the near future?

**Comment by tari** [comment]
You can follow along with the release process in https://github.com/celery/celery/issues/8560

**Comment by auvipy** [comment]
a new version is released with this fix
