### ISSUE TITLE
5.3.3 broke our sqs celery deployment

### ISSUE THREAD

**Issue by charlietruong-wk** [celery/kombu#1822]
When we updated to 5.3.3, it broke our celery deployment. Our celeryconfig uses the following broker configuration with predefined SQS queues. I'm not sure what the root cause could be. 

If it's helpful, here is what our broker configuration roughly looks like with dummy values.

```
broker_transport_options = {
    "region": "my-aws-region",
    "predefined_queues": {
        "queue1": {"url": "https://sqs....queue1"},
        "queue2": {"url": "https://sqs....queue2"},
    },
}
```

Tasks on queue1 run fine while queue2 do not run at all. Reverting to 5.3.2 fixes our problems.

**Comment by auvipy** [comment]
can you check and relate to this? https://github.com/celery/celery/discussions/8627#discussion-5834322 ?

**Comment by SebCorbin** [comment]
Can relate

**Comment by auvipy** [comment]
this should be now fixed with new release
