### ISSUE TITLE
Connection.ensure does not guarantee operation complete

### ISSUE THREAD

**Issue by dnox** [celery/kombu#193]
I have a problem with ensure function.
For example, i have function Foo() that performed for 20 seconds. I am doing next:
conn.ensure(consumer,
                        Foo,
                        errback=errback,
                        max_retries=999,
                        interval_start=5)()
So if connection lost - it works fine, but if connection lost twice during Foo execution there will be exception.
Problem is in 'got_connection' variable - when connection restored it become 1 and next connection lost just skipped. Is this 'got_connection' really needed?

**Comment by auvipy** [comment]
hope this is resolved
