### ISSUE TITLE
`orjson` as JSON serializer

### ISSUE THREAD

**Issue by Zerotask** [celery/kombu#2027]
> orjson is a fast, correct JSON library for Python. It [benchmarks](https://github.com/ijl/orjson#performance) as the fastest Python library for JSON and is more correct than the standard json library or other third-party libraries. It serializes [dataclass](https://github.com/ijl/orjson#dataclass), [datetime](https://github.com/ijl/orjson#datetime), [numpy](https://github.com/ijl/orjson#numpy), and [UUID](https://github.com/ijl/orjson#uuid) instances natively.
(https://github.com/ijl/orjson)

Is it possible to either replace the current JSON [serializer](https://docs.celeryq.dev/projects/kombu/en/v5.3.7/userguide/serialization.html#serializers) with orjson or add it as an alternative JSON serializer?
It seems that in most cases it's ways faster and more correct than the native json module.

**Comment by thedrow** [comment]
Yes it is possible to register your own serializer.
See [documentation](https://docs.celeryq.dev/projects/kombu/en/stable/userguide/serialization.html#creating-extensions-using-setuptools-entry-points).

**Comment by Zerotask** [comment]
> Yes it is possible to register your own serializer.
> See [documentation](https://docs.celeryq.dev/projects/kombu/en/stable/userguide/serialization.html#creating-extensions-using-setuptools-entry-points).

My suggestion is to replace the current default JSON serializer.
It was not a support question.

**Comment by thedrow** [comment]
We don't want to add another dependency if it is not really required.
I think that whoever wants to use orjson already can and that's good enough.
