### ISSUE TITLE
transport SQS queue_delete() method doesn't actually delete the queue

### ISSUE THREAD

**Issue by ivanprjcts** [celery/kombu#2091]
I wonder why `.queue_delete()` method of SQS channel is not actually deleting the queue. I haven't found any doc or comment related to it. I'm sure there is a good reason for it.

The method [._delete()](https://github.com/celery/kombu/blob/1dddf9949fd763da03128bfa0c96fa92446c0146/kombu/transport/SQS.py#L413) of SQS `Channel` class.

```
    def _delete(self, queue, *args, **kwargs):
        """Delete queue by name."""
        if self.predefined_queues:
            return
        super()._delete(queue)
        self._queue_cache.pop(queue, None)
```

SQS queues may be deleted using boto3 `.delete_queue()`(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/client/delete_queue.html).

It would be great to have some docs/comment about it.

Thank you :)

**Comment by thedrow** [comment]
This is a bug in my opinion. We'd welcome a PR to fix this issue.

**Comment by Nusnus** [comment]
> This is a bug in my opinion. We'd welcome a PR to fix this issue.

Please add me for review for such a PR, thanks 🙏
