### ISSUE TITLE
TypeError: _unpack_version() takes from 1 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by couzhei** [celery/kombu#2092]
[This](https://github.com/celery/celery/issues/9161#issuecomment-2260777725) issue belongs here, I believe.

**Comment by Kaveks** [comment]
the isue is annoying

**Comment by couzhei** [comment]
This [comment](https://github.com/celery/celery/issues/9161#issuecomment-2260777725) suggested a workaround to this, making the last argument of a method of the library itself, a *arg. For now, I wrote a bash script for whenever I create a Python venv (ANYWHERE, even on docker images), I manually edit that part, which is a nasty thing. Hopefully we're not launching soon, so I hope they fix it by that time.
