### ISSUE TITLE
Need solution for kombu and amqp traceback 

### ISSUE THREAD

**Issue by nethajik15** [celery/kombu#2102]
We are getting below traceback in the application. 
We are using below version of kombu, amqp, celery.

celery==5.2.2
amqp==5.1.1
kombu==5.2.4

'Traceback (most recent call last):\n File "/home/recipes/.local/lib/python3.9/site-packages/kombu/connection.py", line 446, in reraise_as_library_errors\n yield\n File "/home/recipes/.local/lib/python3.9/site-packages/kombu/connection.py", line 433, in _ensure_connection\n return retry_over_time(\n File "/home/recipes/.local/lib/python3.9/site-packages/kombu/utils/functional.py", line 312, in retry_over_time\n return fun(args, **kwargs)\n File "/home/recipes/.local/lib/python3.9/site-packages/kombu/connection.py", line 877, in _connection_factory\n self._connection = self._establish_connection()\n File "/home/recipes/.local/lib/python3.9/site-packages/kombu/connection.py", line 812, in _establish_connection\n conn = self.transport.establish_connection()\n File "/home/recipes/.local/lib/python3.9/site-packages/kombu/transport/pyamqp.py", line 199, in establish_connection\n conn = self.Connection(*opts)\n File "/home/recipes/.local/lib/python3.9/site-packages/amqp/connection.py", line 178, in __init_\n self.wait(allowed_methods=[\n File "/home/recipes/.local/lib/python3.9/site-packages/amqp/abstract_channel.py", line 66, in wait\n method_sig, args, content = self.connection._wait_method(\n File "/home/recipes/.local/lib/python3.9/site-packages/amqp/connection.py", line 241, in _wait_method\n channel, method_sig, args, content = read_timeout(timeout)\n File "/home/recipes/.local/lib/python3.9/site-packages/amqp/connection.py", line 330, in read_timeout\n return self.method_reader.read_method()\n File "/home/recipes/.local/lib/python3.9/site-packages/amqp/method_framing.py", line 189, in read_method\n raise m\n File "/home/recipes/.local/lib/python3.9/site-packages/amqp/method_framing.py", line 107, in _next_method\n frame_type, channel, payload = read_frame()\n File"/home/recipes/.local/lib/python3.9/site-packages/amqp/transport.py", line 154, in read_frame\n frame_header = read(7, True)\n File "/home/recipes/.local/lib/python3.9/site-packages/amqp/transport.py", line 283

**Comment by thedrow** [comment]
What is the exception type? When does it occur?
There are not enough details for us to debug this issue.
I'm closing it but feel free to comment with more details and I'll reopen it.
