### ISSUE TITLE
Kombu 5.4.1 not working with Celery[SQS] 5.4.0

### ISSUE THREAD

**Issue by Hawkline451** [celery/kombu#2113]
Celery worker is running but is not picking any messages from the SQS queue.

Kombu 5.4.0 works fine.

**Comment by Nusnus** [comment]
The changes regarding SQS in v5.4.1 were:
* SQS: Fixes #2091 queue_delete() method doesn't actually delete the queue by @ivanprjcts in https://github.com/celery/kombu/pull/2099
* Validate SQS SSL certs by default by @poundifdef in https://github.com/celery/kombu/pull/2094

@Hawkline451 can you please share more info?
Is there any error? Does it sometimes work sometimes doesn’t?

If I had to guess, I’d say it’s the SSL [changes](https://github.com/celery/kombu/pull/2094/files) (`validate_cert` changed from default `false` to default `true`), but the original PR says
> ... I'm running python 3.12.4 and tested with the latest Celery+Kombu from github.

So I am not completely sure.
@ivanprjcts @poundifdef can you please give it a look as well in case I am missing something?

Thank you!

**Comment by imran8294** [comment]
Hi @Nusnus 
Kombu `5.4.1` is not compatible with Celery `5.4.0.` As a result, the messages are not being consumed. Although the Celery workers are initialized, they are unable to retrieve messages from the queue.

With kombu <= `5.4.0` its working as expected.

**Comment by Nusnus** [comment]
> Hi @Nusnus 
> Kombu `5.4.1` is not compatible with Celery `5.4.0.` As a result, the messages are not being consumed. Although the Celery workers are initialized, they are unable to retrieve messages from the queue.
> 
> With kombu <= `5.4.0` its working as expected.  

@thedrow @auvipy 

Fyi.

As this is an SQS only issue I prefer not to yank the last release but revert the PR that caused it (once found) and release a new patch.

**Comment by auvipy** [comment]
Yeah that should work

**Comment by Hawkline451** [comment]
> @Hawkline451 can you please share more info? Is there any error? Does it sometimes work sometimes doesn’t?
> 
> If I had to guess, I’d say it’s the SSL [changes](https://github.com/celery/kombu/pull/2094/files) (`validate_cert` changed from default `false` to default `true`), but the original PR says
> 
> > ... I'm running python 3.12.4 and tested with the latest Celery+Kombu from github.
> 

There is no errors or warnings, we test this running the worker in an EC2 server in debug.

Aditional info
```
boto3==1.35.5
botocore==1.35.5
celery==5.4.0
Django==4.2.13
```

Python 3.11

**Comment by ivanprjcts** [comment]
Hi @Nusnus the error seems to be related to this [commit](https://github.com/celery/kombu/pull/2094) 

I have been doing some tests locally commit by commit using a SQS service, and tasks stopped being consumed at that point.

**Comment by ivanprjcts** [comment]
Hi @Nusnus !
I checked the issue using a local sample celery application using SQS, and it seems to be related to this [commit](https://github.com/celery/kombu/pull/2094).

I fixed it after reverting  -> https://github.com/ivanprjcts/kombu/commits/bugfix/revert-cert-validation/

You can try it using:
`pip install git+https://github.com/ivanprjcts/kombu.git@fe5fb64627f17031799bc98be7cab14155eb0682#egg=kombu`

**Comment by Nusnus** [comment]
> Hi @Nusnus !
> I checked the issue using a local sample celery application using SQS, and it seems to be related to this [commit](https://github.com/celery/kombu/pull/2094).
> 
> I fixed it after reverting  -> https://github.com/ivanprjcts/kombu/commits/bugfix/revert-cert-validation/
> 
> You can try it using:
> `pip install git+https://github.com/ivanprjcts/kombu.git@fe5fb64627f17031799bc98be7cab14155eb0682#egg=kombu`

Thank you!

@poundifdef FYI - if you have a potential fix please submit a PR. If not, we will have to revert the change unfortunately 🙏

**Comment by poundifdef** [comment]
Let me take a look!

**Comment by Nusnus** [comment]
@Hawkline451 
Change reverted in `main`.
New patch version will be released soon.

**Comment by Hawkline451** [comment]
> @Hawkline451 Change reverted in `main`. New patch version will be released soon.

Thanks

**Comment by pranavdxl** [comment]
Any ETA for release?

**Comment by Nusnus** [comment]
> Any ETA for release?

Today 🙂

**Comment by mhdzumair** [comment]
+1

**Comment by Nusnus** [comment]
[v5.4.2](https://github.com/celery/kombu/releases/tag/v5.4.2) Released.
https://pypi.org/project/kombu/5.4.2/

@Hawkline451 @imran8294 @ivanprjcts @poundifdef @pranavdxl @mhdzumair

**Comment by spawn-guy** [comment]
https://github.com/celery/kombu/pull/2323
