### ISSUE TITLE
host-pidbox queues aren't necessary unless fanout is enabled

### ISSUE THREAD

**Issue by j0hnsmith** [celery/kombu#219]
`host-pidbox` queues created when celery is started however they're only used when fanout is enabled, they should only be created when fanout is enabled.

This probably isn't a big deal for most transports however when using SQS these unnecessary queues spam the aws SQS interface, additionally the current SQS fanout support is a failed experiment (apparently it doesn't work).

IRC: #celery

asksol: fanout is the amqp broadcast exchange type
cerberos: what does it do?
asksol: so fanout is just synonym to broadcast, but most people don't know what fanout is
cerberos: ok, so if I'm not using fanout, is there any reason for these host-pidbox queues to be created?
asksol: no
cerberos: so would it be fair to say that celery/kombu should only create these host-pidbox queues if fanout is enabled?
asksol: yes, but I don't have time to maintain the sqs transport
cerberos: this doesn't just affect sqs, there's no reason for host-pidbox queues to be created on *any* broker, unless fanout is enabled?
cerberos: asksol: should I create an issue against celery or kombu?
asksol: kombu
asksol: the virtual transports that is, they do already have a 'supports_fanout' flag
asksol: but it's not very generic, it was implemented for the redis backend and then authors mostly copied that without making it generic

**Comment by ask** [comment]
This is fixed in master
