### ISSUE TITLE
SQS broker url doesn't include queue_name_prefix

### ISSUE THREAD

**Issue by j0hnsmith** [celery/kombu#222]
I'm using a AWS IAM to access the SQS queue, the broker url is `sqs://{user_name}@queue.amazonaws.com/{account_id}/{queue_name}`, the `BROKER_TRANSPORT_OPTIONS['queue_name_prefix']` isn't included in the queue name.

I looked in the `fields` param https://github.com/celery/kombu/blob/master/kombu/connection.py#L560 and it the queue name is in virtual host, but with my account id as well (eg 12345/queue_name) so there's no easy way to insert it (I'm not sure if the queue is supposed to be in virtual host or not).

**Comment by josephclim** [comment]
@j0hnsmith were you able to resolve this issue? I just had an application that behaved like this in production but cannot seem to replicate the issue on local. I'm also using SQS and AWS IAM, but using Celery 3.1.18 and Flask deployed on Elastic Beanstalk. Also I don't set the `BROKER_URL` but leave the broker as `sqs://`

**Comment by Lifang13** [comment]
I am having issues to use sqs. http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html 
this doc did not say what is host name after @

**Comment by auvipy** [comment]
@Lifang13 what is the current status of this with kombu 4.6.x?

**Comment by auvipy** [comment]
so is it actually working?

**Comment by shoaib-mohd** [comment]
Absolutely Yes

**Comment by auvipy** [comment]
thank you! but should we document that as example? if so can you please contribute?

**Comment by shoaib-mohd** [comment]
Yes, You can document it as an example.
[auvipy](https://github.com/auvipy) please tell me, where should I post it as a contribution?

**Comment by auvipy** [comment]
you should be able to find relevant sections in userguide and reference if needed https://github.com/celery/kombu/tree/main/docs

**Comment by shoaib-mohd** [comment]
Hello @auvipy 
I have created a pull request by updating the docs/userguide/connections.rst file.
