### ISSUE TITLE
InconsistencyError, Probably the key ('_kombu.binding.celery') has been removed from the Redis database.

### ISSUE THREAD

**Issue by il-b** [celery/kombu#236]
I have installed Celery v3.0.19 with Redis as MQ backend. Everything was fine right after I set them up, but after a while Celery started throwing an error when `.delay` method was called to add a task to queue.    

``` InconsistencyError:
Cannot route message for exchange 'celery': Table empty or key no longer exists.
Probably the key ('_kombu.binding.celery') has been removed from the Redis database.
```

There is no any googleable solution for this problem. But it seems I fixed it for me by specifying `timeout 0` in my `redis.conf` file. It had 300 set by default in version 2.2.12 that I installed from repo on 12.04.2 Ubuntu Server.  

`timeout n`, where n  > 0 means the idle client will be disconnected after n seconds. Kombu's Redis transport may not be able to handle this kind of disconnection.

**Comment by dcramer** [comment]
I realize this ticket is old, but we're trying to upgrade Sentry to 3.1 and we're hitting this as well. We use a router through an exchange, and it seems (at least w/ Redis) its complaining about a missing queue which shouldn't be used.

```
Traceback (most recent call last):
  File "/Users/dcramer/Development/sentry/src/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/Users/dcramer/Development/sentry/src/sentry/event_manager.py", line 469, in _save_aggregate
    is_regression = self._process_existing_aggregate(group, event, kwargs)
  File "/Users/dcramer/Development/sentry/src/sentry/event_manager.py", line 526, in _process_existing_aggregate
    }, extra)
  File "/Users/dcramer/Development/sentry/src/sentry/buffer/base.py", line 37, in incr
    'extra': extra,
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/celery/app/task.py", line 555, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/messaging.py", line 184, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 521, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 60, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 612, in _lookup
    self.get_table(exchange),
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/redis.py", line 723, in get_table
    raise InconsistencyError(NO_ROUTE_ERROR.format(exchange, key))
InconsistencyError:
Cannot route message for exchange 'counters': Table empty or key no longer exists.
Probably the key ('_kombu.binding.counters') has been removed from the Redis database.
```

Relevant settings:

https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L307

Router:

https://github.com/getsentry/sentry/blob/master/src/sentry/queue/routers.py

Feel free to throw this in a new ticket if it makes sense.

**Comment by gensmusic** [comment]
timeout solution didn't work. I encounter this error every two days!!!!

**Comment by nickjj** [comment]
Timeout doesn't work for me too. More details can be found here https://github.com/celery/celery/issues/2484#issuecomment-156809283.

**Comment by pazooki** [comment]
Did you guys find a solution to this?
<code>
venv/lib/python2.7/site-packages/kombu/transport/redis.py", line 721, in get_table
    raise InconsistencyError(NO_ROUTE_ERROR.format(exchange, key))
SchedulingError: Couldn't apply scheduled task nightly-reservation-check: 
Cannot route message for exchange 'celery': Table empty or key no longer exists.
Probably the key ('_kombu.binding.celery') has been removed from the Redis database.
</code>

**Comment by gensmusic** [comment]
@pazooki  If you are using Redis, try to confirm if your redis is hacked!!! It turns out my issue is caused by someone hacked my Redis because I'm using the default redis configuration.

**Comment by strogonoff** [comment]
Seconding @gensmusic’s comment. Been meaning to write that as well: while debugging this problem I discovered the ‘crackit’ key in Redis, and then it turned out our security groups were not configured while Redis in its default configuration at that version allowed connects from anywhere. (I think newer Redis binds only to localhost by default, though.)

**Comment by yuema** [comment]
This issue happened every week for me, as all the '_kombu.binding' keys were evicted each time. Do you guys have any solution yet? BTW, I don't think my redis server was hacked...

**Comment by nickjj** [comment]
@gensmusic Indeed.

@strogonoff This happened to me as well except in my case I actually had iptables configured to block outside connections to Redis however Docker's iptables rules that are auto-appended combined with Redis bound to 0.0.0.0 and no password (the default) allowed for outside connections.

**Comment by ask** [comment]
Sorry for anyone affected by the security issue.  Someone actually deleting the database would indeed explain why the key is missing :(

It's still an issue that does not have to happen, so celery 4.0 does not actually need the _kombu.binding key to send tasks anymore.

**Comment by pazooki** [comment]
does upgrading to celery 4.0 require any change to my code? or is it just a
pip upgrade?


*Mehrdad Pazooki*, Founder
*Tranquant Inc.*
*mehrdad@tranquant.com <mehrdad@tranquant.com>* | *Tranquant.com
<http://tranquant.com>* | Mobile: (*647) 774-7961 |
<https://ca.linkedin.com/pub/mehrdad-pazooki/55/339/27>*

**Comment by ask** [comment]
It's not released yet, the celery git master branch is release candidate 1.

The change log is not complete, but it shall describe exactly what's required to upgrade:
http://docs.celeryproject.org/en/master/whatsnew-4.0.html

**Comment by pazooki** [comment]
Thanks!


*Mehrdad Pazooki*, Founder
*Tranquant Inc.*
*mehrdad@tranquant.com <mehrdad@tranquant.com>* | *Tranquant.com
<http://tranquant.com>* | Mobile: (*647) 774-7961 |
<https://ca.linkedin.com/pub/mehrdad-pazooki/55/339/27>*

**Comment by razerraz** [comment]
Redis 3.2.1 / Celery 3.1.17 / Django  1.9.8

I'm facing the same issue in my django project using celery and redis ampq 
All scheduled tasks are running well from djcelery, but after a couple of days the gunicorn server used for web frontend do not accept tasks with the same error message.

With rabbitmq, the problem doesn't occur 
Redis can't be hacked, since the site is entirely running without any internet link

I have discovered that just starting a new django instance in shell and queeing a task in it solve the problem.
I just launch this script every 12 hours : 
```
from __future__ import absolute_import, unicode_literals
import os, sys, django
sys.path.append(os.path.dirname(__file__))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")
django.setup()

from core.tasks import do_nothing_task
do_nothing_task.delay()
```

**Comment by Muralidharsetty** [comment]
I know this is pretty OLD thread, and closed. If someone can help me with this, It would be really helpful
@ask Can you please explain what is this used for(_kombu.binding)? or Can you point me to any documentation regarding this. I could not find clear view of this.
Just wondering why celery cannot add it self when this key goes missing, Instead of raising an error.

We are using redis as a broker, and we are still facing this issue a lot.

**Comment by auvipy** [comment]
which version of celery are you using?

**Comment by Muralidharsetty** [comment]
I am using **3.1.16 (Cipater)**

**Comment by auvipy** [comment]
try the latest release.
