### ISSUE TITLE
SQS, IAM profiles and missing security_token parameter

### ISSUE THREAD

**Issue by andresriancho** [celery/kombu#239]
AWS provides something called [instance profiles](http://docs.aws.amazon.com/IAM/latest/UserGuide/instance-profiles.html), which is the recommended way to give an EC2 instance access to other AWS services, such as SQS.

When using IAM profiles, the access and secret key are stored in the EC2 instance meta-data, where they can be retrieved by boto; and actually boto knows how to retrieve and use them.

When using IAM profiles, boto needs three things:
- Access key
- Secret key
- Security token

Instead of the "regular" access and secret key.

Kombu's SQS transport, more specifically the [_aws_connect_to](https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L309) method doesn't support instance profiles, because the security token is not passed to the SQSConnection.
# How this works in boto

Working example:

``` python
>>> from boto import provider
>>> boto_creds = provider.Provider('aws')
>>> SQSConnection(aws_access_key_id=boto_creds.access_key,
aws_secret_access_key=boto_creds.secret_key, 
security_token=boto_creds.security_token).get_all_queues()
[Queue(https://queue.amazonaws.com/334918212912/prod-default)]
```

Not working because of the missing security token:

``` python
>>> SQSConnection(aws_access_key_id=boto_creds.access_key, 
aws_secret_access_key=boto_creds.secret_key).get_all_queues()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/boto/sqs/connection.py", line 338, in get_all_queues
    return self.get_list('ListQueues', params, [('QueueUrl', Queue)])
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1049, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.SQSError: SQSError: 403 Forbidden
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
<Error><Type>Sender</Type><Code>InvalidClientTokenId</Code>
<Message>The security token included in the request is invalid.</Message>
<Detail/></Error><RequestId>a3fd1243-0f8f-5a7c-bd32-587f15af9d51</RequestId></ErrorResponse>
```

Working because boto takes all information from the instance metadata and uses it:

``` python
>>> SQSConnection().get_all_queues()
[Queue(https://queue.amazonaws.com/334918212912/prod-default)]
>>>
```
# How the code should look in kombu

``` python
    def _aws_connect_to(self, fun, regions):
        conninfo = self.conninfo
        region = self._get_regioninfo(regions)
        return fun(region=region,
                   aws_access_key_id=conninfo.userid,
                   aws_secret_access_key=conninfo.password,
                   security_token=conninfo.security_token,
                   port=conninfo.port)
```
# Questions

I'm willing to patch this, unittest it, etc. but I need some guidance:
- Where should this security token be added? Is this something you would like to see in Celery's BROKER_URL or in BROKER_TRANSPORT_OPTIONS?
- Another option is to have a configuration parameter that means: "Let boto find the credentials from any of the known sources it has" (which is the `SQSConnection()` example above).

Let me know what you think about all this. For now I think I'll create a fork and use that in my environment, but would like to see this in kombu's master branch so others don't waste their time debugging this issue and re-implementing what I'm about to do.

**Comment by tuky** [comment]
andres solution should be the way to configure the credentials, because environment vars are not best practice: http://boto3.readthedocs.org/en/latest/guide/configuration.html?highlight=role#best-practices-for-configuring-credentials. i know, celery kombu is still boto2, but the best practices should still apply. in fact, it is already possible: just configure `BROKER_URL = 'sqs://'` and nothing else (i.e. no env vars `AWS_ACCESS_KEY_ID` or `AWS_SECRET_ACCESS_KEY`). boto then gets the AWS credentials automatically from meta server via ec2 role (ec2 instance needs a role). i think this should be documented.

**Comment by jbkkd** [comment]
@tuky have you tested that? I just tried this and received an "AccessDenied" error:

"Access to the resource https://queue.amazonaws.com/ is denied"

**Comment by tuky** [comment]
yes, we use this in production. your EC2 instance needs an IAM role which has acces to SQS.

**Comment by gavihs** [comment]
I am using celery 4.1.1 along with Airflow 1.10 and I am getting SQS access denied as the token is not getting generated
Can someone help me with this?

**Comment by auvipy** [comment]
@tuky what is the current status of this?

**Comment by tuky** [comment]
It's still working for us as described. However, I found out by chance yesterday, that the S3Backend does not support credential configuration via IAM instance role. It's raising an assertion, if not explicitly provided with an access key.

**Comment by auvipy** [comment]
so should we close this or update the issue with the remaining part you noticed?

**Comment by tuky** [comment]
personally i would close it. the docs also explain, how to use the instance profile:

> If you are using IAM roles on instances, you can set the BROKER_URL to: sqs:// and kombu will attempt to retrieve access tokens from the instance metadata.

i will consider creating a separate issue for the s3 backend.
