### ISSUE TITLE
Reduce unique column size to support utf8mb4

### ISSUE THREAD

**Issue by ericbuehl** [celery/kombu#265]
As noted in an outstanding bug in django-celery, switching mysql default encoding to utf8mb4 causes key length errors.  https://github.com/celery/django-celery/issues/259

https://github.com/ericbuehl/kombu/commit/39f25dde8c78a09165c2df38542bfa6fc58b9174 is a fix that works for me.  Is this an acceptable solution?  If so, I can open a pull request.

**Comment by ask** [comment]
Using SQL as a broker is no longer supported as we don't have the resources to maintain it :(
