### ISSUE TITLE
Pruning of old messages (Django DB: djkombu_message)

### ISSUE THREAD

**Issue by mwaterfall** [celery/kombu#276]
With Django's DB as the broker, will old message records be pruned? And if so, after how long?

**Comment by blueyed** [comment]
Just out of curiousity: I've noticed that the messages table was huge in my Sentry installation (https://github.com/getsentry/sentry/issues/1474), and nearly all of them were not hidden.
Are messages meant to be hidden after they've been processed?

Apart from that, I've changed the method / `BROKER_URL` later (as per Sentry's recommendations).

Maybe I wasn't running the workers for a longer time, when the DB method was used - I cannot recall.

**Comment by ask** [comment]
Using SQL as a broker is no longer supported, as we don't have the resources to maintain it :(
