### ISSUE TITLE
complete_send.py doesn't automatically create exchange; kombu doesn't report soft connection error

### ISSUE THREAD

**Issue by ngie-eign** [celery/kombu#285]
I tried running complete_send.py from master (actually https://github.com/yaneurabeya/kombu/blob/master/examples/complete_send.py) after a peer of mine reported an issue with the exchange example not working, and I noticed that it doesn't appear to work today in two ways:
1. It doesn't automatically create the exchange, even though it should.
2. It doesn't error out when connecting, which in theory it could/should.

The error was reported in the rabbitmq log like so:

<pre>
=ERROR REPORT==== 10-Dec-2013::17:39:40 ===
connection <0.14302.0>, channel 1 - soft error:
{amqp_error,not_found,"no exchange 'kombu_demo' in vhost '/'",'basic.publish'}
</pre>

- The OS is CentOS 6.4.
- The python version is 2.7.5
- The rabbitmq version is 3.1.5-1
- The amqp library version is 1.3.3
- The amqplib library version is 1.0.2.

Nothing has been changed from the default rabbitmq configuration.

**Comment by scheler** [comment]
@ask I am getting the same error - no exchange x found in vhost '/', although it is not easily reproducible.  Can you clarify what you mean by 'The example does not declare the exchange' in the above comment? 

When I run the example at https://github.com/yaneurabeya/kombu/blob/master/examples/complete_send.py I don't get the error,so any ideas on when one could get this error would be helpful. Thanks.

**Comment by ask** [comment]
You need to start the consumer first, or if you want the message to be enqueued even if the consumer does not exist you should declare the exchange in both consumer and producer.
