### ISSUE TITLE
RawMessage support for SQS

### ISSUE THREAD

**Issue by kkaehler** [celery/kombu#313]
sqs.message.Message base64 encodes all messages causing the size limitation to be lowered to ~196kb instead of 260kb.

If this is something you'd be interested in supporting (perhaps by default?) I'm happy to do most of the work.

**Comment by auvipy** [comment]
I think its already supported. you can try this way:

try:
    content = json.loads(message) # 99% of the cases this will pass, no checks needed
except json.decoder.JSONDecodeError:
    log.info("Failed to decode the message. Probably compressed, trying to decompress...")
    message = b64decode(message)
    message = decompress(message).decode("utf-8")
    content = json.loads(message)
    log.info("Message successfully decompressed.")
