### ISSUE TITLE
Django Transaction Behavior Changing

### ISSUE THREAD

**Issue by fongandrew** [celery/kombu#382]
Using the Django transport introduces the following deprecation warning due to changes in Django's transaction handling.

    /usr/local/lib/python2.7/dist-packages/kombu/transport/django/managers.py:50: RemovedInDjango18Warning: commit_manually is deprecated in favor of set_autocommit.
      @transaction.commit_manually

**Comment by ask** [comment]
Using SQL as a broker is no longer supported, as we don't have the resources to maintain it :(
