### ISSUE TITLE
Kombu filesystem transport not thread safe

### ISSUE THREAD

**Issue by harlowja** [celery/kombu#398]
From looking it over it appears that this transport isn't thread safe.

I've hit errors like http://paste.openstack.org/show/102226/ a few times and am thinking these class of errors are due to files getting moved by more than one thread. Perhaps some basic locking is in order?

**Comment by mpenalver** [comment]
Attached the version we use, which also avoids the copy of the msgs to tmp. Credit to https://github.com/benediktschmitt/py-filelock.
[filesystem.py.tar.gz](https://github.com/celery/kombu/files/3493492/filesystem.py.tar.gz)

**Comment by jhofeditz** [comment]
Thanks! @mpenalver I also have this problem and will try your fix. Can you submit it as a PR?
