### ISSUE TITLE
Can't decode message body: DecodeError(TypeError('__new__() takes exactly 3 arguments (2 given)',),)

### ISSUE THREAD

**Issue by cdchen** [celery/kombu#408]
When I using Pickle as serializer, kombu will raise exception like:

Can't decode message body: DecodeError(TypeError('__new__() takes exactly 3 arguments (2 given)',),) [type:u'application/x-python-serialize' encoding:u'binary' headers:{}]

How to solve this problem?? Thanks.

**Comment by melbic** [comment]
I had the same error. My problem was the fact, that I returned a ```values_list()```.
My fix: ```return list(Model.objects.values_list('pk', flat=True))```

**Comment by ask** [comment]
Pickle cannot serialize many types, you should check the Python documentation of pickle to see how to write pickleable types!
