### ISSUE TITLE
kombu.five broken on OS X 10.9.5

### ISSUE THREAD

**Issue by calys** [celery/kombu#416]
After an update, I cannot import celery anymore. It is using kombu.five, which generates this error:

~$ python
Python 2.7.8 (default, Aug 24 2014, 21:26:19)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kombu import five
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/kombu/five.py", line 52, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

**Comment by MrTomWhite** [comment]
@ask Do you think we can close this issue, then?

**Comment by ask** [comment]
Yup, looks like we can :)

**Comment by muellermichel** [comment]
I have this issue again with 10.12.6

**Comment by georgepsarakis** [comment]
@muellermichel have you perhaps read this [StackOverflow post](https://stackoverflow.com/questions/26299333/runtime-error-with-kombu-on-mac-os-10-9-5) ?

**Comment by martinsileno** [comment]
Same issue on 11.0.1 - any ideas how to fix? 
Cannot start celery and I cannot seem to find a solution in the linked StackOverflow post.

[Others](https://stackoverflow.com/questions/65130080/attributeerror-running-django-site-on-mac-11-0-1) seem to be having the same problem recently.

**Comment by thedrow** [comment]
We recently removed kombu.five so it's not likely it is the same problem.
