### ISSUE TITLE
[2014-11-12 01:02:48,143: ERROR/Beat] Message Error: Couldn't apply scheduled task myTaskName: Queue list empty or key does not exist: '_kombu.binding.queue'

### ISSUE THREAD

**Issue by denisrai** [celery/kombu#429]
My celery was working normally, but at 01:02 AM my scheduled task began trying get in a queue : _kombu.binding.queue.

Someone see it?

**Comment by ask** [comment]
This is unlikely to ever happen in 4.0 now that we bypass the routing table for name->queue mappings.
