### ISSUE TITLE
Object of type has no len()

### ISSUE THREAD

**Issue by whatsdis** [celery/kombu#438]
essentially I am looking to turn off the can_cache_declaration when creating a queue. However, it is throwing the following error

`object of type 'NoCacheQueue' has no len() `

here's my script.

    from kombu import Queue,Exchange
    from celery import Celery
    from celery import Task

    @app.task()
    def process(seed):
        print "processing"
        return

    class NoCacheQueue(Queue): 
        @property 
        def can_cache_declaration(self): 
            return False 
    
    task.apply_async(args=[333], queue=NoCacheQueue(Queue("some_queue", 
        Exchange('lobby', type='topic'), routing_key='default')))

**Comment by ask** [comment]
Why do you have `NoCacheQueue(Queue(` ?

**Comment by whatsdis** [comment]
spelling error but still didn't work when I tried it.

**Comment by whatsdis** [comment]
so this is closed now? how does the latest commit affect it.
