### ISSUE TITLE
The qpid transport Queue.purge() raises AttributeError when the queue does not exist.

### ISSUE THREAD

**Issue by jortel** [celery/kombu#439]
The qpid transport raises an AttributeError when Queue.purge() is called and the queue does not exist.  Seems that is should raise a *NotFound* channel error to be consistent with the *amqp* transport.  The kombu documentation is unclear about this.

```
>>> from kombu import Connection, Queue
>>> with Connection('qpid://localhost:5672') as connection:
>>>     with connection.channel() as channel:
>>>         q = Queue('dog', channel=channel)
>>>         q.purge()
Traceback (most recent call last):
File "<stdin>", line 4, in <module>
File "/usr/lib/python2.7/site-packages/kombu/entity.py", line 583, in purge
nowait=nowait) or 0
File "/usr/lib/python2.7/site-packages/kombu/transport/qpid.py", line 910, in queue_purge
return self._purge(queue)
File "/usr/lib/python2.7/site-packages/kombu/transport/qpid.py", line 632, in _purge
message_count = queue_to_purge.values['msgDepth']
AttributeError: 'NoneType' object has no attribute 'values'
>>> 
```

**Comment by bmbouter** [comment]
Upon further discussion with the reporter, the problem with the fix already merged is that by raising the ChannelError directly, the AMQPError.code is not being set to 404. This will be reworked so that kombu.exceptions will import amqp.NotFound and raise that instead.

**Comment by bmbouter** [comment]
After some discussion with @ask I've learned that Kombu does not try to maintain consistent exception types across different transports. Instead those exceptions need to be marked as channel_recoverable or connection_recoverable. If an exception is neither of those then it is considered a fatal exception.

Now the behavior will be like this:

```
>>> from kombu import Connection, Queue
>>> with Connection('qpid://localhost:5672') as connection:
...     with connection.channel() as channel:
...         q = Queue('dog', channel=channel)
...         q.purge()
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/bmbouter/kombu/kombu/entity.py", line 583, in purge
    nowait=nowait) or 0
  File "/home/bmbouter/kombu/kombu/transport/qpid.py", line 798, in queue_purge
    return self._purge(queue)
  File "/home/bmbouter/kombu/kombu/transport/qpid.py", line 516, in _purge
    raise NotFound(code=404, text=error_text)
qpid.messaging.exceptions.NotFound: NOT_FOUND - no queue 'dog'(404)
```

**Comment by bmbouter** [comment]
Resolved with https://github.com/celery/kombu/pull/448
