### ISSUE TITLE
kombu producer pooling seems to open too many connections

### ISSUE THREAD

**Issue by beav** [celery/kombu#457]
I have an application that uses the kombu producer pool to obtain producers. However, it appears that kombu creates a new TCP connection every time I obtain a producer, and does not release the connection. For example:

```python
import logging

from kombu import Connection, Exchange, pools
from kombu.exceptions import ConnectionLimitExceeded
from kombu import pools

DEFAULT_EXCHANGE_NAME = 'some.exchange'

event_producer_pool = pools.Producers(limit=3)
_logger = logging.getLogger(__name__)


def send(payload, routing_key=None):
    broker_url = 'amqp://localhost:5600' # rabbit on port 5600
    #broker_url = 'qpid://localhost' # qpid on default port
    connection = Connection(broker_url)

    notification_topic = Exchange(name=DEFAULT_EXCHANGE_NAME, type='topic', channel=connection)

    try:
        with event_producer_pool[connection].acquire() as producer:
            producer.maybe_declare(notification_topic)
            producer.publish(payload, exchange=notification_topic, routing_key=routing_key)
    except ConnectionLimitExceeded:
        _logger.warn("No more available connections in AMQP connection "
                     "pool; event message not sent.")

send("123")
send("456")
send("456")
send("456")

raw_input("sent four messages; press enter to terminate process")
```

After running this script, the python process will have four connections to rabbit (29329 is the PID of my python process):

```bash
$ sudo netstat -anp | grep 29392
tcp        0      0 127.0.0.1:54588         127.0.0.1:5600          ESTABLISHED 29392/python        
tcp        0      0 127.0.0.1:54591         127.0.0.1:5600          ESTABLISHED 29392/python        
tcp        0      0 127.0.0.1:54589         127.0.0.1:5600          ESTABLISHED 29392/python        
tcp        0      0 127.0.0.1:54592         127.0.0.1:5600          ESTABLISHED 29392/python        
```

The connection count keeps growing as I send more messages, resulting in eventual system instability. I originally thought this was related to https://github.com/celery/kombu/issues/455, but it happens with both rabbit and qpid transports. If I do not use the producer pool and instead open/close a connection every time, it works great.

**Comment by beav** [comment]
@bmbouter this is the issue I hit when testing #456. It appears to be unrelated since it affects both rabbit and qpid.

**Comment by ask** [comment]
@beav 

You're evaluating an extra connection here without closing it:

      connection = Connection(broker_url)
      notification_topic = Exchange(name=DEFAULT_EXCHANGE_NAME,
                                                      type='topic',       
                                                      channel=connection)
                                                      ^^^

Removing that `channel=connection` will make your problem go away, since it will then
use the channel of the producer instead, when you do:

    producer.maybe_declare(notification_topic)

But the best way to do this is to use the `declare` argument  to `.publish`:

   with event_producer_pool[connection].acquire() as producer:
       producer.publish(payload,
                                   exchange=notification_topic,
                                   routing_key=routing_key,
                                   declare=[notification_topic])

Since that means you can also use the `retry` and `retry_policy` argument to automatically
retry sending the message if the connection is lost.
