### ISSUE TITLE
Pymongo 3.0 has no option `auto_start_request`

### ISSUE THREAD

**Issue by fayazkhan** [celery/kombu#465]
MongoDB transport `_open` method seem to be using it here: https://github.com/celery/kombu/blob/master/kombu/transport/mongodb.py#L184

Ref: http://api.mongodb.org/python/current/changelog.html#mongoclient-changes

**Comment by buckensl** [comment]
should be fixed by 8e6aed9fcf978b6c34108c0d37b720bd125f0352
