### ISSUE TITLE
Inaccurate redis version requirement

### ISSUE THREAD

**Issue by kylec1** [celery/kombu#468]
According to https://github.com/celery/kombu/blob/master/requirements/extras/redis.txt it appears any redis version >= 2.8.0 is acceptable, but https://github.com/celery/kombu/commit/86683e4167fa19246c25ab86629bf51f18495785 introduces a use of TimeoutError, which is only available in redis versions >= 2.10.0.

I noticed this because on my project (which specifies/uses redis 2.9.0) tests began failing today with Kombu 3.0.25, complaining that TimeoutError wasn't defined.

**Comment by cjgu** [comment]
Yes we got hit by this as well today.
