### ISSUE TITLE
requirements update (urgent)

### ISSUE THREAD

**Issue by dbajal** [celery/kombu#470]
Good day kind sires.
I am here to say that requirements/extras/redis shoud be updated. Here are my arguments:
[this commit](https://github.com/celery/kombu/commit/86683e4167fa19246c25ab86629bf51f18495785) adds redis timeout exception... which exists in redis only since [version 2.10.3](https://github.com/andymccurdy/redis-py/commit/0647659c2f3550063c404a616ba37987c9158149)
So I suggest update **requirements/extras/redis.txt** with:
```
redis>=2.10.3
```
Celery/kombu is broken for work with redis at the moment because of this issue.

**Comment by ask** [comment]
Thanks!  Kombu 3.0.26 is on PyPI now
