### ISSUE TITLE
The qpid transport - Transport class leaks (2) file descriptors

### ISSUE THREAD

**Issue by jortel** [celery/kombu#476]
The *Transport* class provided by the qpid transport creates a pipe in __init__().  The pipe file descriptors are never closed.  As a result, each connect or re-connect causes these two file descriptors to be leaked.

kombu 3.0.20 on f21.

**Comment by ask** [comment]
Thanks! Seems to be merged, so closing

**Comment by bmbouter** [comment]
@ask Thanks! I'll try to keep the issues I work on tidier in the future.

**Comment by bmbouter** [comment]
I'm reopening this issue. The fix provided does not work since the `__del__()` method is never called during garbage collection.

**Comment by bmbouter** [comment]
Actually the fix is only broken in the downstream package we carry. The upstream code is working as expected.
