### ISSUE TITLE
New migrations missing from Django transport

### ISSUE THREAD

**Issue by ktosiek** [celery/kombu#482]
At the moment only South-style migrations are available in the Django transport.
They do not work with Django 1.7+ (there's a new migration system now), which breaks the django:// transport there.

**Comment by ask** [comment]
I have no idea how to generate these, but not sure why you would need them unless you are actually migrating new changes to the Kombu models?

**Comment by ask** [comment]
Fixed in 157021d255a6519fa837cf36066a62f09f9af50a
