### ISSUE TITLE
auto_delete argument of exchange causes an error in rabbitmq server

### ISSUE THREAD

**Issue by zbhknight** [celery/kombu#484]
When working in eventlet, kombu uses pyampy as its transportation. Trying to declare an exist exchange will cause an error in the rabbitmqserver.

```
PreconditionFailed: Exchange.declare: (406) PRECONDITION_FAILED - inequivalent arg 'auto_delete' for exchange '341fe91f8943485e91e6beb13a06235e' in vhost '/': received 'true' but current is 'false'
```
According to the doc in http://kombu.readthedocs.org/en/latest/reference/kombu.transport.pyamqp.html , the server should ignore the auto_delete argument, but it does not.

The versions of related modules and packages are listed below.

* kombu==3.0.26
* amqp==1.4.6
* rabbitmq-server 3.5.3-1 / 2.8.4-1

**Comment by ask** [comment]
Where does the documentation say that auto_delete is ignored?
