### ISSUE TITLE
Messages are not automatically serialized as per documentation

### ISSUE THREAD

**Issue by spikykiwi** [celery/kombu#493]
Following the doc here: https://kombu.readthedocs.org/en/latest/reference/kombu.html#kombu.Exchange.Message

Minimal sample code, run in kombu 3.0.26:

    from kombu import Connection, Exchange
    c = Connection("memory://")
    e = Exchange("test", type="topic")
    e_bound = e(c)
    e_bound.declare()
    m = e_bound.Message({'a':1 })
    e_bound.publish(m)

Exception I get:

  File " site-packages/kombu/entity.py", line 259, in publish
    immediate=immediate)
  File " site-packages/kombu/transport/virtual/__init__.py", line 508, in basic_publish
    message['body'], self.body_encoding,
  File " site-packages/kombu/transport/virtual/__init__.py", line 691, in encode_body
    return self.codecs.get(encoding).encode(body), encoding
  File " site-packages/kombu/transport/virtual/__init__.py", line 51, in encode
    return bytes_to_str(base64.b64encode(str_to_bytes(s)))

**Comment by MrTomWhite** [comment]
I just took a quick look through the code (I'm trying to learn Kombu for a side project, so my guess is as good as yours)
The bottom of the traceback is this method call here:
~~~python
    def encode(self, s):
        return bytes_to_str(base64.b64encode(str_to_bytes(s)))
~~~

I haven't tried doing anything similar on my machine yet, but I wonder if you passed the wrong things into the message / did a slightly off call pattern than what you should have?

**Comment by ask** [comment]
It's not serialized when you publish directly to the `Exchange`.

Serialization is a feature of `kombu.Producer`, and `Exchange.publish` is just a low level method used by that.
