### ISSUE TITLE
access to ssl socket

### ISSUE THREAD

**Issue by dwieeb** [celery/kombu#503]
Concerning the `Connection` class and the py-amqp transport with SSL.

How can I get access to the underlying ssl socket created by `ssl.wrap_socket`? I'd like to be able to do this:

```python
ssl_sock.context.options |= ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3
```

... and I don't think that's possible with just a dictionary of options.

Right now, I am having to specify the protocol version directly, which I don't like:

```python
conn = Connection(os.environ['RABBITMQ_BIGWIG_URL'],
                  ssl={'ca_certs': '/etc/rabbitmq/ssl/ca/cacert.pem',
                       'keyfile': '/etc/rabbitmq/ssl/client/key.pem',
                       'certfile': '/etc/rabbitmq/ssl/client/cert.pem',
                       'cert_reqs': ssl.CERT_REQUIRED,
                       'ssl_version': ssl.PROTOCOL_TLSv1_1})
```

As an aside, for someone who hasn't used `ssl.wrap_socket` before, I had to look at source code to know that they are `**` into `kwargs` for `ssl.wrap_socket`. 

Another thing, is there a reason py-amqp doesn't configure the context options in this way by default? RabbitMQ does not support SSLv3.

**Comment by ask** [comment]
Looks you can use `connection.connection.sock._sslobj` ?

As for default context options, I guess that could be possible, but the path `/etc/rabbitmq` may be different, like for me this is `/usr/local/etc/rabbitmq`, and there's also that amqp is supposed to be a generic protocol, so a different broker may have other requirements and features.
