### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by teeberg** [celery/kombu#504]
When using a `utf8mb4` collation and InnoDB, the maximum key length is reduced to 191 (767 / 4) characters. The django `Queue` model however [uses a key with a length of 200](https://github.com/celery/kombu/blob/4aa1fb930ed05d373ebe0c241fda927251825c45/kombu/transport/django/models.py#L12), which, when trying to migrate the kombu tables, causes this error:

```
Operations to perform:
  Synchronize unmigrated apps:[...], kombu_transport_django, [...], djcelery, [...]
  Apply all migrations: [...]
Synchronizing apps without migrations:
  Creating tables...
    Creating table djkombu_queue
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
...
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

**Comment by ask** [comment]
This is better solved in Django really, there should be a global max_char_limit or similar. We cannot easily change the default, as that will require migration.  Maybe monkey patching CharField is a quick fix?

**Comment by teeberg** [comment]
I'll end up doing this in my core `AppConfig`:
```python
import kombu.transport.django.models
kombu.transport.django.models.Queue._meta.get_field('name').max_length = 191
```
I realize it's a potentially breaking change (practically, I don't think so, or are queue names consisting of 200 4-byte characters common practice?), but maybe it could be considered for the next major version bump? I remember seeing some projects setting the `max_length` of their indexes to 191 explicitly, as that seems to be a sane upper limit, but I can't seem to find them anymore. Maybe I fantasized.

This was also brought up in the django bug tracker, so maybe it'll be solved there :) https://code.djangoproject.com/ticket/18392

**Comment by ask** [comment]
Using SQL as a broker is no longer supported as we don't have the resources to maintain it :(

**Comment by teeberg** [comment]
I wasn't using it as a broker, so if that means that this issue is gone 👍
