### ISSUE TITLE
Virtual transport does not support multiple bindings for queues

### ISSUE THREAD

**Issue by hochbergg** [celery/kombu#506]
The virtual transport does not allow binding a queue with different routing keys. When `bind_to()` is called for the same queue more than once, the `queue_bind()` function in the virtual `Channel` class discards the call silently if the queue is already in `state.bindings`.

I have verified this in the `memory` virtual broker. 

I believe the AMQP protocol does allow for multiple bindings with the same queue, and I know its supported in RabbitMQ. Also, its very useful to have the `memory` virtual broker support this to allow testing scenarios.

**Comment by nazavode** [comment]
Trying to add this feature on a [fork](https://github.com/nazavode/kombu) of the latest stable release. All the tests seems to be fine up to now, still a bit of work to be carried out but it looks promising.

**Comment by nazavode** [comment]
#574 is closed, maybe we need to close this one as well @ask?

**Comment by ask** [comment]
Thanks for reminding me! :)
