### ISSUE TITLE
Option to consume from Redis Queues as priority queue instead of round-robin

### ISSUE THREAD

**Issue by Scentus** [celery/kombu#518]
Up in Celery (using Redis as a backend) we recently came across the need to treat queue consumption as a priority queue instead of round robin. Namely we needed the ability to define two queue's from the same Topic Exchange with the (effective) routing keys of job.user001 for the first Queue and job.* for the second Queue.

The behavior we desire would be that a worker setup like this would always prefer jobs from a specific user over jobs from other users when they existed while still being able to fall back to handling jobs from other users when (and only when) said 'user001' was idle.

However the behavior that seems to be defined is instead a round-robin approach to Queue handling that would take one job from 'user001' if available, and then take its next job from all available jobs, even if there are still more jobs remaining for 'user001'. While this behavior is certainly useful in most cases, a configuration option to switch between them would be desirable.

If there is any reason this is not feasible due to some technical limitation I am unaware or if I am simply misunderstanding something please let me know of that as well.

**Comment by plamennikolov** [comment]
+1 It allows a better utilisation of a limited amount of workers.
