### ISSUE TITLE
Qpid transport tries to connect to 127.0.0.1 instead of localhost hostname

### ISSUE THREAD

**Issue by bmbouter** [celery/kombu#519]
If the broker string contains, localhost, 127.0.0.1 will be used. This prevents a certificate with the `CN=localhost` from being used. It shouldn't do this arbitrarily.

**Comment by ask** [comment]
AFAIR the use of 127.0.0.1 was to fix a bug where gevent cannot resolve `localhost`.  Maybe have been fixed upstream.

**Comment by bmbouter** [comment]
Oh that's interesting. I couldn't think of any reason why a rewrite line like that would be present but it makes sense. Hopefully gevent has fixed the issue. Do you have a link to the upstream gevent issue? I'm curious.

For now, I want to leave the qpid transport without the rewrite rule so that the CN assertion with SSL will work correctly. Some Qpid transport users are using it that way. @ask Is that OK with you?

**Comment by bmbouter** [comment]
This fix got merged so I'm going to close this issue. It will be included in the next Kombu release.

@ask do you usually close an issue before the release or after it is released?

**Comment by ask** [comment]
I close them before release, to get them out of the way, and so that I will not forget to close them after :)

**Comment by bmbouter** [comment]
@ask cool, thanks. Given that, I can help close issues I work on so that you have less to do.
