### ISSUE TITLE
libSystem.dylib fails to load on OS X 10.11

### ISSUE THREAD

**Issue by ewang** [celery/kombu#521]
On OS X 10.11, the libSystem = ctypes.CDLL('libSystem.dylib') call in kombu/five.py on the v3.0 branch fails to load with image not found error.

I am using kombo v3.0.26 that's depended on by celery v3.1.18

However, if the above call was changed to ctypes.CDLL(find_library('libSystem.dylib')), the call succeeds.

Disabling SIP resolves the issue, so it's probably due to SIP not allowing access to the /usr/lib folder. However, passing in an absolute path /usr/lib/libSystem.dylib to ctypes.CDLL() or using find_library() works.

**Comment by ask** [comment]
Closed by #522
