### ISSUE TITLE
v3.0.27 breaks Django1.8 that already have `djkombu_message` table

### ISSUE THREAD

**Issue by ticosax** [celery/kombu#527]
The new migration file introduced by 8270dd25ec391c4c65dc2031f901b51c52fe17a0
tells django to create the `djkombu_message` table, but fails if the DB already have this table during
`python manage.py migrate` execution:
```
django.db.utils.ProgrammingError: relation "djkombu_message" already exists
```
It should be at least documented to run that command just after upgrading
`python manage.py migrate kombu_transport_django --fake-initial`

Does it exist a better way to handle this issue ?

**Comment by riklaunim** [comment]
--fake-initial is the only option. Although Django could be smarter with it a bit.

**Comment by blueyed** [comment]
> Changed in Django 1.8:
The --fake-initial flag to migrate was added. Previously, Django would always automatically fake-apply initial migrations if it detected that the tables exist.

Seems like before Django 1.8 this was done implicitly, but then was moved into an explicit option.

Ref: https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-option---fake-initial

**Comment by riklaunim** [comment]
Django can detect initial migration but it doesn't auto-work always. --fake-initial was added to fake initial and nothing else as pre-1.8 --fake would have to be used. And it can behave differently when migrating on a clean database or existing one.

**Comment by rocktavious** [comment]
I'm having this same issue with Django-1.8.1 Celery-3.1.18.

Is there a fix yet?

**Comment by ask** [comment]
@rocktavious You have to run the command mentioned earlier in this thread:

    python manage.py migrate kombu_transport_django --fake-initial

**Comment by ask** [comment]
Closing this, as we don't have the resources to support the Django database transport.
