### ISSUE TITLE
Qpid Support?

### ISSUE THREAD

**Issue by jplock** [celery/kombu#54]
Would it be possible to support the Qpid Python client libraries (https://github.com/apache/qpid/tree/trunk/qpid/python) as another AMQP transport?  That would provide support for the AMQP 0-10 protocol.

**Comment by bmbouter** [comment]
Just came across this old issue. FYI, Kombu 3.0.24 contains support for Qpid.

http://kombu.readthedocs.org/en/latest/reference/kombu.transport.qpid.html
