### ISSUE TITLE
Logs flooded with "Deregistered fd [int] from event loop without registered callbacks."

### ISSUE THREAD

**Issue by adamnreed** [celery/kombu#549]
Hey there. We upgraded yesterday from 3.0.24 to 3.0.30 so kombu would work with python 2.7.11. Since then, our celery workers have been crashing after running for a few hours. At some point, the logs start getting flooded with these "Deregistered" messages, at a rate of hundreds of log messages per second, sometimes almost once per millisecond.

Example:
```
Dec 11 00:42:09 app/worker.3:  [2015-12-11 00:42:09,454: INFO/MainProcess] Deregistered fd 61 from event loop without registered callbacks. 
Dec 11 00:42:09 app/worker.3:  [2015-12-11 00:42:09,465: INFO/MainProcess] Deregistered fd 61 from event loop without registered callbacks. 
Dec 11 00:42:09 app/worker.3:  [2015-12-11 00:42:09,498: INFO/MainProcess] Deregistered fd 61 from event loop without registered callbacks. 
Dec 11 00:42:09 app/worker.3:  [2015-12-11 00:42:09,514: INFO/MainProcess] Deregistered fd 61 from event loop without registered callbacks. 
```

**Comment by ask** [comment]
Interesting... Is it always the same fd?  Can you tell by using `lsof` what type of file descriptor it is?

Please also include more information, like the broker transport used, celery configuration, etc.

**Comment by chocobn69** [comment]
Hey

We have the exact same problem using kombu with celery : Our logs are full of those lines :

`[2015-12-16 07:25:25,068: INFO/MainProcess] Deregistered fd 51 from event loop without registered callbacks.`

```shell
pip freeze|grep kombu
kombu==3.0.30
```

Broker used : rabbitmq

celery conf :

``` python
from __future__ import absolute_import
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from celery import Celery
from .settings import ENV


if ENV == 'prod' or ENV == 'test':

    broker = 'amqp://celery:yyy@1.1.1.1:5672//'
    backend = 'amqp://celery:yyy@1.1.1.1:5672//'
else:

    broker='amqp://guest:guest@192.168.69.85:5672//'
    backend='amqp://guest:guest@192.168.69.85:5672//'


app = Celery('pricing',
             broker=broker,
             backend=backend,
             include=['yyy.tasks'])

# Optional configuration, see the application user guide.
app.conf.update(
    CELERY_TASK_RESULT_EXPIRES=300,
    CELERY_AMQP_TASK_RESULT_EXPIRES=300,
    CELERYD_TASK_TIME_LIMIT=120,
    CELERYD_TASK_SOFT_TIME_LIMIT=70,
    CELERYD_PREFETCH_MULTIPLIER=1,
    CELERY_RESULT_BACKEND='amqp',
    CELERY_RESULT_SERIALIZER='pickle',
    CELERY_ACCEPT_CONTENT=['pickle', ],
    CELERY_SEND_TASK_ERROR_EMAILS=False,
    BROKER_POOL_LIMIT=100,
    ADMINS=(
        ('yyy yyy', 'yyy'),
    ),
    SERVER_EMAIL=xxx',
    CELERY_SEND_EVENTS=False,
    CELERY_MESSAGE_COMPRESSION='bzip2',
    CELERYD_CONCURRENCY=4,
    CELERY_ROUTES={
        'xxx': {'queue': 'xxx'},
        'yyy': {'queue': 'yyy'},
    },
    CELERY_IGNORE_RESULT=True,
    CELERY_STORE_ERRORS_EVEN_IF_IGNORED=False,
    CELERYD_MAX_TASKS_PER_CHILD=2000
)

if __name__ == '__main__':
    app.start()
```

**Comment by chocobn69** [comment]
It could be related to https://github.com/celery/kombu/issues/476 fix ?

**Comment by ask** [comment]
Definitely related, but still need to know what type of file descriptor this is, from the output of `lsof`.

**Comment by niteeshm** [comment]
Facing the same issue. lsof | grep 190 gives:
`ksuspend_   190      root  cwd   unknown                                   /proc/190/cwd (readlink: Permission denied)
ksuspend_   190      root  rtd   unknown                                   /proc/190/root (readlink: Permission denied)
ksuspend_   190      root  txt   unknown                                   /proc/190/exe (readlink: Permission denied)
ksuspend_   190      root NOFD                                             /proc/190/fd (opendir: Permission denied)`
