### ISSUE TITLE
Unavailable `_uuid_generate_random`

### ISSUE THREAD

**Issue by Kronuz** [celery/kombu#551]
In `komb.utils`, it's importing `_uuid_generate_random` which no longer is available (at least in Python 2.7.11), it seems.

```python
from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
```

**Comment by ask** [comment]
This was fixed in 3.0.30

**Comment by Kronuz** [comment]
Yup, just saw that and upgraded. Thanks!

**Comment by ask** [comment]
Cheers :)
