### ISSUE TITLE
kumbu tests fail - no dependencies

### ISSUE THREAD

**Issue by iditgolden** [celery/kombu#552]
The kumbu tests are running in my code but they are missing a mock dependency

Failure: ImportError (No module named mock) ... ERROR
ERROR: Failure: ImportError (No module named mock)

Traceback (most recent call last):
File "/dir/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/dir/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File "/dir/nose/importer.py", line 94, in importFromDir
mod = load_module(part_fqname, fh, filename, desc)
File "/dir/kombu/tests/async/test_hub.py", line 6, in <module>
from kombu.tests.case import Case
File "/dir/kombu/tests/case.py", line 12, in <module>
import mock  # noqa
ImportError: No module named mock

**Comment by iditgolden** [comment]
on version 3.0.30 it did not occur.

**Comment by ask** [comment]
You need to install requirements/test.txt in the kombu source directory

**Comment by iditgolden** [comment]
My problem is that I keep virtualenv in my project and just did pip install to kombu, I also use nosetests to run my tests
and when I run nosetest (in root dir) it collects the tests from kombu as well and fails because of dependency,  and pip install of that kumbu didn't install the test dependency, and now I have to add that dependency to my requirements. I prefer not too.

Thanks

**Comment by iditgolden** [comment]
@ask: ?

**Comment by ask** [comment]
You run nosetests for all packages in your virtualenv? ...

**Comment by iditgolden** [comment]
@ask : I run nosetest in the root of my project, and it also contains the virtualenv inside. then, yes.

**Comment by ask** [comment]
In that case this will be a problem for many libraries, maybe you should specify where to run the tests?

You can specify it manually using `nosetests -xv package`, but the best practice is to have a `setup.cfg` for the project:

https://github.com/celery/celery/blob/master/setup.cfg#L1-L2
