### ISSUE TITLE
Unable to bind to "internal" RabbitMQ exchanges

### ISSUE THREAD

**Issue by jbiel** [celery/kombu#565]
I'm writing a test script based off of the task queue example [here](http://docs.celeryproject.org/projects/kombu/en/latest/userguide/examples.html). I've modified that example to attempt to bind to the amqp.rabbitmq.trace exchange to attempt to use the RabbitMQ [firehose](https://www.rabbitmq.com/firehose.html) to do some debugging.

```
exchange = Exchange('amq.rabbitmq.trace', type='topic')
queues = [Queue('firehose', exchange, durable=False, routing_key='#', auto_delete=True,)]
```

Attempting to run the script yields an exchange declaration mismatch:

```
PreconditionFailed: Exchange.declare: (406) PRECONDITION_FAILED - inequivalent arg 'internal' for exchange 'amq.rabbitmq.trace' in vhost '/': received 'false' but current is 'true'
```

There isn't a native "internal" option for [Exchange](http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.html#exchange) in Kombu. I've tried setting [arguments](http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.html#kombu.Exchange.arguments) like the following (also using boolean True) without success (same precondition failed error is received.)

```
exchange = Exchange('amq.rabbitmq.trace', type='topic', arguments={'internal': 'true'})
```

Am I doing something wrong or is this currently not supported? Thanks!

**Comment by jbiel** [comment]
Thanks Ask!

**Comment by JeancarloBarrios** [comment]
Why did he close it with no answer

**Comment by jbiel** [comment]
See the commit in the "closed this issue" comment. There's now an option called `no_declare` that can be used while instantiating a queue.
