### ISSUE TITLE
This socket is already used by another greenlet

### ISSUE THREAD

**Issue by scheler** [celery/kombu#566]
Hello,
I am running into the following error once in a while. My application uses greenlets and possible does simultaneous publish calls.  I do use a semaphore from gevent.lock around the publish call, so it is not clear what is going wrong.  Any suggestions?

Traceback (most recent call last):
File "pubsub.py", line 313, in publish
publish(bus_message, exchange=exchange, routing_key=topic)
File "/local/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
return fun(*args, **kwargs)
File "/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
routing_key, mandatory, immediate, exchange, declare)
File "/local/lib/python2.7/site-packages/kombu/messaging.py", line 177, in _publish
channel = self.channel
File "/local/lib/python2.7/site-packages/kombu/messaging.py", line 194, in _get_channel
channel = self._channel = channel()
File "/local/lib/python2.7/site-packages/kombu/utils/_init__.py", line 422, in call
value = self.__value__ = self.__contract__()
File "/local/lib/python2.7/site-packages/kombu/messaging.py", line 209, in <lambda>
channel = ChannelPromise(lambda: connection.default_channel)
File "/local/lib/python2.7/site-packages/kombu/connection.py", line 758, in default_channel
self._default_channel = self.channel()
File "/local/lib/python2.7/site-packages/kombu/connection.py", line 242, in channel
chan = self.transport.create_channel(self.connection)
File "/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 92, in create_channel
return connection.channel()
File "/local/lib/python2.7/site-packages/amqp/connection.py", line 282, in channel
return self.Channel(self, channel_id)
File "/local/lib/python2.7/site-packages/amqp/channel.py", line 101, in init
self._x_open()
File "/local/lib/python2.7/site-packages/amqp/channel.py", line 429, in _x_open
(20, 11), # Channel.open_ok
File "/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
self.channel_id, allowed_methods, timeout)
File "/local/lib/python2.7/site-packages/amqp/connection.py", line 241, in _wait_method
channel, method_sig, args, content = read_timeout(timeout)
File "/local/lib/python2.7/site-packages/amqp/connection.py", line 330, in read_timeout
return self.method_reader.read_method()
File "/local/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
raise m
AssertionError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0x7f535463e780>>
backend.py:248 'This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0x7f535463e780>>'
Traceback (most recent call last):

thanks.

**Comment by sergedomk** [comment]
publish is not the only call that uses the socket. In your case the exception is actually getting raised when the publish method attempts to create the channel. Getting your channel also requires the socket connection. As this call is happening within your lock on the publish, it's obviously not the culprit for the exception. But, there might be some code running in another greenlet that is also attempting to create a channel. If there is, it is also using the socket.

I worked around this issue by using locks on pretty much everything that would require communication with the server (i.e., publish, channel, etc.).

**Comment by scheler** [comment]
@sergedomk Thanks for the reply.  I don't use channels explicitly. I have the following currently. Where do you think an additional channel is being seeked.

`def _publish(self, exchange_name, topic, message, extra):
        exchange = Exchange(exchange_name, 'topic', durable=True)
        conn = self._get_publish_connection()
        producer = Producer(conn)
        publish = conn.ensure(producer, producer.publish, errback=error_publishing, max_retries=5)

        with _lock(self.publish_lock):
            try:
                publish(bus_message, exchange=exchange, routing_key=topic)
            except Exception as e:
                self.log.exception('Error publishing %s to exchange %s', topic, exchange_name)
                raise`

**Comment by ask** [comment]
Two greenlets cannot share the same connection, you should use a connection pool to share connections between greenthreads.

**Comment by anentropic** [comment]
I think we have this problem in our web app

It is running under uWSGI+gevent so the green threads are not directly under control of our app code

We rarely but consistently see exactly this error.

I don't think we can set up our own connection pool and pass it around, as our app code is already loaded inside a greenlet by uWSGI

Based on comments above it seems like problem with @scheler example above is they need to get lock before acquiring connection, rather than just before publish?

i.e.
```python
def _publish(self, exchange_name, topic, message, extra):
        exchange = Exchange(exchange_name, 'topic', durable=True)
        with _lock(self.publish_lock):
            conn = self._get_publish_connection()
            producer = Producer(conn)
            publish = conn.ensure(producer, producer.publish, errback=error_publishing, max_retries=5)
            try:
                publish(message, exchange=exchange, routing_key=topic)
            except Exception as e:
                self.log.exception('Error publishing %s to exchange %s', topic, exchange_name)
                raise
```
?

And we could do a similar thing when enqueueing Celery tasks, where the publishing happens implicitly?
i.e.
```python
@app.task
def my_celery_task():
    pass

def enqueue():
    with lock(...):
        my_celery_task.delay()
```

is this likely to help?

and it is a `gevent.lock.Semaphore` that we need to use for the locking?
