### ISSUE TITLE
Question for MessagePack Support

### ISSUE THREAD

**Issue by hiroaki-yamamoto** [celery/kombu#570]
Hi,

I have a question about msgpack serialization:
https://github.com/celery/kombu/blob/master/kombu/serialization.py#L366

According to above, `unpack` function calls `unpackb` function with `utf-8` encoding, but I don't understand why the encoding is given. And because of this behavior, `msgpack` can't serialize binary blob though `msgpack` itself can serialize it.

Can anyone tell ~~my~~ me the reason why `unpack` calls `unpackb` with encoding?

Edit: I made an embarrassing typo

**Comment by ask** [comment]
I have no idea why, what is it used for?  Is changing it backwards compatible?

**Comment by hiroaki-yamamoto** [comment]
Well, as far as I checked [readme] msgpack, msgpack can distinguish binary and str and I don't think specifying the encoding is needed. In addition making a consumer that uses current msgpack and it returns binary type by using celery, kombu shows the binary is not serializable / deserializable because of this encoding behavior. So, I think `encoding` parameter should be removed.

What do you think?

[readme]: https://github.com/msgpack/msgpack-python#string-and-binary-type

**Comment by georgemarshall** [comment]
This change breaks msgpack in Python 3. All keys are now returned as `bytes` and thus `'status' != b'status'`.

**Comment by hiroaki-yamamoto** [comment]
Ohhh.... Sorry, it's my bad.

Honestly I wanted kombu to send/receive binary data.

**Comment by ask** [comment]
I read up on msgpack again, and this seems to properly use a binary type for str/bytes and a string type for unicode/str (but ironically still truncates any non-ascii unicode characters).
