### ISSUE TITLE
Redis dependency should be >2.10

### ISSUE THREAD

**Issue by muralikg** [celery/kombu#575]
Change history tells

> Redis: Adds the ability to set more Redis connection options using Connection(transport_options={...}).
> 
> socket_connect_timeout
> socket_keepalive (requires redis-py > 2.10)
> socket_keepalive_options (requires redis-py > 2.10)

But the requirements has an older redis dependency >2.8

**Comment by ask** [comment]
This was deliberate as I didn't want to bump the redis version requirement for a bugfix release unless truly necessary.

That changelog is meant to read as: socket_connect_timeout is supported by all versions, but to use the socket_keepalive_* settings you need to have at least redis 2.10.
