### ISSUE TITLE
Installation error, requirements/default.txt not present into temp folder !

### ISSUE THREAD

**Issue by estevopaz** [celery/kombu#585]
\# Install the application in development mode. The installed package is just a link to the project in the current path.
\`which python` setup.py develop --script-dir=~/bin --install-dir=~/.local/lib/python2.7/site-packages
/usr/lib/python2.7/dist-packages/setuptools/command/install_scripts.py:3: UserWarning: Module email was already imported from /usr/lib/python2.7/email/__init__.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import Distribution, PathMetadata, ensure_directory
running develop
running egg_info
(...)
Searching for kombu>=3.0.34,<3.1
Reading http://pypi.python.org/simple/kombu/
Best match: kombu 3.0.35
Downloading https://pypi.python.org/packages/source/k/kombu/kombu-3.0.35.tar.gz#md5=6483ac8ba7109ec606f5cb9bd084b6ef
Processing kombu-3.0.35.tar.gz
Running kombu-3.0.35/setup.py -q bdist_egg --dist-dir /tmp/easy_install-K5dmwG/kombu-3.0.35/egg-dist-tmp-EvoEXj
error: [Errno 2] No such file or directory: '/tmp/easy_install-K5dmwG/kombu-3.0.35/requirements/default.txt'
make: *** [develop] Error 1

**Comment by onagorodniuk** [comment]
same problem with 3.0.34 version

**Comment by paperbd** [comment]
Also running into this issue when installing kombu with easy_install.

**Comment by ask** [comment]
requirements/default.txt is in MANIFEST.in, and also in the 3.0.35 distribution so does easy_install not extract the distribution?
