### ISSUE TITLE
SQS - Creating duplicate queues with different visibility_timeout when number of queues is greater than 1000

### ISSUE THREAD

**Issue by luyun-aa** [celery/kombu#586]
We are using celery and kombu with a lot of SQS queues (>10k).  We found that when you have so many queues, the queue name will be missing in the internal cache of the `Channel`. The root cause is the ListQueues method of SQS will only return 1k queues with the given prefix. This will result in kombu creating duplicate queues.

**Comment by luyun-aa** [comment]
@ask Could you take a look at this pull request?

**Comment by luyun-aa** [comment]
@ask @thedrow Could you take a look at this pull request please? It's very important for us to merge this patch to the upstream. Thanks!

**Comment by ask** [comment]
Closed by #587
