### ISSUE TITLE
Errors not reported

### ISSUE THREAD

**Issue by smurfix** [celery/kombu#603]
kombu/mixins.py:
```
174                 except errors:
175  ->                 warn('Connection to broker lost. '
176                          'Trying to re-establish the connection...')
```

Errm, would you *please* not drop the actual error message on the floor? It contains important information, in this case the fact that the user didn't have rights to the queue.

**Comment by ask** [comment]
It doesn't drop it, it logs it...

The alternative would be to not recover when the connection is lost.

Granted, the logging situation in Python is not all that great as users will not see this unless we configure logging, and it's not possible for us to do this as Kombu is a library, not an end-user program.

The alternative to logging would be to use print statements, and that is even more unacceptable for a library to do.

**Comment by smurfix** [comment]
On 24.06.2016 00:46, Ask Solem wrote:
>
> It doesn't drop it, it logs it...
>
It does not. It logs that an error occurred, but not which one, as can
be seen quite plainly from the lines I quoted.

-- 
-- Matthias Urlichs

**Comment by ask** [comment]
Seems it's already fixed in master, as it's using `exc_info=1` there.
