### ISSUE TITLE
redis.ping() instead of redis.info() for connection health?

### ISSUE THREAD

**Issue by phill-tornroth** [celery/kombu#607]
On Channel's __init__ [we're calling redis' INFO command](https://github.com/celery/kombu/blob/master/kombu/transport/redis.py#L495). In my experience INFO's performance can be fairly variable depending on the server's config and database stats. Wondering if there's a strong reason not to use [PING](http://redis.io/commands/ping) for this purpose? It's much faster.

**Comment by ask** [comment]
Good idea!  Definitely makes more sense to use PING, not sure if that was available at the time when I chose this.
