### ISSUE TITLE
Multiprocessing in kombu ConsumerMixin breaks connection

### ISSUE THREAD

**Issue by Shookit** [celery/kombu#613]
Inside of my kombu consumer's run loop, I had planned on using an external process to handle processing the callback (to deal with Python's memory fragmentation issues). It appears that launching a subprocess inside of the callback will break the specified connection (this happens even if the subprocess has nothing to do with the program flow, as shown; just the existence of the subprocess causes this). Is this a known issue with kombu?

```
self.pool = Pool(1, maxtasksperchild=20)

def x((k)):
    return True

def callback(body, message):
        # pool.map(x, ['k'])

        # Unless above is commented, this gives WARNING:kombu.mixins:Connection to broker lost, trying to re-establish connection...
        producer_inst.publish(self.data,
                                           serializer='json',
                                           exchange=self.exchange,
                                           routing_key='null')
```

**Comment by ask** [comment]
Celery uses multiprocessing.Pool so I doubt that it's incompatible, but note that connection pools have a after-fork callback that closes the connections in the child process.

Python also shares sockets so if the child process is reading/writing from the socket bad things can happen (like the server closing the connection due to a framing race condition).

**Comment by Shookit** [comment]
Sorry, this was a bad implementation on my part, but hopefully this can help someone out. 

I have a multiprocessed architecture, and inside of a kombu callback, I needed to publish a message. I was originally creating extra kombu connections within the subprocess to send that message out, but inside of the message via `def callback(body, message)`, there is actually a connection already available via message.connection. This cleared up all of my connection collisions.
