### ISSUE TITLE
Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by sicarrots** [celery/kombu#622]
hi,

In #609 there was introduced change which breaks running on 2.7.3. The exception message is: Struct() argument 1 must be string, not unicode (amqp/exceptions.py, line 264).

**Comment by ask** [comment]
Are you saying unpack requires bytes on 2.73, unicode on 2.7.5 and either bytes/string on 2.7.6+?

**Comment by sicarrots** [comment]
That seems very strange, but i've cheked this once more. Python 2.7.3, exception as i written above.

**Comment by kellyschoenhofenfpx** [comment]
We are having this issue, same exact situation/problem. We think the problem is from amqp upgrading to 2.1.0; I'm going to try pinning it back to 2.0.3 which is the version on the working python 2.7.3 machines. Much thanks to Lacriatch in the #celery irc room.

**Comment by bsmithyman** [comment]
@ask: Can you confirm that 2.7.5 requires `unicode`? My impression was that all versions < 2.7.7 required `str` input, and that 2.7.7 added `unicode` as an option ([see here](http://python-future.org/stdlib_incompatibilities.html#struct-pack)). It seems like the change in https://github.com/celery/py-amqp/commit/9167f6569e5f48fcb37e6eda8caf9ce81de2dc93 goes the wrong direction.

I think the right update would be to change everything to bytestrings, which seem to work in all versions of 2.7 and 3.x that I have tested so far. See https://github.com/celery/py-amqp/pull/108.

**Comment by ask** [comment]
I don't have a 2.7.5 running here, so I cannot confirm :(

Using bytes everywhere definitely sounds reasonable if that is supported by all of them (and you'd think so).

I don't think we should worry about 3.4 at all, both celery 4 and kombu 4 requires 3.5+, so amqp should also.

**Comment by phretor** [comment]
@ask I have a 2.7.5 running with Celery 4.0.0, amqp==2.1.1, RabbitMQ 3.6.3, Erlang 18.3

```
Python 2.7.5 (default, Sep 15 2016, 22:37:39)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
```

Just crashed right now with:

```
[2016-11-29 08:17:15,800: CRITICAL/MainProcess] Unrecoverable error: TypeError('Struct() argument 1 must be string, not unicode',)
```

This is a staging environment, so I'm happy to perform tests if at all helpful.

**Comment by xxmatyuk** [comment]
@ask, just to confirm:

the following set 
`Django==1.10.1
amqp==2.1.4
billiard==3.5.0.2
celery==4.0.2
kombu==4.0.2
pytz==2016.10
vine==1.1.3`

triggers django to fail with 

`TypeError: Struct() argument 1 must be string, not unicode`

downgrade to amqp==2.1.3 fixes the problem and @bsmithyman, you're right, that was the commit that caused the problem. For those who's suffering, downgrade to 2.1.3 might be the cure.

**Comment by hp685** [comment]
amqp 2.1.0 is still incompatible with celery 4.0.2

**Comment by auvipy** [comment]
hope new release fix this
