### ISSUE TITLE
OrderedDict that was previously defined in compat doesn't appear to be there anymore

### ISSUE THREAD

**Issue by h2rashee** [celery/kombu#632]
Was OrderedDict deprecated from an older version? Currently using 3.0.35.

Can't seem to find it on the revision history though which is strange.
https://github.com/celery/kombu/commits/master/kombu/utils/compat.py

```
celery/five.py", line 149, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
ImportError: cannot import name OrderedDict
```

Can provide more info on the stacktrace in a private message.

**Comment by ask** [comment]
Kombu 3.0.x should definitely have that, but it's to be removed in Kombu 4.x.

Are you sure you haven't accidentally installed the kombu dev version somehow?  Some older versions pip seem to install dev versions of things, even though it shouldn't.

**Comment by h2rashee** [comment]
Sorry yes the initial comment is wrong. pip was installing kombu 4.x dev version instead of a released stable one. Any reason why this was re-structured and why it causes this issue especially when OrderedDict is in Python?

**Comment by ask** [comment]
Kombu 3.0 is compatible with Python 2.6 and that doesn't have OrderedDict,  kombu 4.0 requires Python 2.7 so just uses `collections.OrderedDict` directly.

The Celery 3.1 requirements are strictly requiring kombu<3.1 in anticipation of incompatible changes, but with this pip bug it's difficult to enforce :(
