### ISSUE TITLE
Update msgpack MIME type

### ISSUE THREAD

**Issue by cemremengu** [celery/kombu#646]
According to [RFC 6838](http://tools.ietf.org/html/rfc6838)  and  [RFC 6648](https://tools.ietf.org/html/rfc6648), any use of types in the "x." tree is strongly discouraged. So `application/x-msgpack` is essentially a deprecated mime type.

>  However, with the simplified registration procedures described above
>    for vendor and personal trees, it should rarely, if ever, be
>    necessary to use unregistered types.  Therefore, use of types in the
>    "x." tree is strongly discouraged.

The issue is also being discussed here so will be helpful to watch for updates: https://github.com/msgpack/msgpack/issues/194

**Comment by auvipy** [comment]
are you willing to contribute this change?

**Comment by cemremengu** [comment]
@auvipy sorry its been a long time and dont have the time anymore 😞 

maybe it should not be changed since it might be a very breaking fix
