### ISSUE TITLE
in flask-SocketIO use redis/sentinel message_queue

### ISSUE THREAD

**Issue by Negashev** [celery/kombu#656]
[Problem](https://github.com/miguelgrinberg/Flask-SocketIO/issues/359) with find master

```python
redis.sentinel.MasterNotFoundError: No master found for None
```

**Comment by ask** [comment]
I'm not exactly sure how the sentinel integration works, perhaps it's not passing this value correctly?

**Comment by auvipy** [comment]
let us know if the bug still exists
