### ISSUE TITLE
collect_replies is no longer working after 4.0.0

### ISSUE THREAD

**Issue by VladimirKorzh** [celery/kombu#669]
We use collect_replies internally for RPC handling. After upgrading to kombu 4.0.0 suddenly code that was rock solid for months started failing. Investigation and intense debugging showed that drain_consumer on_message function fails to add incoming message to deque, which generates infinite IndexErrors in the loop. 

Steps to reproduce:
1. Publisher1 message to Q1
2. Publisher1 goes into a loop waiting for reply using collect_replies method
3. Consumer1 reads the message 
4. Consumer1 sends a reply using send_reply method
5. Message appears in the target reply_to queue
6. Publisher1 takes the message off the queue and fails to put in deque

Result:
Message eaten internally and never delivered to requester.

Log RPC Server:
23:22:57 INFO   Received packet: {'function': 'functionName', 'parameters': {'param1': [value1]}}
23:22:57 INFO   Reply sent: {'message': [''value1','value2','], 'status': 200}

Log RPC Consumer:
23:23:08 ERROR ServiceName service not available, retrying!   (Got Timeout)

Solution:
Roll back to using 3.0.37

**Comment by auvipy** [comment]
hope using the latest releases fix the issue if not plz report here
