### ISSUE TITLE
Consumer cannot stop if heartbeat is missed

### ISSUE THREAD

**Issue by mattbennett** [celery/kombu#670]
I have been testing consumer heartbeats under different network failure modes using [toxiproxy](http://toxiproxy.io).

When the connection to the broker loses packets downstream (broker -> consumer) but the socket doesn't actually close, kombu hangs rather than re-establishing the connection when the heartbeat check fails. The consumer issues a `basic_cancel` and then to waits for a `basic_cancel_ok` from the broker, which is swallowed by the broken network connection.

The [Consumer.cancel()](https://github.com/celery/kombu/blob/master/kombu/messaging.py#L434-L438) is wrapped in a try/except, but it never raises because there's no`timeout` set when waiting for the reply method.

I don't know whether a timeout on the `wait` is the required fix, or whether `basic_cancel` should be sent with `nowait=True`.

I've demonstrated this on the latest kombu and pyamqp versions (4.0.0 and 2.1.1) and it's present in the 3.x and 1.x generations too.

I can put together a reproducible testcase if it would be helpful.

**Comment by ask** [comment]
Where is the Consumer.cancel called from?

I thought closing the connection only calls .collect, which should not wait for consumers to be cancelled.

**Comment by mattbennett** [comment]
It's in [`Consumer.__exit__`](https://github.com/celery/kombu/blob/master/kombu/messaging.py#L433).

There's a deeply nested set of context managers inside `ConsumerMixin.consume`, and `Consumer.__exit__` is at the end of the chain, wrapped up inside `nested`.

Could a simple fix be for `Consumer.__exit__` to check whether it's exiting due to a connection error? Something like:

``` python
    def __exit__(self, *exc_info):
        if exc_info and issubclass(exc_info[0], ConnectionError):
            return
        try:
            self.cancel()
        except Exception:
            pass
```
