### ISSUE TITLE
RTD Shows Docs for Previous Release as Latest

### ISSUE THREAD

**Issue by ashcrow** [celery/kombu#682]
- Latest Index Release: https://pypi.python.org/pypi/kombu/4.0.2
- Latest GitHub Release: https://github.com/celery/kombu/releases/tag/v4.0.2
- Docs (latests is 3.0.37): http://kombu.readthedocs.io/en/latest/ and http://docs.kombu.me/en/latest/

**Comment by edmorley** [comment]
As a workaround until "latest" is pointed back at master, "stable" is correctly showing 4.x:
http://docs.celeryproject.org/projects/kombu/en/stable/changelog.html

**Comment by bmbouter** [comment]
I went to file this bug, but I found it was already filed. What needs to happen to fix this bug?

**Comment by thedrow** [comment]
We need access to RTD's admin. Unfortunately @ask is not currently available to grant us the required privileges due to personal reasons.

**Comment by thedrow** [comment]
This is now fixed. We were given admin access and ad54980ddb63e22e10c0ba66773db6c5e53e497b should fix the "not viewing docs for latest version" message.

**Comment by bmbouter** [comment]
This is great! Thank you for fixing. If you need any help keeping those things current I was a RTD admin when our project was using it. Either way thanks!
