### ISSUE TITLE
sqla transport

### ISSUE THREAD

**Issue by aminghadersohi** [celery/kombu#686]
Hi, any particular reason why 'sqla' is not listed here? 
https://github.com/celery/kombu/blob/master/kombu/transport/__init__.py#L20
The previous version, 3.1.15, supported this transport. Is it just overlooked?

**Comment by auvipy** [comment]
umm it was removed due to lack of funding and maintainer AFAIK

**Comment by arcivanov** [comment]
@aminghadersohi You might want to check https://github.com/karellen/karellen-kombu-ext

**Comment by auvipy** [comment]
But I am heavily interested to restore the support
