### ISSUE TITLE
Migation from old django-kombu

### ISSUE THREAD

**Issue by barseghyanartur** [celery/kombu#691]
Please, explain how to migrate from old [django-kombu](https://pypi.python.org/pypi/django-kombu). In the old package the following is mentioned:

> django-kombu has now moved into Kombu core, so this repository is no longer in use.
> To upgrade, install the latest Kombu version and add the following to your settings.py:
>
>    INSTALLED_APPS = (
>        "kombu.transport.django",
>    )

But, it seems that Django transport has been completely removed from the package (for good reasons, I suppose). So, please, explain how to migrate from old django-kombu to kombu.

**Comment by auvipy** [comment]
just follow the kombu docs and adjust your old code according to that :)

**Comment by barseghyanartur** [comment]
@auvipy:

Readthedocs are still at 3.0.37. I'm looking at the sources, but any help is highly appreciated.

**Comment by auvipy** [comment]
@thedrow could you also check the rtd?

**Comment by thedrow** [comment]
Unfortunately, I don't have admin access on RTD.

**Comment by auvipy** [comment]
in the mean time https://github.com/celery/kombu/tree/master/docs/userguide @barseghyanartur

**Comment by barseghyanartur** [comment]
@auvipy:

Yes, I checked that already. It doesn't say anything about migration from old Django transport. There was ever a django-kombu package, which then has been merged into kombu contrib app and then just deprecated. I have [updated](https://github.com/barseghyanartur/django-kombu) the old one (moved back the code that used to work). Would you be interested in a pull request?

**Comment by auvipy** [comment]
definitely yes :dagger:
