### ISSUE TITLE
kombu.transport.redis.Mutex is broken in python 3

### ISSUE THREAD

**Issue by zaro** [celery/kombu#701]
The Mutex class is defined as:
```python
@contextmanager
def Mutex(client, name, expire):
    """The Redis lock implementation (probably shaky)."""
    lock_id = uuid()
    i_won = client.setnx(name, lock_id)
    try:
        if i_won:
            client.expire(name, expire)
            yield
        else:
            if not client.ttl(name):
                client.expire(name, expire)
            raise MutexHeld()
    finally:
        if i_won:
            try:
                with client.pipeline(True) as pipe:
                    pipe.watch(name)
                    if pipe.get(name) == lock_id:
                        pipe.multi()
                        pipe.delete(name)
                        pipe.execute()
                    pipe.unwatch()
            except redis.WatchError:
                pass
```

The following cleanup condition:

``` python
                    if pipe.get(name) == lock_id:
```

will always fail under python 3  because lock_id is string, and the default behaviour for redis is to return bytes in python 3. This leads to the Mutex never being cleaned up. 

Changing it to :

```python
                    if pipe.get(name).decode() == lock_id:
```
fixes the problem.

**Comment by auvipy** [comment]
any failing test and proposed fix as PR?

**Comment by zaro** [comment]
@auvipy 
OK :) Got some time to figure out how to run tests. The tests use a mock Redis client, which will never show this behaviour, as the data doesn't travel over the network to Redis.

Is there any way to run the tests with actual Redis instance ?

I can make a PR with the fix, no problem, but I have no clue how to add a test case :)

**Comment by georgepsarakis** [comment]
@zaro I think you need to use the [bytes_if_py2](https://github.com/celery/vine/blob/master/vine/five.py#L202) compatibility function:

```
lock_id = bytes_if_py2(uuid())
```

**Comment by shaib** [comment]
Hi, this was relatively recently closed without explanation, but the problem is still there in Kombu 4.6.7. We run tests which include using an actual Redis rather than a mock, and when we run them with the Python flag `-bb` (make mixing bytes and string an error), we get an exception (context doesn't matter much, but our actual use case is through Celery):
```
  File ".../lib/python3.7/site-packages/kombu/transport/redis.py", line 127, in Mutex
    if pipe.get(name) == lock_id:
BytesWarning: Comparison between bytes and string
```
I am going to work on a fix.
