### ISSUE TITLE
SimpleConsumer get() race condition causing exceptions/possibly inaccurate timeouts

### ISSUE THREAD

**Issue by c-nichols** [celery/kombu#720]
When supplying a timeout perimeter to the get() method of SimpleBase, it is possible for the local variable `remaining` to be assigned a negative value, which is then used. This causes the Python socket library to throw an exception.

Also, currently the `remaining` variable does not count down time from when the method was first called. In theory, it should be close as long as there Isn't much contention for the CPU. I think it might make sense, to rewrite it so it will behave closer to "real"-time.

I would be happy to submit a pull request for this

EDIT for ease of googling, the exception message I encountered was:
`ValueError: Timeout value out of range`

**Comment by georgepsarakis** [comment]
Sounds right. Sure, feel free to provide a fix.

**Comment by benoit-intrw** [comment]
I have this same problem, is there a workaround waiting the release of this fix ?

**Comment by c-nichols** [comment]
You should be able to subclass SimpleConsumer and override the get() method with the version in my commit referenced above. That is what I have done in the meantime

**Comment by benoit-intrw** [comment]
Thank you for your answer and you patch!
