### ISSUE TITLE
Please, release a new version

### ISSUE THREAD

**Issue by koorgoo** [celery/kombu#722]
Recently I fixed kombu for ZooKeeper in #713. I could not get any response on irc.
I ask to release a new version with bumped _patch_ part, v4.0.3.

**Comment by auvipy** [comment]
we are planning to release new versions for all repo's

**Comment by koorgoo** [comment]
It is sadly to see that a patch must wait for the whole chain.
Versioning has the aim to solve cohesion - release sooner until the patch version breaks backward compatibility (and [it must not](http://semver.org/#summary)).
On the other side fixing patches must be released ASAP.

**Comment by krzysztofwolski** [comment]
@auvipy Is there any anticipated date of new release (days? weeks?)? We are also waiting for these fixes.

**Comment by thedrow** [comment]
As soon as I have the time to write the release notes and @ask has the time to perform the release.

**Comment by auvipy** [comment]
@thedrow can't we automate the release process?

**Comment by thedrow** [comment]
We can, but no has so far.

**Comment by georgepsarakis** [comment]
Related issue: #709

**Comment by lendoly** [comment]
I don't want to annoy anyone, but some advances in this area?

**Comment by thedrow** [comment]
I just got around to this. https://github.com/celery/py-amqp/pull/146 is the first step. After we'll release a new py-amqp version we'll release the new Kombu version as well.

**Comment by galuszkak** [comment]
@thedrow @auvipy I saw that new py-amqp was released, any ETA to release kombu and celery?

**Comment by thedrow** [comment]
We merged the release notes. @ask is the only one with release rights and he is unavailable at the moment.
