### ISSUE TITLE
Kombu maintainers not documented

### ISSUE THREAD

**Issue by bmbouter** [celery/kombu#756]
I am interested in knowing who are the current maintainers for the Kombu projects. I thought that information would be on this page:  http://kombu.readthedocs.io/en/latest/introduction.html#contributing

I also tried to look at the github repo, but github does not make that information public.

Can someone write out on this ticket who the current maintainers are for Kombu. Then with that information, a documentation update can be prepared.

**Comment by auvipy** [comment]
me @thedrow and @georgepsarakis I guess right now and @ask ?

**Comment by auvipy** [comment]
the mailing list should be updated too
