### ISSUE TITLE
SQS Feature Request: Support getting AWS access tokens from  ECS Task Role

### ISSUE THREAD

**Issue by dlin-me** [celery/kombu#759]
From [here](http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html)

> If you are using IAM roles on instances, you can set the BROKER_URL to: sqs:// and kombu will attempt to retrive access tokens from the instance metadata.

From Jun 2016, AWS added support for granting permissions to ECS container tasks via dedicated task role.  Instead of retrieving access tokens from EC2 instance metadata, within the container, kombu should retrieve access tokens from 

`curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`

More details available at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

**Comment by georgepsarakis** [comment]
@dlin-me SQS now works internally with boto3 which should support this feature (credential resolution) out-of-the-box.

**Comment by georgepsarakis** [comment]
@dlin-me can we close this now? If you have any other questions please let us know.

**Comment by dlin-me** [comment]
@georgepsarakis  yes, if boto3 is supported. I will check when boto3 was added. Thanks

**Comment by georgepsarakis** [comment]
@dlin-me v4.1.0 uses boto3.
