### ISSUE TITLE
Permission problem with SQS

### ISSUE THREAD

**Issue by Fiedzia** [celery/kombu#761]
AWS allows to give permission to read from specific queue, but not to list available queues.
In that case attempt to use kombu fails, because it is trying to list all queues and fails with permission error.
There is no workaround for that (other than monkeypatching).

**Comment by auvipy** [comment]
whats your suggested workaround for that?

**Comment by georgepsarakis** [comment]
@auvipy @Fiedzia the queue listing based on *prefix* happens [here](https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L107).

As an alternative the [get_queue_url](http://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.Client.get_queue_url) API call could be used, but the queue prefix support must be dropped (if it was ever intentionally supported).

**Comment by Fiedzia** [comment]
> whats your suggested workaround for that?

Main goal for me was to use celery, not Kombu directly, so I'd prefer solution that allows that.
If the current behavious is desired , one way would be to make it controllable via transport options,
another would be to have  single-queue variant of a transport.

However I don't really understand the problem that having  queue cache is trying to solve (and I don't believe it even solves it, taking into account that you may have more than one application using sqs).
The comment in code states that:

> # SQS blows up if you try to create a new queue when one already
> # exists but with a different visibility_timeout.  This prepopulates
> # the queue_cache to protect us from recreating
> # queues that are known to already exist.

couldn't this condition be simply handled by raising an exception when it will happen
and let developer deal with that? I am not sure what "blows up" mean, but does it happen in a way that allows to know the reason for it?

**Comment by georgepsarakis** [comment]
From the AWS SQS [API reference](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html):

> QueueAlreadyExists
A queue already exists with this name. Amazon SQS returns this error only if the request includes attributes whose values differ from those of the existing queue.
HTTP Status Code: 400

**Comment by georgepsarakis** [comment]
@Fiedzia your thought on letting the developer handle the error by raising a proper exception is correct, however what happens when the transport is initialized from a Celery worker? Perhaps the queue listing should be somehow converted to a transport option as you initially suggested.

**Comment by georgepsarakis** [comment]
@eruvanos #834 has been opened that addresses this issue. Can you please have a look at the solution?

**Comment by auvipy** [comment]
closing as per https://github.com/celery/kombu/pull/1156
