### ISSUE TITLE
Remove invalid function references from serialization module documentation

### ISSUE THREAD

**Issue by georgepsarakis** [celery/kombu#771]
According to this [commit](https://github.com/celery/kombu/commit/4594655066bb1f677ac1afa0d824e881056514eb), we should remove references from this [documentation file](https://github.com/celery/kombu/blob/master/docs/reference/kombu.serialization.rst).

**Comment by thedrow** [comment]
I don't see `dumps()`/`loads()` in the documentation anymore.
