### ISSUE TITLE
kombu signing key on PyPI

### ISSUE THREAD

**Issue by fladi** [celery/kombu#773]
The 4.1.0 release of kombu was signed with key 12A53B890119D176 but it seems that it is no published on public keyservers. This makes it impossible to actually verify new source tarballs for the Debian package.

**Comment by auvipy** [comment]
@thedrow

**Comment by thedrow** [comment]
I should publish my key. You're right.
Sorry about that.

**Comment by thedrow** [comment]
@fladi Which keyserver should I be using?

**Comment by fladi** [comment]
@thedrow I guess `hkp://pool.sks-keyservers.net` should be fine.

**Comment by thedrow** [comment]
@fladi I pushed the key. Can you check?

**Comment by fladi** [comment]
Worked fine, thank you!
