### ISSUE TITLE
ensure( q, q.get, ..)(block=False) fails to recover from broker shutdown

### ISSUE THREAD

**Issue by anilaratna2** [celery/kombu#776]
Our RabbitMQ broker URL points to a load balancer which has 4 brokers. 
When doing the following **block=False**
`res = connection.ensure(
                    queue,
                    queue.get,
                    **retry_policy)(block=False)`

if the broker that had the queue declared shuts down before this call, ensure() retries as expected on the exception RecoverableConnectionError('connection already closed') but eventually fails 

`Traceback (most recent call last):`
`  File "consumer.py", line 42, in <module>`
`    **retry_policy)(block=False)`
`  File "python2.7/site-packages/kombu/connection.py", line 436, in _ensured`
`    return fun(*args, **kwargs)`
 ` File "python2.7/site-packages/kombu/simple.py", line 43, in get`
`    return self.get_nowait()`
 ` File "python2.7/site-packages/kombu/simple.py", line 60, in get_nowait`
  `  m = self.queue.get(no_ack=self.no_ack)`
`  File "python2.7/site-packages/kombu/entity.py", line 587, in get`
`    message = self.channel.basic_get(queue=self.name, no_ack=no_ack)`
 ` File "python2.7/site-packages/amqp/channel.py", line 1952, in basic_get`
`    self._send_method((60, 70), args)`
`  File "python2.7/site-packages/amqp/abstract_channel.py", line 50, in _send_method`
`    raise RecoverableConnectionError('connection already closed')`
`amqp.exceptions.RecoverableConnectionError: connection already closed`

The queue created is a durable SimpleQueue with x-expires set.

The same problem DOES NOT occur with **block=True**
`res = connection.ensure(
                    queue,
                    queue.get,
                    **retry_policy)(block=True)`

and the queue moves to a new broker and consumes messages

**Comment by auvipy** [comment]
is this fixed with new release?

**Comment by auvipy** [comment]
closing as inactive.
