### ISSUE TITLE
Redis 2.10.4 or greater is required, not 2.10.0

### ISSUE THREAD

**Issue by colinjeanne** [celery/kombu#784]
Attempting to use Redis 2.10.3 with kombu will fail with `TypeError: can_read() got an unexpected keyword argument 'timeout'`. Redis only added the `timeout` parameter to this function in 2.10.4.

**Comment by georgepsarakis** [comment]
The required version seems correct in the related Celery extras [requirements file](https://github.com/celery/celery/blob/master/requirements/extras/redis.txt). You are right, the [Kombu requirements file](https://github.com/celery/kombu/blob/master/requirements/extras/redis.txt) is wrong however.
Would you like to open a Pull Request for this change?

**Comment by colinjeanne** [comment]
Sure, I'll get to this this week.

**Comment by colinjeanne** [comment]
This was fixed by #788
