### ISSUE TITLE
SQS queue name gets mangled

### ISSUE THREAD

**Issue by jkoehl** [celery/kombu#791]
Using Celery/Kombu in an environment with _future_ strings support you end up with mangled queue names in SQS.

The code that tries to translate invalid SQS queue characters causes the byte string to get converted to a string representation such as b'my_queue_name' and then translated that to 'b_my_queue_name'

I am finding this because we are using Apache Airflow in a Python 2.7 environment using SQS queues as the broker.

**Comment by georgepsarakis** [comment]
@jkoehl Airflow uses Celery 3 correct?

**Comment by jkoehl** [comment]
I and others seem are using Celery 4.x with Airflow 1.8

**Comment by auvipy** [comment]
could you plz send a pr?

**Comment by jkoehl** [comment]
I am going to try to reproduce this original issue again and then try to get a PR together with a test case. 

At the moment when I run the just the Kombu tests I am not able to reproduce it so I suspect it is specific to the combination of Airflow+Celery4+Kombu+Python 27 that made the string handling behave differently.

**Comment by jkoehl** [comment]
@auvipy I think I figured out the root cause but I am not sure how you guys want the test to be created.

The root cause is that Airflow uses the Python-future package and therefore the queue name for SQS comes in as a "newstr" and the Kombu `safe_str()` function ends up mangling the queue name in that case.

```
from kombu.utils.encoding import bytes_to_str, safe_str
from builtins import str
safe_str(str('blah')
```
`Out[4]: b'blah'`

So I think the only way I can reproduce this is to include the `future` package as a new dependency in the tests.

Do you have any thoughts on this?

**Comment by georgepsarakis** [comment]
@jkoehl thank you very much for your efforts in this issue. I have managed to reproduce it as well.

I have traced the problem to originate from [here](https://github.com/celery/kombu/blob/836512cadd23c96f23bbb5cd8f4a1bf83c36ab19/kombu/utils/encoding.py#L129), where the `newstr` type is converted to `bytes`.
I think it can be fixed by slightly modifying `_safe_str` at that point, wrapping the encoding with a new `ensure_str` function:

```
def ensure_str(s):
    if isinstance(s, bytes):
        return s.decode()
    return s

def _safe_str(s, errors='replace', file=None):  # noqa
        encoding = default_encoding(file)
        try:
            if isinstance(s, unicode):
                return ensure_str(s.encode(encoding, errors))
            return unicode(s, encoding, errors)
        except Exception as exc:
            return '<Unrepresentable {0!r}: {1!r} {2!r}>'.format(
                type(s), exc, '\n'.join(traceback.format_stack()))
```

Can you please check if this patch resolves the issue?

**Comment by jkoehl** [comment]
@georgepsarakis I updated the PR to make it pass all of the tests. I still am not sure there is a great way to write a failing test since the behavior we are handing seems specific to using the python-future model in 2.7 which we wouldn't want to bring in here.

**Comment by georgepsarakis** [comment]
@jkoehl maybe you can create in the tests a small custom sub-class of `str` for this purpose?

```
# ... or inherit from unicode?
class newstr(str):
    pass

a = newstr('asdadasdas')
print type(a)  # newstr
print isinstance(a, basestring)  # True
```
