### ISSUE TITLE
Update rabbit and warrens link

### ISSUE THREAD

**Issue by morenoh149** [celery/kombu#793]
as of august 2017 the rabbit and warrens blogpost is unreachable.

http://blogs.digitar.com/jjww/2009/01/rabbits-and-warrens/

https://github.com/celery/kombu/blob/802e77b6c3b813d17eef3695d1ae0df576eeba80/docs/includes/introduction.txt#L66

perhaps link to an archived copy? http://web.archive.org/web/20160323134044/http://blogs.digitar.com/jjww/2009/01/rabbits-and-warrens/

**Comment by auvipy** [comment]
yes plz send a pr
