### ISSUE TITLE
Connection is shut down by a quick hearbeat

### ISSUE THREAD

**Issue by xlqian** [celery/kombu#806]
I'm using a `ConsumerProducerMixin` worker to do RPC jobs which may take a long time to finish.

Surprisingly, I just discovered that, with a short heartbeat, the connection between client and server is closed repeatedly(on the `http://localhost:15672/#/queues/%2F/rpc_queue`, the consumer will disappear and reappear), however with a **bigger** heartbeat, the worker just worked like a charm. 

I seems to me that heartbeat are just missed when the worker is processing the job(in my example code: `time.sleep(50)`), according to the doc, the connection is considered 'dead' when two heartbeat are missed...

```python

from kombu import BrokerConnection, Exchange, Queue, Consumer, Producer
import time
from kombu.mixins import ConsumerProducerMixin

connection_string = 'pyamqp://guest:guest@localhost:5672?heartbeat=5' # making the heartbeat bigger, there is no problem....
connection = BrokerConnection(connection_string)

rpc_queue = Queue('rpc_queue')

with connection.channel() as channel:
    with Producer(channel) as producer:
        producer.publish('toto', routing_key='rpc_queue')


class Worker(ConsumerProducerMixin):
    """
    ConsumerProducerMixin: a RPC model
    """
    def __init__(self, connection, rpc_queue):
        self.connection = connection
        self.rpc_queue = rpc_queue

    def get_consumers(self, Consumer, channel):
        return [Consumer(
            queues=[self.rpc_queue],
            on_message=self.on_request,
            prefetch_count=1,
        )]

    def on_request(self, message):
        time.sleep(50)
        print(message.payload)
        print('OK! acking message...')
        message.ack() # You cannot ack() probably, because the connection is probably down but the exception is caught

Worker(connection, rpc_queue).run()
```

My question are:

1. To me it's weird that a quick heartbeat shutdown the connection? (in production, we put the 60s for the heartbeat, but the worker's job may last 10min) Am i missunderstanding something?

2. If so, what's the right way to do it?

**Comment by xlqian** [comment]
I read the doc again... i think i understand something and i'm doing other tests to confirm it...

**Comment by xlqian** [comment]
the heartbeat in the connection string is a server heartbeat... what i need is perhaps client heartbeats during the long processing... am i right?

**Comment by jazeltq** [comment]
I test with similar problems. Instead use BrokerConnection, i manage the connection, and that, 
the heartbeat is very fragile. 


os level:
I set keepalive time to 180, interval 3, probes 5.

rabbitmq server level:
I set heartbeat to 60

kombu connection level:
I test heartbeat either 30 or 60.

The heartbeat thread will call every 2 seconds.

The connection will shutdown for in 4 or 5 minutes. I do not very understand why.

The test code is here
`
#!/usr/bin/python

import sys
import time
import threading
from kombu import Connection,Consumer,Exchange
from kombu import Queue
import logging
from Queue import Queue as qq
from Queue import Empty


logging.basicConfig(level=10, stream=sys.stdout)
MSG_QUEUE = qq()
SHUTDOWN_EVENT = threading.Event()
H_EVENT = threading.Event()

class HeartbeatThread(threading.Thread):
     def __init__(self, conn, interval):
         super(HeartbeatThread, self).__init__()
         self.conn = conn
         self.interval = interval

     def _check(self):
         global H_EVENT
         while not H_EVENT.isSet():
             logging.debug("---%s: do heartbeat check" % threading.current_thread().name)
             logging.debug("---the interval is %s" % str(self.interval))
             try:
                 self.conn.heartbeat_check()
             except Exception as exp:
                 logging.debug("met exception %s" % exp)
                 break
             time.sleep(self.interval)

     def run(self):
         self.w = threading.Thread(target=self._check)
         self.w.start()

     def stop(self):
         global H_EVENT
         H_EVENT.set()
         self.w.join()

class CWorker(threading.Thread):
    def __init__(self, num):
        super(CWorker, self).__init__()
        self.workers = []
        for i in range(num):
            t = threading.Thread(target=self._on_msg)
            self.workers.append(t)

    def _on_msg(self):
         global MSG_QUEUE, SHUTDOWN_EVENT
         while not SHUTDOWN_EVENT.isSet():
            try:
                while not MSG_QUEUE.empty():
                    body, msg = MSG_QUEUE.get(timeout=1)
                    logging.info("%s: do msg consume" % threading.current_thread().name)
                    logging.info("body len: %d " % len(body))
                    logging.debug("ack begin")
                    #n = 5
                    #logging.debug("sleep %d s before ack" % n)
                    time.sleep(1)
                    msg.ack()
                    logging.debug("ack end")
            except Empty:
                logging.debug(">>>  queue is empty")
                continue

    def run(self):
        print ">>>>> run ..."
        for t in self.workers:
            t.start()

    def stop(self):
        SHUTDOWN_EVENT.set()
        for t in self.workers:
            # wait for queues empty
            t.join()


def on_msg(body, msg):
    global MSG_QUEUE
    logging.info("puting msg")
    MSG_QUEUE.put((body, msg))
    logging.debug("The queus size is %d" % MSG_QUEUE.qsize())
    time.sleep(1)

with Connection('amqp://guest:repaTxGNetJHQTaWcnFk3CB6E@10.0.172.45:5672',
                heartbeat=60) as conn: # hearbeat set to 60s
    w = CWorker(10) # 10 workers
    hb = HeartbeatThread(conn, 1) # 10s interval to heartbeat
    hb.start()
    w.start()

    try:
        print "go here"
        with conn.channel() as channel:
           a_ex = Exchange(name='ceilometer', type='topic', channel=channel, durable=False)
           a_queue = Queue(name="notifications.sample", exchange=a_ex, routing_key="notifications.sample",
                           channel=channel, durable=False)
           a_queue.declare()
           with Consumer(channel, [a_queue,], callbacks=[on_msg,]) as consumer:
               consumer.consume(no_ack=False)
               while True:
                   try:
                       conn.drain_events()
                   except Exception as exp:
                       logging.exception(exp)
                       consumer.cancel()
    finally:
        w.stop()
        hb.stop()
`

**Comment by auvipy** [comment]
closing for now. will reopen upon report
