### ISSUE TITLE
[feature proposal] pass whole message instead only body to load/dump in serializers

### ISSUE THREAD

**Issue by sicarrots** [celery/kombu#812]
Hi, 
I would start discussion about extending serializers. In current implementation load/dump functions receives only body of message. In my use case I want to use Apache Avro as serializer, which requires schema. One possible way is to pass schema path via message header, but in current implementation loads/dump won't recive headers from message, so this is not possible. I propose to extend current api to pass whole KombuMessage object instead only payload to serializer methods. It will be incompatible with current behavior, so before starting implementation I want to hear your opinion on that solution.

**Comment by auvipy** [comment]
sound good to me. can you elaborate more detail? you can also send pr with your proposed design

**Comment by auvipy** [comment]
can we close this issue?
