### ISSUE TITLE
Ask for help: Does there any ways to delete received messages?

### ISSUE THREAD

**Issue by Iflier** [celery/kombu#815]
Hi, I am newer to kombu. In practice, producer send messages to queue and consumer get messages from queue, before restart consumer everything goes well. But, when restart consumer and producer send only one message to queue, I can get all the messages received before restart consumer. Now, I am trying to find methods to solve it.
Thanks in advance for any help.

**Comment by eavictor** [comment]
@Iflier 
Without seeing the actual code, the community couldn't provide much help.

Please make sure ```message.ack()``` is called in consumer after all logic process finished.
Note: ```message``` is the object received from MQ(e.g. RabbitMQ).

This method acknowledge MQ that THIS message has been successfully received by consumer without any trouble, then MQ will remove this message from Queue.
