### ISSUE TITLE
warning "Bad frame read" on connection closed

### ISSUE THREAD

**Issue by vadamoto** [celery/kombu#819]
Hello, 
the following warning appears sometimes,

```
2017-12-22 02:48:14 3905 WARNING  Connection to broker lost, trying to re-establish connection...
Traceback (most recent call last):
  File "/*****/*****-******/lib/python2.7/site-packages/kombu/mixins.py", line 170, in run
    for _ in self.consume(limit=None, **kwargs):
  File "/*****/*****-******/lib/python2.7/site-packages/kombu/mixins.py", line 192, in consume
    conn.drain_events(timeout=safety_interval)
  File "/*****/*****-******/lib/python2.7/site-packages/librabbitmq/__init__.py", line 227, in drain_events
    self._basic_recv(timeout)
ConnectionError: Bad frame read
2017-12-22 02:48:14 3905 INFO     Connected to amqp://*****:**@********.***.*****.**:5672//
```
It looks like kombu reconnects immediately and works correctly after that,
but still.

A little bit more debugging showed, that function amqp_simple_wait_frame() from 
Modules/_librabbitmq/connection.c returns -7 in such cases. This code, probably, means AMQP_STATUS_CONNECTION_CLOSED defined in ./librabbitmq/amqp.h.

**Comment by auvipy** [comment]
it's suggested to use py-amqp client. plz try that and see what happend

**Comment by vadamoto** [comment]
It says here

http://docs.celeryproject.org/projects/kombu/en/latest/userguide/connections.html

> AMQP Transports
> 
> There are 4 transports available for AMQP use.
> 
>     pyamqp uses the pure Python library amqp, automatically installed with Kombu.
>     librabbitmq uses the high performance transport written in C. This requires the librabbitmq Python package to be installed, which automatically compiles the C library.
>     amqp tries to use librabbitmq but falls back to pyamqp.
>     qpid uses the pure Python library qpid.messaging, automatically installed with Kombu. The Qpid library uses AMQP, but uses custom extensions specifically supported by the Apache Qpid Broker.
> 
> For the highest performance, you should install the librabbitmq package. To ensure librabbitmq is used, you can explicitly specify it in the transport URL, or use amqp to have the fallback.

First of all, it recommends librabbitmq. I'm not sure, but it seems like librabbitmq is the one I use. At least I didn't do anything to make it otherwise. I tried it to be as close to the documentation examples as possible.

Second, it is not clear how do I use  py-amqp client (or "transport" and "client" is not the same thing?).
