### ISSUE TITLE
Timer.__iter__'s docstring is error.

### ISSUE THREAD

**Issue by j2gg0s** [celery/kombu#820]
``kombu.async.timer.Timer.__iter__`` yields a tuple of ``(wait_seconds, entry)``, not ``(entry, wait_seconds)``.

Should I provide pr to fix such small problem?
As a newcomer, I don't know if this is appropriate?

**Comment by georgepsarakis** [comment]
You are referring to this [docstring](https://github.com/celery/kombu/blob/836512cadd23c96f23bbb5cd8f4a1bf83c36ab19/kombu/async/timer.py#L183), right? I think that you are correct, yes please, all contributions are more than welcome! :smile:
