### ISSUE TITLE
Delete bindings?

### ISSUE THREAD

**Issue by bykof** [celery/kombu#831]
Hi kombu team, 
first I want to thank you for this project, it's great!

I want to create an exchange and several queues which are bound to the exchange **with multiple bindings**.
They should be persistent and bound to the exchange for a specific amount of time, but after that I want to delete **only** the bindings. 
How can I do that? 
Anyone an idea?

Thanks

**Comment by prd-hai-huynh** [comment]
Hi @bykof, @auvipy ,
Why is this issue closed?
Were you able to solve it yet?

Thank you,

**Comment by auvipy** [comment]
can you provide more detail of what you are facing?

**Comment by prd-hai-huynh** [comment]
sure, thank you for replying so fast

First of all, I used these bindings

````python
# Binding queues
app.conf.task_queues = {
    Queue(Queue.TEST_QUEUE_PRIMARY, [
        binding(Exchange.EXCHANGE_1, routing_key=RoutingKey.RK_TASK_1),
        binding(Exchange.EXCHANGE_2, routing_key=RoutingKey.RK_TASK_2),
        binding(Exchange.EXCHANGE_1, routing_key=RoutingKey.RK_TASK_3),
    ]),
    Queue(Queue.TEST_QUEUE_ADHOC, [
        binding(Exchange.EXCHANGE_1, routing_key=RoutingKey.RK_TASK_3),
    ]),
}
````

After such a time, I removed
````python
binding(OliviaExchange.EXCHANGE_1, routing_key=OliviaRoutingKey.RK_TASK_3),
````
from the queue `TEST_QUEUE_PRIMARY`
and the code should be like this:
````python
# Binding queues
app.conf.task_queues = {
    Queue(Queue.TEST_QUEUE_PRIMARY, [
        binding(Exchange.EXCHANGE_1, routing_key=RoutingKey.RK_TASK_1),
        binding(Exchange.EXCHANGE_2, routing_key=RoutingKey.RK_TASK_2),
    ]),
    Queue(Queue.TEST_QUEUE_ADHOC, [
        binding(Exchange.EXCHANGE_1, routing_key=RoutingKey.RK_TASK_3),
    ]),
}
````

and I checked on RabbitMQ broker, there was still a binding that has been removed in the code

I thought it should be removed, shouldn't they?
or did I misunderstand something?

Thank you so much for your time

**Comment by matusvalo** [comment]
Hi @prd-hai-huynh. The bindings are persistent. You need to explicitely delete it via:
1. Web UI of RabbitMQ
2. Http API of RabbitMQ
3. using Kombu, e.g.: https://docs.celeryproject.org/projects/kombu/en/master/reference/kombu.html?highlight=unbind_from#kombu.Exchange.unbind_from

Please refer the documentation of RabbitMQ and kombu.

**Comment by prd-hai-huynh** [comment]
@matusvalo 
I got it, thank you so much.
