### ISSUE TITLE
send_task in celery/app/base.py uses an invalid connection object for sending arguments to celery task

### ISSUE THREAD

**Issue by lyssalivingston** [celery/kombu#832]
I am running a Centos 6.9 VM with rabbitmq 3.7.2 in which I've installed Python 2.7.14 in a virtualenv. I am seeing a problem with send_task in celery/app/base.py getting the Wrong destination?!? message when sending the task parameters to a Celery task. I have tracked the problem to producer_or_acquire() returning an object with a valid connection object and a valid channel object that contains an invalid connection object. The invalid connection object is what's being used to send the task parameters. It does not throw a traceback, so the only way I can demonstrate this is through a backtrace in ipdb: 

```
(centos_automation) lyssa@centos6_9(392) sender
> /home/lyssa/challenge/centos_automation/automation/cli/sender.py(10)main()
      9     import ipdb; ipdb.set_trace()
---> 10     result = tasks.schedule.delay()
     11     print 'Task result:', result.get(timeout=10)
 
ipdb> tbreak /home/lyssa/.virtualenvs/centos_automation/lib/python2.7/site-packages/celery/app/base.py:734
Breakpoint 1 at /home/lyssa/.virtualenvs/centos_automation/lib/python2.7/site-packages/celery/app/base.py:734
ipdb> c
Deleted breakpoint 1
> /home/lyssa/.virtualenvs/centos_automation/lib/python2.7/site-packages/celery/app/base.py(734)send_task()
    733             producer = amqp.Producer(connection, auto_declare=False)
--> 734         with self.producer_or_acquire(producer) as P:
    735             with P.connection._reraise_as_library_errors():
 
ipdb> n
> /home/lyssa/.virtualenvs/centos_automation/lib/python2.7/site-packages/celery/app/base.py(735)send_task()
    734         with self.producer_or_acquire(producer) as P:
--> 735             with P.connection._reraise_as_library_errors():
    736                 self.backend.on_task_call(P, task_id)
 
ipdb> p P
<Producer: <promise: 0x7f6432883c80>>
ipdb> p P.connection
<Connection: amqp://admin:**@10.0.2.15:5672// at 0x7f6432888dd0>
ipdb> p P.channel.connection
<Connection: admin:password@exc_value:5672//>
ipdb>
```

Ultimately, the call to _basic_publish in librabbitmq/__init__.py:115 uses the invalid connection object from the channel. Further, I think the bad connection object is created as a result of revive() in kombu/messaging.py, but I am unfamiliar enough with the code to be absolutely certain.

I don't see any obvious option in Celery to change which connection object is used, especially since this occurs outside the direct control of my code, however, please let me know if I am missing the necessary option and what that option should be set to. I did not see this issue in the current bug list. Actually, I haven't seen anyone else having this issue, either. Here is my environment:

```
(centos_automation) lyssa@centos6_9(396) which python
/home/lyssa/.virtualenvs/centos_automation/bin/python
(centos_automation) lyssa@centos6_9(397) python --version
Python 2.7.14
(centos_automation) lyssa@centos6_9(398) uname -a
Linux centos6_9 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(centos_automation) lyssa@centos6_9(407) pip freeze
amqp==2.2.2
astroid==1.6.1
attrs==17.4.0
automation==1.0.0
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
billiard==3.5.0.3
celery==4.1.0
click==6.7
configparser==3.5.0
coverage==4.4.2
decorator==4.2.1
enum34==1.1.6
funcsigs==1.0.2
ipdb==0.10.3
ipython==5.5.0
ipython-genutils==0.2.0
isort==4.2.15
kombu==4.1.0
lazy-object-proxy==1.3.1
librabbitmq==1.6.1
mccabe==0.6.1
mock==1.0.0
pathlib2==2.3.0
pexpect==4.3.1
pickleshare==0.7.4
pika==0.11.2
pluggy==0.6.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.5.2
Pygments==2.2.0
pylint==1.8.2
pytest==3.3.2
pytest-cov==2.5.1
pytz==2017.3
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
tox==2.9.1
traitlets==4.3.2
vine==1.1.4
virtualenv==15.1.0
wcwidth==0.1.7
wrapt==1.10.11
(centos_automation) lyssa@centos6_9(408)
```

I realize this is sketchy at best so please let me know what else you may need from me if this is, indeed, a bug.

**Comment by auvipy** [comment]
it's recommended to use py-amqp instead of librabbit

**Comment by lyssalivingston** [comment]
Ah. I thought pyamqp was only for Windows? Is there a proper time to use librabbit?

**Comment by auvipy** [comment]
both going to be release new versions. if you face bottleneck on pyamqp then i guess

**Comment by lyssalivingston** [comment]
Thanks for the heads up. Not having a problem since I changed to pyamqp,
although I would really like to try librabbitmq again. I appreciate the
followup.

Lyssa
