### ISSUE TITLE
Kombu 4.1.0 - Memory usage increase (leak?) on a worker when using kombu queues

### ISSUE THREAD

**Issue by sradhakrishna** [celery/kombu#844]
Hi,

I have implemented a worker using Kombu's SimpleQueue. The implementation is as given below. When I run this worker for a few hours on a Ubuntu 16.04 system with redis as the backend, I notice a gradual memory build up on the process. When I run this worker for over a day, it ends up consuming all memory on the system and the system ends up being unusable, until the worker is killed. 

On redis server, I have it configured with a timeout set to 5 seconds and a tcp_keepalive set to 60 seconds.

Worker Code:

```
from kombu import Connection

myqueue_name = 'test_queue'
backendURL = 'redis://127.0.0.1:6379/'

def GetConnection():
    conn = Connection(backendURL)

    return conn

def dequeue():
    conn = GetConnection()
    with conn:
        myqueue = conn.SimpleQueue(myqueue_name)

        item = None

        try:
            qItem = myqueue.get(block=True, timeout=2)
            item = qItem.payload
            qItem.ack()
        except Exception as e:
            qItem = None

        myqueue.close()

    conn.close()
    conn.release()

    return item

if __name__ == '__main__':
    try:
        i = 1
        while True:
            print 'Iteration %s: %s' % (i, dequeue())
            i = i + 1
    except (KeyboardInterrupt, SystemExit):
        print 'Terminating'
```
Here's a plot of free memory on the system:

![image](https://user-images.githubusercontent.com/375461/38440168-1e96ffe2-39fe-11e8-9b89-2083cef50ddc.png)

What is going wrong here? Did I miss anything in the implementation?

Any help here will be greatly appreciated.

**Comment by sradhakrishna** [comment]
Same behavior with 4.2 from master as well. Actually, it seems worse - memory is piling up rather quick.

Am I missing anything in the code above, to kick off memory release from objects, connections/ queues etc?

**Comment by auvipy** [comment]
ask your question to mailing list/irc referencing the issue

**Comment by sradhakrishna** [comment]
I am trying to post the question on the google groups mailing list - somehow, the post doesn't show up.

@auvipy Can you help confirm this behavior?
@Everyone, any suggestions/ pointers please?

**Comment by sradhakrishna** [comment]
Addressing this issue is quite important to me - it's pretty much lines down scenario for my usecase.

Switching away from kombu to something else requires quite some time so don't seem to have many options other than fixing this.

Any way I can get attention of the community to this issue?

Any help in addressing this issue will be greatly appreciated.

**Comment by auvipy** [comment]
could you try rabbitmq? that might be a temporary solution

**Comment by sradhakrishna** [comment]
I've tried the same with rabbitmq as the backend. Saw the same behavior in that scenario too. Seems that the issue might not be in the backend specific implementation.

**Comment by auvipy** [comment]
try to find out thee leak, also I would suggest to install all the dependencies of celery from master branch to verify on master

**Comment by aviperetz34** [comment]
I am experiencing the same issue. the issue disappears when you don't use timeout and keep blocking.

**Comment by auvipy** [comment]
@pawl

**Comment by pawl** [comment]
@auvipy Nice find, it seems like this could definitely be related to: https://github.com/celery/celery/issues/4843#issuecomment-999168967

**Comment by pawl** [comment]
This may be fixed by: https://github.com/celery/kombu/pull/1476

**Comment by auvipy** [comment]
ok merged, lets see
