### ISSUE TITLE
Release 4.2

### ISSUE THREAD

**Issue by auvipy** [celery/kombu#849]

**Comment by stuartspotlight** [comment]
Is there any word on this?

**Comment by thedrow** [comment]
We haven't had the time to formalize the release process yet. I need to update our release process documents. 
The ETA is very soon.

**Comment by stuartspotlight** [comment]
Is this any further along?

**Comment by auvipy** [comment]
consider 30 may

**Comment by thedrow** [comment]
I just released Kombu 4.2.
@auvipy I'll try to work on the release process after we're done with Celery 4.2. Don't have time for it now.

**Comment by auvipy** [comment]
ok no problem. I will resume the work on celery compat issue patch.

**Comment by thedrow** [comment]
@auvipy Already resolved :)
