### ISSUE TITLE
Support rediss:// protocol to connect to redis over TLS

### ISSUE THREAD

**Issue by remeika** [celery/kombu#862]
Kombu should allow the user to pass a connection URL with [rediss://](https://www.iana.org/assignments/uri-schemes/prov/rediss) protocol  that will create a connection to redis over TLS.

**Comment by gonzalodiaz** [comment]
+1

**Comment by rnegron** [comment]
+1

**Comment by snstanton** [comment]
Yes, this is making it difficult to configure django-redis and celery using the same url scheme.  As it stands, I have to parse the rediss:// url to break it up into bite sized pieces for kombu.

**Comment by thedrow** [comment]
This is already done in master.
