### ISSUE TITLE
Serialize Exception under meta when using Task.update_state

### ISSUE THREAD

**Issue by humitos** [celery/kombu#868]
I'm trying to serialize an unhandled exception raised inside a Task into the `meta` info of the task in the `after_return` method.

The original need of this is to be able to access the exception object _and_ some metada information (filled by us) from a `FAILURE` task.

Here there is an example that produces this issue:

```python
# jsonresults.py
#
#

# python -m celery --app=jsonresults:app worker -l INFO
#

# $ python
# Python 3.6.4 (default, Mar 15 2018, 09:44:44)
# [GCC 7.3.0] on linux
# Type "help", "copyright", "credits" or "license" for more information.
# >>> import celery
# >>> celery.__version__
# '4.1.0' 
# >>> import jsonresults ; result = jsonresults.MyTask().delay()
# >>> result
# <AsyncResult: 75387cda-4998-41da-a50d-87080726d999>
# >>> result.info
# EncodeError("Object of type 'ValueError' is not JSON serializable",)
# >>>


from celery.app.base import Celery
from celery import Task

CELERY_RESULT_SERIALIZER = 'json'
BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'


app = Celery(config_source=__name__)


class MyTask(Task):
    name = 'MyTask'

    def run(self):
        raise ValueError('go away')

    def after_return(self, status, retval, task_id, args, kwargs, einfo):
        info = {}
        if status == 'FAILURE':
            info['error'] = retval
        self.update_state(state=status, meta=info)

app.tasks.register(MyTask())
```

We are using a similar code as the example in Read the Docs at https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/utils/tasks/public.py#L83

> I'm not an expert on Celery nor Read the Docs code but previously, in Celery 3.x --when the RTD code was written-- it seems this was working without problem, but now using Celery 4.x this doesn't work anymore. I'm supposing that in Celery 4.x this started to happen becase the `AsyncResult.info` is either the `result` of the task when it is `SUCCESS` _or_ the exception raised when it is `FAILURE` but we can have both.

On the other hand, the `Exception` can be JSON serialized without problem as a _result_ because Celery has mechanism for this, but it seems that code is not applied when trying to serialize the `Exception` when it's inside the `meta` information.

I also tried to have a `FAILURE` task _without_ and exception as result but our metadata dictionary and that failed on deserialization since Celery tries to find the `exc_type` and `exc_message` from our meta dictionary.

I replace the line `info['error'] = retval` from the example by `info.update(self.backend.store_result(self.request.id, retval, 'FAILURE'))` as @georgepsarakis suggested me and this did work (the `meta` was serialized properly) but I don't have a way to access to this information from the `AsyncResult` since `info` _and_ `result` are the same object/value Exception: 

```
In [2]: result = jsonresults.MyTask().delay()

In [3]: result
Out[3]: <AsyncResult: 2c5faa5b-c541-4bfa-9984-802840eea90d>

In [4]: result.result
Out[4]: celery.backends.base.ValueError('go away')

In [5]: result.info
Out[5]: celery.backends.base.ValueError('go away')
```

Finally, is there a way to have a `FAILURE` task with metadata information filled at `after_return`?

> I tried to be as clear as I could and I'm not sure if this is a problem in `kombu` or in `celery` or both. To me, it's like `kombu` _should_ serialize the exception without problem by default and `celery` _should_ provide a way to access both, exception and metadata info from a `FAILURE` task.

Always, *thanks* for this amazing framework.

Ref: https://github.com/celery/kombu/issues/573#issuecomment-387835445

**Comment by georgepsarakis** [comment]
@humitos I am not fully understanding your use case, however I think that you want to access the task metadata which can be done by either calling the `AsyncResult` protected method: 

```python
result._get_task_meta()
```

Or directly the public method `get_task_meta()` of the backend:

```python
result.backend.get_task_meta(result.id)
```

Let me know if this works.

**Comment by georgepsarakis** [comment]
@humitos any feedback on this?

**Comment by auvipy** [comment]
> @humitos I am not fully understanding your use case, however I think that you want to access the task metadata which can be done by either calling the `AsyncResult` protected method:
> 
> ```python
> result._get_task_meta()
> ```
> 
> Or directly the public method `get_task_meta()` of the backend:
> 
> ```python
> result.backend.get_task_meta(result.id)
> ```
> 
> I think the second is preferable, since it is more unlikely to change in the future, as it is public interface.
> 
> Let me know if this works.

closing for now based on this.
