### ISSUE TITLE
Has SQS fanout support via SimpleDB been removed?

### ISSUE THREAD

**Issue by robertknight** [celery/kombu#871]
Several places in the documentation, especially [this chart](http://kombu.readthedocs.io/en/latest/introduction.html#transport-comparison), state that fanout support is implemented for Amazon SQS [via SimpleDB](https://github.com/celery/kombu/search?utf8=✓&q=simpledb&type=)

However I couldn't find references to SimpleDB or some other form of routing table persistence in the actual implementation and it looks to me as though 6a1abb7e946085befb3c7ea4a3e6d703160356e4 removed the fanout support for SQS.

Can you confirm if my understanding is correct and that there isn't an alternate way of getting fanout support for SQS? I'd be happy to submit a PR to update the documentation accordingly.

**Comment by auvipy** [comment]
could you find out the commits related to removal of simpleDB?

**Comment by robertknight** [comment]
Hello @auvipy - It happened in this commit: https://github.com/celery/kombu/commit/6a1abb7e946085befb3c7ea4a3e6d703160356e4, along with many other changes.

**Comment by thedrow** [comment]
It seems that it has been removed because it did not work properly.
What would you suggest?

**Comment by dkershaw215** [comment]
looks like SimpleDB would not be a path going forward for AWS. Is there another option to implement?

**Comment by thedrow** [comment]
> looks like SimpleDB would not be a path going forward for AWS. Is there another option to implement?

Fanout using SNS. See [this](https://aws.amazon.com/getting-started/tutorials/send-fanout-event-notifications/) for details.

**Comment by auvipy** [comment]
closing as resolved
