### ISSUE TITLE
Different safe_str behavior between 4.1.0 and 4.2.0 with Python 2.7

### ISSUE THREAD

**Issue by selimt** [celery/kombu#874]
Hi, we use the kombu.utils.encoding.safe_str method to handle the encoding of unicode strings in Python 2.7. Between kombu 4.1.0 and 4.2.0 we are getting different results:

```
> setenv LANG en_US.UTF-8
> pip install kombu==4.1.0 --user
> python
>>> f = u'Ame\u0301lie'
>>> print f
Amélie
>>> from kombu.utils.encoding import safe_str
>>> safe_str(f)
'Ame\xcc\x81lie'
```
vs
```
> pip install kombu==4.2.0 --user
> python
>>> f = u'Ame\u0301lie'
>>> print f
Amélie
>>> from kombu.utils.encoding import safe_str
>>> safe_str(f)
u'Ame\u0301lie'
```

Looks like this change is due to this commit:

https://github.com/celery/kombu/commit/39e733c14347f982e38e27c9f9edd7c400798e69

The problem we are having is that if we try to call safe_str on a unicode string and try to write it to a file, we get a UnicodeEncode error:

```
>>> import tempfile
>>> f = u'Ame\u0301lie\n'
>>> with tempfile.NamedTemporaryFile(dir='/tmp', delete=False) as manifest:
...   manifest.write(safe_str(f))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 3: ordinal not in range(128)
```

Thanks in advance
-Selim

**Comment by georgepsarakis** [comment]
You need to use the [codecs module](https://docs.python.org/2/library/codecs.html) for writing UTF-8 strings to files. Check this StackOverflow answer https://stackoverflow.com/a/934173/920374 .

**Comment by georgepsarakis** [comment]
@selimt do you think we can close this?

**Comment by selimt** [comment]
Hi George, yes the codecs module can be used for this but I was hoping for a more general solution since it can not be easily incorporated with tempfile. For now we copied the old safe_str implementation into our code until we find a better solution or switch to Python 3.

You can go ahead and close this issue.

Thanks
-Selim

**Comment by georgepsarakis** [comment]
@selimt thanks a lot for the feedback.
