### ISSUE TITLE
Celery started pulling in Kombu 4.2.0 which is breaking with KeyError 'async'

### ISSUE THREAD

**Issue by robvdl** [celery/kombu#877]
We had a working application, but since Celery isn't pinning Kombu properly (it really should to avoid this sort of thing), things started failing in our application the minute Kombu 4.2.0 was released.

Rolled back to Kombu 4.1.0 in the mean time because 4.2.0 seems to be broken, we are using Python 3.4

Crash is in kombu/transport/base.py, line 123 (return self[key])

It raises KeyError 'async'

**Comment by FrankWangAU** [comment]
What is your celery version?
if want to use 4.2.0, you have to use celery 4.1.1.

Check this:
https://github.com/celery/kombu/issues/870

**Comment by kibernick** [comment]
We have the same issue. As part of an airflow installation, we got the latests celery library - which got the kombu version 4.2.0, and now this error appears.

**Comment by clokep** [comment]
Kombu 4.2.0 is compatible with Celery 4.1.1 o r 4.2.0RC4. Updating your Celery or pining kombu to 4.1.0 should fix the issue.

**Comment by robvdl** [comment]
Ok, good to know, it would be nice if Celery did a slightly better job of pinning dependencies though, but that isn't a kombu issue.. it's a celery issue.
