### ISSUE TITLE
connection.heartbeat_check does not seem to heartbeat?

### ISSUE THREAD

**Issue by acee87** [celery/kombu#894]
I was trying to rely on the heartbeat feature to allow the connection be closed if something seems to have hung. However, I'm not sure if I'm using the heartbeat_check call properly, because in all my tests with heartbeats enabled in the connection, my connection always gets closed with "Too many heartbeats missed" even though I am constantly calling connection.heartbeat_check().

In the most stripped down example I have, my code looks like this (where I do nothing but heartbeat):
```
import time
import kombu

connection = kombu.Connection('pyamqp://localhost:5672', 
	transport_options={'confirm_publish': True},
	connect_timeout=5,
	heartbeat=5)

connection.connect()

while True:
	print('Heartbeat')
	connection.heartbeat_check()
	time.sleep(1)
```
It seems to be that, consistently, after approximately 2x heartbeat seconds have passed, the connection is closed with the exception:
```
(venv-kombu) ~/src$ python test-kombu.py 
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Heartbeat
Traceback (most recent call last):
  File "test-kombu.py", line 33, in <module>
    connection.heartbeat_check()
  File "/home/eea/src/venv-kombu/lib/python3.5/site-packages/kombu/connection.py", line 290, in heartbeat_check
    return self.transport.heartbeat_check(self.connection, rate=rate)
  File "/home/eea/src/venv-kombu/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 149, in heartbeat_check
    return connection.heartbeat_tick(rate=rate)
  File "/home/eea/src/venv-kombu/lib/python3.5/site-packages/amqp/connection.py", line 704, in heartbeat_tick
    raise ConnectionForced('Too many heartbeats missed')
amqp.exceptions.ConnectionForced: Too many heartbeats missed
```
I feel like I'm misunderstanding about how the heartbeats are supposed to work - what might I be missing?

This is with:
```
amqp==2.2.2
kombu==4.1.0
pkg-resources==0.0.0
vine==1.1.4
```

**Comment by olii** [comment]
You actually have to read the heartbeat from the server. Use a call that reads from server. Heartbeat is calculated from incomming bytes.

```
import time
import kombu

connection = kombu.Connection('pyamqp://localhost:5672',
    transport_options={'confirm_publish': True},
    connect_timeout=5,
    heartbeat=5)

connection.connect()

while True:
    print('Heartbeat')
    try:
        connection.drain_events(timeout=0.1)
    except Exception:
        pass
    connection.heartbeat_check()
    time.sleep(1)
```

**Comment by acee87** [comment]
Ah, I did not realize that! My application only publishes messages (never consumes), so I didn't realize I had to still call drain_events in this case. Thank you for the explanation.
