### ISSUE TITLE
q: where/what is the broker component for pyro transport?

### ISSUE THREAD

**Issue by irmen** [celery/kombu#897]
Hi, in #895 I've done some work to get the Pyro transport working.
I'm now stuck on the following: 
Where is the pyro broker component that should provide the actual queueing methods that are remotely accessed from the Pyro transport? I see nothing in the kombu repo doing this, and can't find anything via google. Is there such a thing or should I write it myself? What should it do exactly?

(example: https://github.com/celery/kombu/blob/master/kombu/transport/pyro.py#L30  where it invokes get_queue_names on some remote Pyro object that is in self.shared_queues.... )

**Comment by irmen** [comment]
Right, I went ahead and implemented a minimal Broker myself see 82843166cc894f9adbc71ebc77cd9903da226e16

I'm going at it without really knowing what it should really do, but the version I included does work at least in a correct enough way that I successfully ran the hello_consumer/hello_producer example using the Pyro protocol. (``pyro://localhost/kombu.broker`` url)

Would love some feedback / help :smile:

**Comment by auvipy** [comment]
shouldn't we close this?

**Comment by irmen** [comment]
It could be closed, but be advised that my preliminary implementation of the broker for the pyro transport is based on very little understanding of the more complex internals of kombu. I couldn't get some example code to run with it, it only works with the "simple interface" and I lack the knowledge to extend it to work with the example code that uses Queue/Exchange api, which seems to be kombu's "real" api so to speak.
