### ISSUE TITLE
Support byte array "x" field table type

### ISSUE THREAD

**Issue by daviskirk** [celery/kombu#913]
Currently, the field type "x" which is supported by rabbit and qpid is not supported in kombu.  The field type represents a byte array.  Pika and a few other libraries support this type.  From looking at the code one should be able to add it in the serialization.py but up until now I have not been able to do so successfully. 
Are there any plans on supporting this or perhaps reasons why it is not supported?

https://github.com/pika/pika/blob/4ec4a42c894326ae0798d7f3a5efd7a18e04b191/pika/data.py#L290

**Comment by thedrow** [comment]
We do support it but didn't serialize the data correctly.
See https://github.com/celery/py-amqp/pull/264 for details.

This is going to be fixed very soon anyway, so I'll close this one if you don't mind.
