### ISSUE TITLE
kombu.me is down

### ISSUE THREAD

**Issue by Kyle-Verhoog** [celery/kombu#930]
The README has a link to http://kombu.me, but the website appears to be down.

![screen shot 2018-10-12 at 5 24 42 pm](https://user-images.githubusercontent.com/6321485/46878521-d0710a80-ce43-11e8-8aad-c4f4425581bc.png)

**Comment by auvipy** [comment]
actually its the old link, new one is on read the docs

**Comment by Kyle-Verhoog** [comment]
resolved with #935
