### ISSUE TITLE
removal of kombu-4.2.2 from pypi

### ISSUE THREAD

**Issue by prometheanfire** [celery/kombu#974]
During/after 4.2.2-post1 was published 4.2.2 was removed.  This broke openstack gate :|  Was there a reason for it's removal?

https://storyboard.openstack.org/#!/story/2004685

**Comment by thedrow** [comment]
The release was made from master by accident.
It contained code which should not have been released and causes errors in production.
We will create a more automated release process soon which will prevent such problems in the future.
My apologies for the inconvenience this may have caused.

**Comment by thedrow** [comment]
See #996.

**Comment by nkuttler** [comment]
Which release was made by accident, 4.2.2? Should we downgrade to 4.2.1 for now, or is post1 a proper release?

#996 doesn't seem to exist

**Comment by prometheanfire** [comment]
ok, thanks.  closing this in favor of #966
