### ISSUE TITLE
base64.b64decode raises TypeError, not KeyError

### ISSUE THREAD

**Issue by homm** [celery/kombu#977]
There is handling for `KeyError` which could occur in `message['Body']` expression, but it is repeated in the except clause, and this is why it is meaningless. I believe it should be handling for `TypeError`, which could occur in `base64.b64decode` function.

https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L232-L235

The error was introduced in https://github.com/celery/kombu/commit/01ab1a7

**Comment by georgepsarakis** [comment]
@homm you are right. The exception handling was introduced in https://github.com/celery/kombu/pull/937 and accounts for non-base64 encoded messages, in which case a `TypeError` is raised.

**Comment by thedrow** [comment]
Fixed in https://github.com/celery/kombu/commit/139f68de23b7e2e56272deef247f4170448a26ae.
I mentioned the wrong issue by accident.
