### ISSUE TITLE
Failing testcase on master

### ISSUE THREAD

**Issue by physicalattraction** [celery/kombu#980]
I found the following error in the test suite on master. I have the following in my local `~/.aws/config`:

```
[default]
region = eu-central-1
```

When I change this region to eu-west-1, then it complains that eu-west-1 is not us-east-1, so it is indeed reading this configuration. I do not want to change my local environment, a test case shouldn't depend on a local configuration. Why is this test there in the first place?

```
    def test_region(self):
        import boto3
        _environ = dict(os.environ)

        # when the region is unspecified
        connection = Connection(transport=SQS.Transport)
        channel = connection.channel()
        assert channel.transport_options.get('region') is None
        # the default region is us-east-1
>       assert channel.region == 'us-east-1'
E       AssertionError: assert 'eu-central-1' == 'us-east-1'
E         - eu-central-1
E         + us-east-1

t/unit/transport/test_SQS.py:191: AssertionError
```

**Comment by thedrow** [comment]
I agree this is annoying. I think that we should mock the underlying boto implementation.
We're checking boto's behavior here which is irrelevant.

**Comment by thedrow** [comment]
It is checking what the `region` property is returning.
It's a legitimate unit test in my opinion.

**Comment by auvipy** [comment]
this is probably already fixed
