### ISSUE TITLE
Kombu 4.3 Release

### ISSUE THREAD

**Issue by auvipy** [celery/kombu#999]

**Comment by thedrow** [comment]
I'm currently writing the release notes.

**Comment by auvipy** [comment]
thanks for handling this!!

**Comment by thedrow** [comment]
Build is passing, changelog is done.
I'm going to wait 30 minutes to see if anyone has any objections and then release Kombu.

**Comment by auvipy** [comment]
awesome go for it!!

**Comment by thedrow** [comment]
DONE!
